/* AI in Motion — Artificial Intelligence track. © Janin A Apurba, CSE, AUST */
module.exports = [
  {
    slug: 'what-is-artificial-intelligence', title: 'What Is Artificial Intelligence?', track: 'ai', level: 'Beginner', poster: 1,
    summary: 'A clear, visual introduction: what AI is, how modern AI learns from data, and how AI, machine learning and deep learning fit together.',
    scenes: [
      { kit: 'title', title: 'What Is Artificial Intelligence?', sub: 'The big picture in three minutes', track: 'Artificial Intelligence', chapter: 'Introduction', say: 'Welcome to AI in Motion. In this first lesson we answer a simple question: what exactly is artificial intelligence? No jargon, just pictures.' },
      { kit: 'definition', term: 'Artificial Intelligence', def: 'Building computer systems that perform tasks we normally associate with human intelligence: seeing, understanding language, reasoning, planning and learning.', eg: 'recognising a face, translating a sentence, recommending a song', chapter: 'Definition', say: 'Artificial intelligence is the science of building computer systems that do things we normally link with human intelligence. Seeing, understanding language, reasoning, planning and learning.' },
      { kit: 'nested', head: 'AI, machine learning and deep learning', rings: [{ label: 'Artificial Intelligence', note: 'Any technique that makes machines act intelligently' }, { label: 'Machine Learning', note: 'Systems that learn patterns from data' }, { label: 'Deep Learning', note: 'Learning with many-layered neural networks' }, { label: 'Generative AI', note: 'Deep models that create text, images and audio' }], chapter: 'The family tree', say: 'These terms are nested circles. Artificial intelligence is the whole field. Machine learning is the part that learns from data. Deep learning uses many-layered neural networks. And generative AI, like chatbots and image generators, sits inside deep learning.' },
      { kit: 'compare', head: 'Two ways to build intelligence', left: { title: 'Rules written by people', items: ['Experts write if–then rules', 'Easy to explain', 'Breaks on messy, new situations'], color: 'amber' }, right: { title: 'Learning from data', items: ['Show thousands of examples', 'The model finds the patterns', 'Handles images, speech and language'], color: 'cyan' }, chapter: 'Rules vs learning', say: 'Early AI relied on rules written by human experts. That works for tidy problems, but real life is messy. Modern AI mostly learns from examples instead, finding the patterns itself.' },
      { kit: 'cycle', head: 'How modern AI learns', steps: ['Data', 'Train', 'Model', 'Predict', 'Feedback'], desc: ['Collect many examples', 'Adjust the model to fit them', 'The learned patterns', 'Apply to new inputs', 'Learn from mistakes'], chapter: 'The learning loop', say: 'Most modern AI follows a loop. Collect data. Train a model on it. Use the model to make predictions on new inputs. Then use feedback and fresh data to improve it again.' },
      { kit: 'compare', head: 'Narrow AI vs general AI', left: { title: 'Narrow AI (today)', items: ['Excellent at one kind of task', 'Chess, translation, face unlock', 'Every AI system in use today'], color: 'green' }, right: { title: 'General AI (hypothetical)', items: ['Human-level at any task', 'Transfers knowledge freely', 'Does not exist yet'], color: 'violet' }, chapter: 'Narrow vs general', say: 'All the AI we use today is narrow AI. It can be superhuman at one kind of task, but it cannot do everything a person can. General AI, matching humans at any task, does not exist yet.' },
      { kit: 'bullets', style: 'recap', items: ['AI — machines doing tasks that need intelligence', 'Machine learning — learning patterns from data', 'Deep learning — many-layered neural networks', 'Today’s AI is narrow — brilliant at specific tasks'], chapter: 'Recap', say: 'To recap. AI is the broad goal. Machine learning learns from data. Deep learning uses deep neural networks. And every AI system today is narrow, brilliant at specific tasks.' }
    ],
    takeaways: ['AI builds systems that perform tasks associated with human intelligence.', 'Machine learning is the part of AI that learns from data; deep learning uses deep neural networks.', 'Modern AI mostly learns from examples rather than hand-written rules.', 'All AI in use today is narrow AI.'],
    quiz: [
      { q: 'Which statement about AI, ML and deep learning is correct?', a: ['Deep learning contains machine learning', 'Machine learning is a subset of AI, and deep learning is a subset of machine learning', 'They are three unrelated fields'], c: 1, why: 'They are nested: AI ⊃ machine learning ⊃ deep learning.' },
      { q: 'How do most modern AI systems gain their abilities?', a: ['By learning patterns from example data', 'By copying human brains cell by cell', 'By following rules typed in by experts only'], c: 0, why: 'Modern AI mostly learns from large amounts of example data.' },
      { q: 'A face-unlock feature on a phone is an example of…', a: ['General AI', 'Narrow AI', 'Superintelligence'], c: 1, why: 'It does one task very well — that is narrow AI.' }
    ],
    read: ['what-is-artificial-intelligence', 'landscape-of-modern-ai', 'narrow-general-and-super-intelligence']
  },
  {
    slug: 'history-of-ai', title: 'A Short History of AI', track: 'ai', level: 'Beginner', poster: 1,
    summary: 'From Alan Turing to ChatGPT in one animated timeline — the breakthroughs, the “AI winters” and the ideas that changed everything.',
    scenes: [
      { kit: 'title', title: 'A Short History of AI', sub: 'Seventy years in five minutes', track: 'Artificial Intelligence', chapter: 'Introduction', say: 'Artificial intelligence is older than most people think. Let us travel through seventy years of ideas, hype, disappointment and breakthroughs.' },
      { kit: 'timeline', head: 'The early years', events: [['1950', 'Turing asks: can machines think?'], ['1956', 'Dartmouth workshop names the field'], ['1958', 'Rosenblatt’s perceptron'], ['1966', 'ELIZA chatbot'], ['1970s', 'First “AI winter”']], chapter: 'The early years', say: 'In 1950 Alan Turing asked whether machines can think. In 1956 the Dartmouth workshop gave the field its name. Rosenblatt built the perceptron in 1958, and ELIZA chatted with people in 1966. But promises outran results, and funding dried up in the first AI winter.' },
      { kit: 'timeline', head: 'Knowledge, games and data', events: [['1980s', 'Expert systems boom'], ['1986', 'Backpropagation popularised'], ['Late 80s', 'Second AI winter'], ['1997', 'Deep Blue beats Kasparov'], ['2011', 'Watson wins Jeopardy!']], chapter: 'Expert systems to Deep Blue', say: 'The 1980s brought expert systems, rule-based programs used by businesses. Backpropagation was popularised in 1986, but another winter followed. In 1997 IBM’s Deep Blue beat world chess champion Garry Kasparov.' },
      { kit: 'timeline', head: 'The deep learning era', events: [['2012', 'AlexNet wins ImageNet'], ['2016', 'AlphaGo beats Lee Sedol'], ['2017', 'The Transformer'], ['2020', 'GPT-3'], ['2022', 'ChatGPT goes public']], chapter: 'Deep learning era', say: 'In 2012 a deep neural network called AlexNet crushed an image recognition contest, starting the deep learning era. AlphaGo beat a Go champion in 2016. The Transformer arrived in 2017, powering the large language models behind ChatGPT, released in 2022.' },
      { kit: 'pipeline', head: 'Why progress accelerated', steps: ['More data', 'Faster GPUs', 'Better algorithms', 'Open research'], desc: ['The internet created huge labelled and unlabelled datasets.', 'Graphics chips made training large neural networks practical.', 'Ideas like ReLU, dropout, residual connections and attention.', 'Shared papers, code and benchmarks let the field move quickly.'], chapter: 'Why now?', say: 'Why did progress speed up? Four ingredients arrived together. Massive data from the internet. Fast graphics processors. Better training ideas. And an open research culture that shared code and results.' },
      { kit: 'bullets', style: 'recap', items: ['1950s — the question and the name', '1980s — expert systems and backpropagation', '2012 — deep learning takes off', '2017 onwards — transformers and generative AI'], chapter: 'Recap', say: 'The story in four beats. The question and the name in the fifties. Expert systems in the eighties. Deep learning from 2012. And transformers and generative AI since 2017.' }
    ],
    takeaways: ['The term “artificial intelligence” dates from the 1956 Dartmouth workshop.', 'Periods of hype were followed by “AI winters” when results disappointed.', 'Deep learning took off around 2012 thanks to data, GPUs and better algorithms.', 'The 2017 Transformer architecture underpins today’s large language models.'],
    quiz: [
      { q: 'Which event is usually seen as the start of the deep learning era?', a: ['Deep Blue in 1997', 'AlexNet winning ImageNet in 2012', 'ELIZA in 1966'], c: 1, why: 'AlexNet’s 2012 ImageNet win showed deep neural networks could beat other methods by a wide margin.' },
      { q: 'What was an “AI winter”?', a: ['A period of reduced funding and interest after hype', 'A cold-weather robot test', 'A type of neural network'], c: 0, why: 'AI winters followed periods where promises exceeded results.' },
      { q: 'Which 2017 architecture powers modern language models?', a: ['The perceptron', 'The Transformer', 'Expert systems'], c: 1, why: 'The Transformer, introduced in 2017, is the basis of today’s LLMs.' }
    ],
    read: ['history-of-ai', 'turing-test-and-its-critics', 'expert-systems-rule-based-ai']
  },
  {
    slug: 'intelligent-agents', title: 'Intelligent Agents: Perceive, Decide, Act', track: 'ai', level: 'Beginner', poster: 1,
    summary: 'Watch a robot vacuum perceive its world, decide and act — the agent loop that underlies everything from thermostats to AI assistants.',
    scenes: [
      { kit: 'title', title: 'Intelligent Agents', sub: 'Perceive, decide, act — repeat', track: 'Artificial Intelligence', chapter: 'Introduction', say: 'In AI, an agent is anything that perceives its environment and acts on it to achieve a goal. Let us watch one at work.' },
      { kit: 'agent', chapter: 'A cleaning agent', say: 'Here is a simple robot vacuum. Its sensor perceives whether the current square is dirty. A rule decides what to do. If dirty, suck. If clean, move on. Its performance is measured by how many squares it cleans.' },
      { kit: 'cycle', head: 'The agent loop', steps: ['Perceive', 'Decide', 'Act', 'Learn'], desc: ['Sensors read the environment', 'Choose the best action for the goal', 'Actuators change the world', 'Improve from the results'], chapter: 'The agent loop', say: 'Every agent runs the same loop. Perceive through sensors. Decide what to do. Act through actuators. And the best agents also learn from the results, getting better over time.' },
      { kit: 'bullets', head: 'Types of agents', items: ['Simple reflex — if–then rules on the current percept, like a thermostat', 'Model-based — keeps an internal map of the world', 'Goal-based — plans actions to reach a goal, like a route planner', 'Utility-based — weighs trade-offs to pick the best outcome', 'Learning — improves its behaviour from experience'], chapter: 'Types of agents', say: 'Agents come in levels of sophistication. Simple reflex agents follow if-then rules. Model-based agents remember the world. Goal-based agents plan. Utility-based agents weigh trade-offs. And learning agents improve with experience.' },
      { kit: 'pipeline', head: 'PEAS: describing any agent', steps: ['Performance', 'Environment', 'Actuators', 'Sensors'], desc: ['How success is measured: squares cleaned, time taken, energy used.', 'The world it operates in: rooms, dirt, furniture.', 'What it can do: wheels, brushes, suction.', 'What it can perceive: dirt sensor, bump sensor, camera.'], chapter: 'PEAS', say: 'To design an agent, describe it with PEAS. Performance measure, environment, actuators and sensors. For our vacuum, that is squares cleaned, the rooms, wheels and suction, and a dirt sensor.' },
      { kit: 'bullets', style: 'recap', items: ['An agent perceives its environment and acts on it', 'Sensors in, actuators out, a decision in between', 'Agents range from reflex rules to learning systems', 'Describe any agent with PEAS'], chapter: 'Recap', say: 'Remember: an agent perceives and acts. Sensors bring information in, actuators change the world. Agents range from simple rules to learning systems, and PEAS describes any of them.' }
    ],
    takeaways: ['An agent perceives its environment and acts on it to achieve goals.', 'Agents range from simple reflex rules to learning systems.', 'PEAS — performance, environment, actuators, sensors — describes any agent.', 'Modern AI assistants that use tools follow the same perceive–decide–act loop.'],
    quiz: [
      { q: 'A thermostat that switches heating on below 20 °C is what kind of agent?', a: ['Simple reflex agent', 'Learning agent', 'Utility-based agent'], c: 0, why: 'It applies an if–then rule to the current percept.' },
      { q: 'In PEAS, what does the “A” stand for?', a: ['Algorithms', 'Actuators', 'Accuracy'], c: 1, why: 'Actuators are how the agent acts on its environment.' },
      { q: 'Which step comes between perceiving and acting?', a: ['Deciding', 'Sleeping', 'Labelling'], c: 0, why: 'The agent decides which action best serves its goal.' }
    ],
    read: ['intelligent-agents-and-environments', 'ai-agents-tool-use']
  },
  {
    slug: 'breadth-first-and-depth-first-search', title: 'Breadth-First vs Depth-First Search', track: 'ai', level: 'Beginner', poster: 1,
    summary: 'Watch two classic search algorithms explore the same maze — one in ripples, one in deep dives — and see why only one guarantees the shortest path.',
    scenes: [
      { kit: 'title', title: 'Breadth-First vs Depth-First Search', sub: 'How AI explores a maze', track: 'Artificial Intelligence', chapter: 'Introduction', say: 'Many AI problems are really search problems. From a start state, explore possible moves until you reach a goal. Let us compare two classic ways to explore.' },
      { kit: 'grid-search', algo: 'bfs', sub: 'explores in ripples, closest cells first', chapter: 'Breadth-first search', say: 'Breadth-first search explores in ripples. It visits every cell one step away, then every cell two steps away, and so on. Amber cells are waiting in the queue. Because it expands by distance, the first time it reaches the goal, it has found a shortest path: here, 37 moves.' },
      { kit: 'grid-search', algo: 'dfs', sub: 'dives as deep as possible, then backtracks', chapter: 'Depth-first search', say: 'Depth-first search dives down one path as far as it can, and only backtracks at dead ends. It uses a stack instead of a queue. It found the goal, but look at the path. It is 73 moves long, nearly twice the shortest route.' },
      { kit: 'compare', head: 'Queue vs stack', left: { title: 'Breadth-first (queue)', items: ['First in, first out', 'Finds the shortest path when every step costs the same', 'Needs lots of memory on big problems'], color: 'cyan' }, right: { title: 'Depth-first (stack)', items: ['Last in, first out', 'Uses little memory', 'No guarantee of the shortest path'], color: 'pink' }, chapter: 'Queue vs stack', say: 'The only difference is the data structure. Breadth-first uses a queue, first in first out. Depth-first uses a stack, last in first out. That one choice changes everything about how they behave.' },
      { kit: 'bars', head: 'On our maze', labels: ['BFS explored', 'DFS explored', 'BFS path', 'DFS path'], values: [205, 185, 37, 73], unit: 'cells / moves', chapter: 'Results', say: 'On this maze, breadth-first explored 205 cells and found a 37-move path. Depth-first explored slightly fewer, 185 cells, but its path was 73 moves. Cheaper exploration, much worse answer.' },
      { kit: 'bullets', style: 'recap', items: ['BFS — explores level by level with a queue', 'BFS finds the shortest path when all moves cost the same', 'DFS — dives deep with a stack, uses little memory', 'Neither uses any hint about where the goal is'], chapter: 'Recap', say: 'To recap. Breadth-first explores level by level and finds shortest paths. Depth-first dives deep and saves memory. Both are uninformed: they have no idea where the goal is. Next, we will fix that with A star.' }
    ],
    takeaways: ['Breadth-first search uses a queue and finds a shortest path when all steps cost the same.', 'Depth-first search uses a stack, needs little memory, but can return long paths.', 'On our maze: BFS 205 cells explored and a 37-move path; DFS 185 cells and a 73-move path.', 'Both are uninformed — they don’t know where the goal is.'],
    quiz: [
      { q: 'Which data structure does breadth-first search use?', a: ['A stack', 'A queue', 'A tree of priorities'], c: 1, why: 'BFS explores oldest-discovered cells first: first in, first out.' },
      { q: 'Which algorithm guarantees a shortest path when every move costs the same?', a: ['Depth-first search', 'Breadth-first search', 'Neither'], c: 1, why: 'BFS expands in order of distance, so its first path to the goal is shortest.' },
      { q: 'Why are BFS and DFS called “uninformed”?', a: ['They use no information about where the goal is', 'They were invented before computers', 'They cannot find the goal'], c: 0, why: 'They explore without any estimate of distance to the goal.' }
    ],
    read: ['uninformed-search-strategies']
  },
  {
    slug: 'a-star-search', title: 'A* Search: Smarter Pathfinding', track: 'ai', level: 'Intermediate', poster: 1,
    summary: 'A* combines the cost so far with an estimate of the cost remaining. Watch it head for the goal and find the same shortest path while exploring fewer cells.',
    scenes: [
      { kit: 'title', title: 'A* Search', sub: 'The pathfinding algorithm behind maps and games', track: 'Artificial Intelligence', chapter: 'Introduction', say: 'Every time a game character walks around a wall or a map app plans a route, there is a good chance A star is involved. Published in 1968, it is still everywhere.' },
      { kit: 'equation', head: 'The key idea', parts: [{ t: 'f(n)', c: 'amber', note: 'f is the estimated total cost of a path through cell n' }, { t: ' = ' }, { t: 'g(n)', c: 'cyan', note: 'g is the real cost from the start to n — the steps already taken' }, { t: ' + ' }, { t: 'h(n)', c: 'pink', note: 'h is a heuristic: an estimate of the cost from n to the goal' }], below: 'A* always explores the cell with the lowest f next', chapter: 'f = g + h', say: 'A star scores every cell with f equals g plus h. G is the cost already travelled from the start. H is a heuristic, an estimate of the distance still to go. A star always explores the cell with the lowest total f next.' },
      { kit: 'grid-search', algo: 'astar', sub: 'guided by the Manhattan-distance heuristic', chapter: 'Watching A*', say: 'Here is A star on the same maze. Watch the numbers at the top: f equals g plus h for the current cell. Instead of spreading evenly, it leans towards the goal, and only explores detours when walls force it to.' },
      { kit: 'bars', head: 'Same maze, same shortest path', labels: ['Breadth-first', 'A*', 'Greedy best-first'], values: [205, 161, 76], unit: 'cells explored', hl: 1, chapter: 'Comparison', say: 'All three found the same 37-move path here. Breadth-first explored 205 cells, A star 161. Greedy search, which only looks at h, explored just 76, but greedy search is not guaranteed to find the shortest path in general. A star is, if its heuristic never overestimates.' },
      { kit: 'grid-search', algo: 'greedy', sub: 'only looks at h — fast, but no guarantee', chapter: 'Greedy search', say: 'This is greedy best-first search. It chases whatever looks closest to the goal. On this maze it got lucky. On other mazes it can walk into long detours, because it ignores the cost already paid.' },
      { kit: 'bullets', style: 'recap', items: ['f = g + h — cost so far plus estimated cost remaining', 'Always expand the cell with the lowest f', 'Admissible heuristic (never overestimates) → shortest path guaranteed', 'Explores fewer states than blind search'], chapter: 'Recap', say: 'Remember. A star uses f equals g plus h. It always expands the lowest f. With a heuristic that never overestimates, it is guaranteed to find a shortest path, usually with far less exploration than blind search.' }
    ],
    takeaways: ['A* scores cells with f = g + h and explores the lowest f first.', 'With an admissible heuristic, A* is guaranteed to find a shortest path.', 'On our maze: BFS explored 205 cells, A* 161, greedy 76 — all found the 37-move path.', 'Greedy best-first search is fast but not guaranteed to be optimal.'],
    quiz: [
      { q: 'In f(n) = g(n) + h(n), what is h(n)?', a: ['The exact cost so far', 'An estimate of the remaining cost to the goal', 'The number of cells explored'], c: 1, why: 'h is the heuristic estimate of the distance still to go.' },
      { q: 'When is A* guaranteed to find a shortest path?', a: ['When its heuristic never overestimates the true remaining cost', 'Always, whatever the heuristic', 'Only on grids without walls'], c: 0, why: 'An admissible heuristic guarantees optimality.' },
      { q: 'Greedy best-first search chooses cells using…', a: ['Only g', 'Only h', 'g + h'], c: 1, why: 'Greedy search ignores the cost so far and chases the smallest estimate.' }
    ],
    read: ['informed-search-a-star', 'uninformed-search-strategies']
  },
  {
    slug: 'minimax-and-alpha-beta', title: 'Minimax and Alpha–Beta Pruning', track: 'ai', level: 'Intermediate', poster: 2,
    summary: 'How game-playing AI thinks ahead: MAX and MIN take turns, values flow up the tree, and alpha–beta pruning skips branches that cannot matter.',
    scenes: [
      { kit: 'title', title: 'Minimax and Alpha–Beta', sub: 'How game-playing AI looks ahead', track: 'Artificial Intelligence', chapter: 'Introduction', say: 'How does a computer play chess or tic-tac-toe? It imagines future moves for both players and assumes the opponent plays their best. That idea is called minimax.' },
      { kit: 'bullets', head: 'Two players, opposite goals', items: ['MAX — the AI, wants the highest score', 'MIN — the opponent, wants the lowest score', 'Leaves — final positions, scored by an evaluation', 'Values flow up — each player picks their best option'], chapter: 'The idea', say: 'We call our AI MAX, because it wants the highest score. The opponent is MIN, who wants the lowest. We score the final positions at the bottom of the tree, then pass values upwards, each player choosing their best option.' },
      { kit: 'game-tree', chapter: 'Minimax', say: 'Watch the values rise. Each MIN node takes the smallest value below it: three, two and two. Then MAX at the top takes the largest of those, three. So MAX should choose the left move, which guarantees at least three, whatever MIN does.' },
      { kit: 'game-tree', prune: true, chapter: 'Alpha–beta pruning', say: 'Now alpha beta pruning. After the left branch, MAX knows it can get at least three. In the middle branch, MIN finds a two straight away, so this branch can never beat three. The remaining leaves are skipped. Same answer, less work.' },
      { kit: 'compare', head: 'Why pruning matters', left: { title: 'Plain minimax', items: ['Checks every leaf', 'Cost explodes with depth', 'Fine for tic-tac-toe'], color: 'amber' }, right: { title: 'Alpha–beta', items: ['Skips branches that cannot matter', 'With good move ordering, can search roughly twice as deep in the same time', 'Always returns the same answer as minimax'], color: 'green' }, chapter: 'Why it matters', say: 'Game trees grow exponentially. Alpha beta pruning always gives exactly the same answer as minimax, but with good move ordering it can search roughly twice as deep in the same time. That is a huge advantage in games like chess.' },
      { kit: 'bullets', style: 'recap', items: ['MAX maximises, MIN minimises, turn by turn', 'Values are passed up from the leaves', 'Alpha–beta skips branches that cannot change the result', 'Same answer as minimax, far less work'], chapter: 'Recap', say: 'Remember: MAX maximises, MIN minimises. Values flow up from the leaves. Alpha beta pruning skips hopeless branches and gets the same answer much faster.' }
    ],
    takeaways: ['Minimax assumes both players play optimally: MAX maximises, MIN minimises.', 'Values are computed at the leaves and passed up the tree.', 'Alpha–beta pruning skips branches that cannot affect the final decision.', 'Pruning returns exactly the same move as full minimax.'],
    quiz: [
      { q: 'In our tree the MIN nodes had values 3, 2 and 2. What value does MAX choose?', a: ['2', '3', '14'], c: 1, why: 'MAX takes the largest of its children’s values: 3.' },
      { q: 'What does alpha–beta pruning change?', a: ['The final decision', 'How many positions must be evaluated', 'The rules of the game'], c: 1, why: 'It skips irrelevant branches but returns the same decision.' },
      { q: 'Why could the middle branch be pruned after seeing a 2?', a: ['MIN would never let MAX get more than 2 there, and MAX already has 3', 'Because 2 is an even number', 'Because it was the last branch'], c: 0, why: 'That branch can be worth at most 2 to MAX, which is worse than the 3 already guaranteed.' }
    ],
    read: ['adversarial-search-minimax-alpha-beta', 'monte-carlo-tree-search', 'alphago-alphazero']
  },
  {
    slug: 'hill-climbing-and-simulated-annealing', title: 'Hill Climbing and Simulated Annealing', track: 'ai', level: 'Intermediate', poster: 2,
    summary: 'Local search climbs towards better solutions — but gets stuck on local peaks. Simulated annealing adds controlled randomness to escape.',
    scenes: [
      { kit: 'title', title: 'Hill Climbing & Simulated Annealing', sub: 'Local search on a bumpy landscape', track: 'Artificial Intelligence', chapter: 'Introduction', say: 'Some problems have too many possible solutions to search them all. Local search starts somewhere and keeps improving. Let us see how, and where it goes wrong.' },
      { kit: 'landscape', mode: 'hill', chapter: 'Hill climbing', say: 'Imagine every possible solution as a point on a landscape, where height means quality. Hill climbing looks at its neighbours and steps to whichever is higher. It climbs quickly, but here it gets stuck on a small local peak, even though a much higher peak exists.' },
      { kit: 'bullets', head: 'Why hill climbing gets stuck', items: ['Local maxima — every neighbour is worse, but it is not the best', 'Plateaus — flat areas give no direction', 'Ridges — the way up needs a sideways step first'], chapter: 'The problem', say: 'Hill climbing fails in three classic ways. Local maxima, where every neighbour is worse even though a better peak exists. Plateaus with no slope to follow. And ridges, where you must first step sideways.' },
      { kit: 'landscape', mode: 'anneal', chapter: 'Simulated annealing', say: 'Simulated annealing borrows an idea from metalworking. At first the temperature is high, and it often accepts worse moves, jumping around the landscape. As it cools, it becomes pickier. Here it escaped the local peak and settled on the global maximum. Because it uses randomness, it usually escapes, though not on every run.' },
      { kit: 'equation', head: 'Accepting a worse move', parts: [{ t: 'P(accept)', c: 'amber', note: 'The probability of accepting a move that makes things worse' }, { t: ' = ' }, { t: 'e', c: null }, { t: '^(Δ / T)', c: 'pink', note: 'Δ is how much worse the move is (negative). T is the temperature: high T accepts more.' }], below: 'Better moves are always accepted; worse moves sometimes, less often as T falls', chapter: 'The acceptance rule', say: 'The rule is simple. Better moves are always accepted. A worse move is accepted with probability e to the power delta over T. When the temperature is high, bad moves are often accepted. As it cools, they become rare.' },
      { kit: 'bullets', style: 'recap', items: ['Hill climbing — always step uphill; fast but short-sighted', 'Local maxima, plateaus and ridges trap it', 'Simulated annealing accepts some worse moves early on', 'Cooling slowly lets it settle near the best solution'], chapter: 'Recap', say: 'To recap. Hill climbing always steps uphill, but gets trapped. Simulated annealing accepts some worse moves while hot, which helps it escape local peaks before settling down.' }
    ],
    takeaways: ['Hill climbing moves to the best neighbour and can get stuck on local maxima.', 'Simulated annealing accepts worse moves with probability e^(Δ/T).', 'A high temperature encourages exploration; cooling focuses the search.', 'Randomness means annealing usually — but not always — finds the global best.'],
    quiz: [
      { q: 'Why did hill climbing stop on the smaller peak?', a: ['Every neighbour there was lower', 'It ran out of time', 'The landscape was flat'], c: 0, why: 'At a local maximum every nearby move is worse, so hill climbing stops.' },
      { q: 'What happens to simulated annealing as the temperature falls?', a: ['It accepts worse moves more often', 'It accepts worse moves less often', 'It stops moving immediately'], c: 1, why: 'Lower temperature makes e^(Δ/T) smaller for bad moves.' },
      { q: 'A move that improves the solution is accepted…', a: ['Always', 'Only when hot', 'Only when cold'], c: 0, why: 'Improvements are always accepted; only worse moves are probabilistic.' }
    ],
    read: ['local-search-hill-climbing-simulated-annealing', 'genetic-algorithms-evolutionary-computation']
  },
  {
    slug: 'genetic-algorithms', title: 'Genetic Algorithms: Evolution in Code', track: 'ai', level: 'Intermediate', poster: 2,
    summary: 'Selection, crossover and mutation: watch a population of bit strings evolve towards a perfect solution, generation by generation.',
    scenes: [
      { kit: 'title', title: 'Genetic Algorithms', sub: 'Borrowing evolution to solve problems', track: 'Artificial Intelligence', chapter: 'Introduction', say: 'Nature solves hard design problems through evolution. Genetic algorithms borrow that idea: breed better and better solutions over many generations.' },
      { kit: 'cycle', head: 'The evolutionary loop', steps: ['Population', 'Fitness', 'Selection', 'Crossover', 'Mutation'], desc: ['Many candidate solutions', 'Score each one', 'Fitter ones become parents', 'Children mix parent genes', 'Random flips add variety'], chapter: 'The loop', say: 'Start with a population of random candidate solutions. Score each one with a fitness function. Select the fitter ones as parents. Combine their genes with crossover. Add small random mutations. Then repeat.' },
      { kit: 'genetic', sub: 'goal: a string of sixteen 1s (the “OneMax” problem)', chapter: 'Watching evolution', say: 'Here each individual is a string of sixteen bits, and fitness simply counts the ones. Green cells are ones. Watch generation by generation as selection, crossover and mutation push the population towards all ones. The chart on the right tracks the best fitness, and by generation sixteen it finds the perfect string of sixteen ones.' },
      { kit: 'compare', head: 'Crossover and mutation', left: { title: 'Crossover', items: ['Pick a cut point', 'Child takes the first part from parent A', 'And the rest from parent B', 'Combines good building blocks'], color: 'cyan' }, right: { title: 'Mutation', items: ['Flip a random bit, rarely', 'Keeps diversity in the population', 'Helps escape dead ends'], color: 'pink' }, chapter: 'The operators', say: 'Crossover combines good pieces from two parents into one child. Mutation randomly flips a bit now and then. Crossover exploits what already works. Mutation keeps exploring.' },
      { kit: 'bullets', head: 'Where genetic algorithms are used', items: ['Scheduling — timetables, shifts and deliveries', 'Engineering design — antennas, wings and structures', 'Tuning — searching settings of other algorithms', 'Games and art — evolving strategies and creatures'], chapter: 'Applications', say: 'Genetic algorithms are useful when the search space is huge and there is no neat formula. Timetables, engineering designs, tuning other algorithms, and even evolving game strategies.' },
      { kit: 'bullets', style: 'recap', items: ['A population of candidate solutions evolves', 'Fitness decides who reproduces', 'Crossover mixes, mutation explores', 'Best for huge, messy search spaces'], chapter: 'Recap', say: 'To recap. A population evolves. Fitness decides who reproduces. Crossover mixes good ideas and mutation explores new ones. Great for big, messy search problems.' }
    ],
    takeaways: ['Genetic algorithms evolve a population of candidate solutions.', 'A fitness function decides which candidates become parents.', 'Crossover combines parents; mutation adds random variation.', 'They suit large search spaces without a neat mathematical solution.'],
    quiz: [
      { q: 'What does the fitness function do?', a: ['Scores how good each candidate is', 'Randomly flips bits', 'Joins two parents together'], c: 0, why: 'Fitness measures quality and drives selection.' },
      { q: 'Which operator mainly keeps diversity in the population?', a: ['Selection', 'Mutation', 'Sorting'], c: 1, why: 'Random mutations introduce new variation.' },
      { q: 'In the OneMax example, what is the best possible fitness for 16 bits?', a: ['8', '16', '32'], c: 1, why: 'Fitness counts the 1s, so all sixteen 1s is optimal.' }
    ],
    read: ['genetic-algorithms-evolutionary-computation', 'swarm-intelligence-pso-aco']
  },
  {
    slug: 'bayes-theorem', title: 'Bayes’ Theorem: Reasoning Under Uncertainty', track: 'ai', level: 'Beginner', poster: 1,
    summary: 'A positive medical test that is “90% accurate” — so why is the chance of being sick only about 32%? Bayes’ theorem explained with 200 people.',
    scenes: [
      { kit: 'title', title: 'Bayes’ Theorem', sub: 'Updating beliefs with evidence', track: 'Artificial Intelligence', chapter: 'Introduction', say: 'AI systems constantly reason under uncertainty. Bayes theorem tells us how to update a belief when new evidence arrives. Let us see it with a simple medical test.' },
      { kit: 'bayes', chapter: 'Counting people', say: 'Picture 200 people. Five percent, that is ten people, are actually sick. The test catches 90 percent of sick people, so nine test positive. But it also wrongly flags 10 percent of the 190 healthy people, which is 19 false alarms. So of 28 positive results, only nine are sick. About 32 percent.' },
      { kit: 'equation', head: 'Bayes’ theorem', size: 44, parts: [{ t: 'P(A|B)', c: 'green', note: 'Posterior: what we believe about A after seeing evidence B' }, { t: ' = ' }, { t: 'P(B|A)', c: 'amber', note: 'Likelihood: how probable the evidence is if A is true (90% for sick people)' }, { t: ' · ' }, { t: 'P(A)', c: 'pink', note: 'Prior: what we believed before the evidence (5% are sick)' }, { t: ' / ' }, { t: 'P(B)', c: 'cyan', note: 'Evidence: how common the evidence is overall (28 positives out of 200)' }], below: '0.9 × 0.05 / 0.14 ≈ 0.32', monoBelow: true, chapter: 'The formula', say: 'The formula says: the posterior equals the likelihood times the prior, divided by the evidence. Point nine times point zero five, divided by point one four, gives about point three two. Exactly what we counted.' },
      { kit: 'bullets', head: 'Why our intuition fails', items: ['Base rate neglect — we forget that the illness is rare', 'Many healthy people means many false alarms', 'A second, independent test raises the probability sharply', 'AI spam filters and diagnosis tools use this reasoning'], chapter: 'Why it matters', say: 'Our intuition fails because we ignore the base rate. When a condition is rare, even a small false-alarm rate produces many false positives. A second independent test would change the picture a lot. Spam filters and diagnostic AI use exactly this reasoning.' },
      { kit: 'bullets', style: 'recap', items: ['Prior — what you believed before', 'Likelihood — how well the evidence fits', 'Posterior — your updated belief', 'Always consider the base rate'], chapter: 'Recap', say: 'To recap. Start with a prior. Weigh the evidence with the likelihood. Get an updated posterior. And never forget the base rate.' }
    ],
    takeaways: ['Bayes’ theorem updates a prior belief into a posterior using evidence.', 'In the example, a positive result means only about a 32% chance of being sick.', 'Ignoring rare base rates leads to badly wrong conclusions.', 'Naive Bayes classifiers and probabilistic AI build on this rule.'],
    quiz: [
      { q: 'In the example, how many of the 28 positive tests were truly sick?', a: ['9', '19', '28'], c: 0, why: '9 sick people tested positive; 19 positives were false alarms.' },
      { q: 'What is the “prior” in this example?', a: ['The 90% detection rate', 'The 5% of people who are sick', 'The 32% result'], c: 1, why: 'The prior is the belief before seeing the test result.' },
      { q: 'Why is the posterior so much lower than 90%?', a: ['Because the illness is rare, so false alarms outnumber true cases', 'Because the test is broken', 'Because of rounding'], c: 0, why: 'With a low base rate, even a 10% false-positive rate creates many false alarms.' }
    ],
    read: ['bayes-theorem-explained', 'bayesian-networks', 'naive-bayes-classifiers']
  },
  {
    slug: 'how-large-language-models-work', title: 'How Large Language Models Work', track: 'ai', level: 'Beginner', poster: 2,
    summary: 'ChatGPT, Claude and friends predict the next token over and over. Watch a model choose words from probabilities, one token at a time.',
    scenes: [
      { kit: 'title', title: 'How Large Language Models Work', sub: 'Predicting the next token, again and again', track: 'Artificial Intelligence', chapter: 'Introduction', say: 'Large language models can write essays, code and poems. Underneath, they do one thing over and over. They predict the next piece of text.' },
      { kit: 'pipeline', head: 'From text to prediction', steps: ['Tokens', 'Embeddings', 'Transformer layers', 'Probabilities'], desc: ['Text is split into tokens: words or pieces of words, each with an ID.', 'Each token becomes a list of numbers that captures its meaning.', 'Attention layers mix information between all the tokens.', 'The model outputs a probability for every possible next token.'], chapter: 'The pipeline', say: 'First the text is split into tokens. Each token becomes a vector of numbers called an embedding. Many transformer layers use attention to mix information between tokens. Finally the model outputs a probability for every possible next token.' },
      { kit: 'llm', prompt: 'The best way to learn AI is', steps: [['to', [['to', .58], ['by', .27], ['through', .1], ['with', .05]]], ['build', [['build', .36], ['practise', .31], ['start', .2], ['read', .13]]], ['small', [['small', .41], ['real', .29], ['simple', .2], ['many', .1]]], ['projects', [['projects', .72], ['models', .16], ['apps', .09], ['things', .03]]]], sub: 'illustrative probabilities', chapter: 'Generating text', say: 'Watch it write. Given the prompt, the model scores every candidate for the next token. It picks one, adds it to the text, and repeats with the longer text. To, build, small, projects. These probabilities are illustrative, but the process is exactly how generation works.' },
      { kit: 'bullets', head: 'How the model learned', items: ['Pre-training — predict the next token across a huge amount of text', 'Every mistake nudges billions of parameters', 'Fine-tuning — learn to follow instructions helpfully', 'Human feedback — prefer answers people rate as better'], chapter: 'Training', say: 'During pre-training, the model predicts the next token across an enormous amount of text, and every mistake slightly adjusts billions of parameters. Then fine-tuning and human feedback teach it to follow instructions and be helpful.' },
      { kit: 'compare', head: 'Strengths and limits', left: { title: 'Strengths', items: ['Fluent writing and summarising', 'Explaining and brainstorming', 'Code and translation'], color: 'green' }, right: { title: 'Limits', items: ['Can state false things confidently', 'Knowledge has a cut-off date', 'Needs checking for important facts'], color: 'red' }, chapter: 'Strengths and limits', say: 'Language models are excellent at writing, explaining and coding. But they generate plausible text, not verified truth. They can confidently state false things, and their knowledge stops at a cut-off date. Always check important facts.' },
      { kit: 'bullets', style: 'recap', items: ['Text → tokens → embeddings → attention → probabilities', 'Generate one token at a time, then repeat', 'Pre-training on text, then fine-tuning to follow instructions', 'Plausible is not the same as true'], chapter: 'Recap', say: 'To recap. Text becomes tokens, embeddings, attention and probabilities. The model generates one token at a time. It learns from huge text, then from instructions. And plausible is not the same as true.' }
    ],
    takeaways: ['An LLM predicts the next token repeatedly to generate text.', 'Tokens become embeddings, attention mixes context, and the output is a probability for each possible token.', 'Pre-training on text is followed by instruction fine-tuning and human feedback.', 'LLM output is plausible, not guaranteed true — verify important facts.'],
    quiz: [
      { q: 'What does a language model output at each step?', a: ['A finished paragraph', 'A probability for each possible next token', 'A database query'], c: 1, why: 'It produces a probability distribution over the next token.' },
      { q: 'What happens after a token is chosen?', a: ['Generation stops', 'It is added to the text and the model predicts again', 'The model retrains'], c: 1, why: 'Generation is repeated, one token at a time.' },
      { q: 'Why can language models “hallucinate”?', a: ['They generate plausible text rather than looking up verified facts', 'They are always connected to the internet', 'Their tokens are too long'], c: 0, why: 'They are trained to produce likely text, which is not always true.' }
    ],
    read: ['large-language-models-overview', 'gpt-family-autoregressive-models', 'decoding-strategies-sampling', 'llm-hallucination']
  },
  {
    slug: 'attention-and-transformers', title: 'Attention and Transformers', track: 'ai', level: 'Intermediate', poster: 2,
    summary: 'Self-attention lets every word look at every other word. See how “it” finds “animal”, and how attention matrices power the Transformer.',
    scenes: [
      { kit: 'title', title: 'Attention and Transformers', sub: 'Learning where to look', track: 'Artificial Intelligence', chapter: 'Introduction', say: 'The Transformer, introduced in 2017, is the architecture behind modern language models. Its key idea is attention: letting each word decide which other words matter to it.' },
      { kit: 'attention', note: '“it” pays most attention to “animal” — that is what it refers to', sub: 'illustrative attention weights', chapter: 'Self-attention', say: 'Read this sentence. The animal did not cross the street because it was tired. What does it refer to? Self attention lets the word it look at every other word and assign weights. Here most of its attention goes to animal, which is exactly right.' },
      { kit: 'pipeline', head: 'Queries, keys and values', steps: ['Query', 'Key', 'Score', 'Value'], desc: ['Each word asks a question: what am I looking for?', 'Each word also advertises: this is what I contain.', 'Matching a query with every key gives attention weights that sum to 1.', 'Each word’s new meaning is a weighted mix of all the values.'], chapter: 'Query, key, value', say: 'Attention works with three vectors per word. A query, what am I looking for. A key, what do I contain. Comparing a query with all keys gives weights that add up to one. The word then becomes a weighted blend of all the words’ values.' },
      { kit: 'attention', mode: 'matrix', head: 'The attention matrix', sub: 'illustrative weights', words: ['The', 'cat', 'sat', 'on', 'the', 'mat'], chapter: 'Attention matrix', say: 'Doing this for every word at once gives an attention matrix. Each row shows how much one word attends to every other word. Because every word can look at every other word directly, transformers capture long-range relationships and train efficiently in parallel.' },
      { kit: 'bullets', head: 'Inside a Transformer block', items: ['Multi-head attention — several attention patterns in parallel', 'Feed-forward network — processes each token further', 'Residual connections and normalisation — keep training stable', 'Stack dozens of blocks — deeper understanding'], chapter: 'Transformer blocks', say: 'A Transformer stacks many identical blocks. Each has multi-head attention, so it can track several kinds of relationships at once, followed by a small feed-forward network, with residual connections to keep training stable.' },
      { kit: 'bullets', style: 'recap', items: ['Attention lets each token weigh every other token', 'Queries, keys and values produce the weights', 'Rows of the attention matrix sum to 1', 'Transformers stack attention blocks — the basis of LLMs'], chapter: 'Recap', say: 'To recap. Attention lets every token weigh every other token, using queries, keys and values. Transformers stack attention blocks, and they power today’s language, vision and speech models.' }
    ],
    takeaways: ['Self-attention lets each token weigh the relevance of every other token.', 'Queries are compared with keys to produce weights; values are blended with those weights.', 'Each row of an attention matrix sums to 1.', 'Transformers stack multi-head attention and feed-forward layers.'],
    quiz: [
      { q: 'In the example sentence, which word did “it” attend to most?', a: ['street', 'animal', 'tired'], c: 1, why: '“It” refers to the animal, and the attention weights reflect that.' },
      { q: 'What do the attention weights in one row add up to?', a: ['0', '1', 'The number of words'], c: 1, why: 'They are produced by a softmax, so they sum to 1.' },
      { q: 'Why does multi-head attention use several heads?', a: ['To track different kinds of relationships at the same time', 'To make the model smaller', 'To remove the need for training'], c: 0, why: 'Each head can learn a different attention pattern.' }
    ],
    read: ['attention-mechanism', 'self-attention-in-depth', 'transformer-architecture-explained']
  },
  {
    slug: 'how-image-generators-work', title: 'How AI Image Generators Work', track: 'ai', level: 'Beginner', poster: 1,
    summary: 'Diffusion models turn pure noise into a picture by removing a little noise at a time, guided by your text prompt.',
    scenes: [
      { kit: 'title', title: 'How AI Image Generators Work', sub: 'From pure noise to a picture', track: 'Artificial Intelligence', chapter: 'Introduction', say: 'Type a description and an AI draws it in seconds. Most of these image generators are diffusion models. Their trick sounds backwards: they create images by removing noise.' },
      { kit: 'diffusion', shape: 'heart', prompt: 'a pink heart icon', sub: 'illustration of the denoising process', chapter: 'Denoising', say: 'Generation starts with random static. At each step, the model predicts which part of the picture is noise and removes a little of it. Slowly, shapes appear, then details sharpen, until the image matches the prompt.' },
      { kit: 'pipeline', head: 'How the model learned', steps: ['Take real images', 'Add noise', 'Predict the noise', 'Repeat millions of times'], desc: ['Millions of images, each with a caption.', 'Add a random amount of noise to each image.', 'The network learns to guess exactly which noise was added.', 'Once it predicts noise well, running it in reverse creates new images.'], chapter: 'Training', say: 'During training, the model sees millions of captioned images. Noise is added to each one, and the network learns to predict exactly which noise was added. Once it is good at that, you can start from pure noise and run the process in reverse.' },
      { kit: 'diffusion', shape: 'smiley', prompt: 'a happy yellow face', head: 'The prompt steers every step', chapter: 'Guided by text', say: 'The text prompt is turned into embeddings, and they guide every denoising step. A different prompt, starting from the same kind of noise, ends in a different picture.' },
      { kit: 'bullets', head: 'Using image generators responsibly', items: ['Check the tool’s licence before commercial use', 'Do not imitate real people without consent', 'Watch for stereotypes in results', 'Label AI-generated images where appropriate'], chapter: 'Responsible use', say: 'Use these tools responsibly. Check licences, never create images of real people without consent, watch for stereotypes in the results, and label AI images when it matters.' },
      { kit: 'bullets', style: 'recap', items: ['Start from random noise', 'Remove a little predicted noise at every step', 'The text prompt guides each step', 'Trained by learning to predict added noise'], chapter: 'Recap', say: 'To recap. Diffusion starts from noise, removes a little predicted noise at every step, is guided by the prompt, and was trained by learning to predict the noise added to real images.' }
    ],
    takeaways: ['Diffusion models generate images by gradually removing noise.', 'They are trained to predict the noise added to real images.', 'The text prompt, turned into embeddings, guides every step.', 'Use generated images responsibly: licences, consent and bias.'],
    quiz: [
      { q: 'What does a diffusion model start from when generating an image?', a: ['A blank white canvas', 'Random noise', 'A photo from the internet'], c: 1, why: 'Generation begins with pure random noise.' },
      { q: 'What is the model trained to predict?', a: ['The noise that was added to an image', 'The photographer’s name', 'The final image in one step'], c: 0, why: 'Learning to predict the added noise lets it remove noise step by step.' },
      { q: 'How does the text prompt affect the image?', a: ['It guides every denoising step', 'It is only used for the file name', 'It picks a stock photo'], c: 0, why: 'Prompt embeddings condition each step of denoising.' }
    ],
    read: ['diffusion-models', 'latent-diffusion-stable-diffusion', 'text-to-image-and-video-generation']
  }
];
