/* AI in Motion — Deep Learning track. © Janin A Apurba, CSE, AUST */
module.exports = [
  {
    slug: 'artificial-neurons-and-the-perceptron', title: 'Artificial Neurons and the Perceptron', track: 'dl', level: 'Beginner', poster: 1,
    summary: 'Inside a single artificial neuron: weighted inputs, a sum, a bias and an activation — plus the perceptron that learns from its mistakes.',
    scenes: [
      { kit: 'title', title: 'Artificial Neurons', sub: 'The building block of every neural network', track: 'Deep Learning', chapter: 'Introduction', say: 'Every neural network, from a tiny classifier to a giant language model, is built from one simple unit: the artificial neuron. Let us open one up.' },
      { kit: 'neuron', chapter: 'Inside a neuron', say: 'A neuron receives inputs. Each input is multiplied by a weight. Here, 0.8 times 1.2, 0.3 times minus 0.7, and 0.5 times 0.9. The neuron adds them up with a bias of minus 0.4, giving z equals 0.8. Then an activation function, here the sigmoid, turns that into an output of 0.69.' },
      { kit: 'equation', head: 'The neuron in one line', parts: [{ t: 'output', c: 'pink', note: 'What the neuron passes on to the next layer' }, { t: ' = ' }, { t: 'f', c: 'amber', note: 'f is the activation function, such as sigmoid or ReLU' }, { t: '(' }, { t: 'Σ wᵢxᵢ', c: 'cyan', note: 'The weighted sum: each input times its weight' }, { t: ' + ' }, { t: 'b', c: 'green', note: 'The bias shifts the threshold at which the neuron activates' }, { t: ')' }], chapter: 'The formula', say: 'In one line: the output is an activation function applied to the weighted sum of the inputs plus a bias. Learning simply means finding good weights and biases.' },
      { kit: 'compare', head: 'Biological vs artificial neurons', left: { title: 'Biological neuron', items: ['Dendrites receive signals', 'Fires if stimulation passes a threshold', 'About 86 billion in a human brain'], color: 'violet' }, right: { title: 'Artificial neuron', items: ['Inputs multiplied by weights', 'Activation function decides the output', 'A loose mathematical inspiration'], color: 'cyan' }, chapter: 'Inspired by biology', say: 'Artificial neurons were inspired by brain cells, which receive signals and fire when stimulated enough. But the inspiration is loose. An artificial neuron is simple maths, not a model of real biology.' },
      { kit: 'classify-boundary', model: 'perceptron', chapter: 'The perceptron learns', say: 'In 1958 Frank Rosenblatt built the perceptron, a single neuron that learns. When it misclassifies a point, it nudges its weights towards the right answer. Here the boundary moves until most points are on the correct side.' },
      { kit: 'bullets', style: 'recap', items: ['Inputs × weights, summed with a bias', 'An activation function produces the output', 'Learning = adjusting weights and biases', 'The perceptron (1958) learns from its mistakes'], chapter: 'Recap', say: 'To recap. A neuron multiplies inputs by weights, adds a bias, and applies an activation. Learning means adjusting those weights. And the perceptron was the first neuron that learned.' }
    ],
    takeaways: ['A neuron computes f(Σ wᵢxᵢ + b).', 'In the example: z = 0.80 and sigmoid(0.80) ≈ 0.69.', 'Weights and biases are what a network learns.', 'The perceptron (Rosenblatt, 1958) updates its weights when it makes a mistake.'],
    quiz: [
      { q: 'What does a weight do?', a: ['Scales how much an input influences the neuron', 'Stores the output', 'Counts the inputs'], c: 0, why: 'Each input is multiplied by its weight.' },
      { q: 'What is the role of the activation function?', a: ['It turns the weighted sum into the neuron’s output, adding non-linearity', 'It loads the data', 'It deletes weak inputs'], c: 0, why: 'Activations such as sigmoid or ReLU shape the output.' },
      { q: 'When does the perceptron update its weights?', a: ['When it misclassifies an example', 'Every second', 'Only at the start'], c: 0, why: 'It learns only from mistakes.' }
    ],
    read: ['from-neurons-to-neural-networks', 'the-perceptron']
  },
  {
    slug: 'neural-networks-forward-pass', title: 'Neural Networks: The Forward Pass', track: 'dl', level: 'Beginner', poster: 1,
    summary: 'Stack neurons into layers and connect them. Watch signals flow from input to output and become class probabilities.',
    scenes: [
      { kit: 'title', title: 'Neural Networks', sub: 'Layers of neurons working together', track: 'Deep Learning', chapter: 'Introduction', say: 'One neuron can only draw a straight line. Connect many of them in layers, and you get a neural network that can learn remarkably complex patterns.' },
      { kit: 'network', layers: [4, 6, 6, 3], out: ['Cat', 'Dog', 'Bird'], probs: [.81, .14, .05], chapter: 'A forward pass', say: 'This network has four inputs, two hidden layers of six neurons and three outputs. In a forward pass, signals flow from left to right. Each neuron combines the signals from the previous layer, and the output layer produces probabilities: 81 percent cat, 14 percent dog, 5 percent bird.' },
      { kit: 'equation', head: 'A whole layer at once', parts: [{ t: 'a', c: 'pink', note: 'The activations (outputs) of this layer' }, { t: ' = ' }, { t: 'f', c: 'amber', note: 'The activation function, applied to every neuron' }, { t: '(' }, { t: 'W', c: 'cyan', note: 'W is a matrix holding every weight between the two layers' }, { t: 'x + ' }, { t: 'b', c: 'green', note: 'b holds one bias per neuron' }, { t: ')' }], below: 'A network is these layers chained together', chapter: 'Matrix form', say: 'In practice we compute a whole layer at once with a matrix. Multiply the inputs by the weight matrix W, add the biases, and apply the activation. A network is just these layers chained together, which is why GPUs, built for matrix maths, are so useful.' },
      { kit: 'bullets', head: 'Why depth helps', items: ['Each layer builds on the one before', 'Early layers find simple patterns, later layers combine them', 'Universal approximation — enough neurons can approximate almost any function', 'Deep networks often need fewer neurons than wide shallow ones'], chapter: 'Why layers?', say: 'Why use layers? Each layer builds on the one before. Early layers detect simple patterns and later layers combine them into complex ones. In theory, a network with enough neurons can approximate almost any function.' },
      { kit: 'network', layers: [3, 5, 5, 5, 2], out: ['Spam', 'Not spam'], probs: [.93, .07], head: 'A deeper network', chapter: 'Going deeper', say: 'Here is a deeper network with three hidden layers, deciding whether an email is spam. More layers let the network build more abstract features, as long as we have enough data to train it.' },
      { kit: 'bullets', style: 'recap', items: ['Neurons are arranged in layers', 'The forward pass flows from input to output', 'Each layer computes f(Wx + b)', 'Depth lets networks build complex features from simple ones'], chapter: 'Recap', say: 'To recap. Networks arrange neurons in layers. The forward pass flows from input to output. Each layer computes f of W x plus b. And depth builds complex features from simple ones.' }
    ],
    takeaways: ['A network chains layers that each compute f(Wx + b).', 'The forward pass carries signals from inputs to outputs.', 'The output layer often produces class probabilities with softmax.', 'Depth lets networks compose simple features into complex ones.'],
    quiz: [
      { q: 'In a forward pass, information flows…', a: ['From input to output', 'From output to input', 'Randomly'], c: 0, why: 'The forward pass computes predictions layer by layer.' },
      { q: 'What does the weight matrix W contain?', a: ['All the weights between two layers', 'The training labels', 'The learning rate'], c: 0, why: 'Each entry connects one neuron to one neuron in the next layer.' },
      { q: 'Why are GPUs useful for neural networks?', a: ['They are fast at matrix operations', 'They store more labels', 'They choose the architecture'], c: 0, why: 'Layers are matrix multiplications, which GPUs accelerate.' }
    ],
    read: ['multilayer-perceptrons-universal-approximation', 'from-neurons-to-neural-networks']
  },
  {
    slug: 'activation-functions', title: 'Activation Functions: Sigmoid, Tanh and ReLU', track: 'dl', level: 'Beginner', poster: 1,
    summary: 'Why networks need non-linearity, and how sigmoid, tanh, ReLU, Leaky ReLU and GELU differ — drawn live.',
    scenes: [
      { kit: 'title', title: 'Activation Functions', sub: 'The non-linear spark in every neuron', track: 'Deep Learning', chapter: 'Introduction', say: 'Without activation functions, even a hundred-layer network would only learn straight-line relationships. Activation functions add the bends that make deep learning powerful.' },
      { kit: 'bullets', head: 'Why non-linearity?', items: ['A linear layer followed by another linear layer is still linear', 'So without activations, depth adds nothing', 'Non-linear activations let networks model curves and complex boundaries'], chapter: 'Why they matter', say: 'Stacking linear layers just gives another linear function, so depth would be pointless. Non-linear activations break that, letting networks model curves, corners and complex decision boundaries.' },
      { kit: 'activation', fns: ['sigmoid', 'tanh', 'relu', 'leaky'], notes: ['Squeezes to (0, 1). Good for probabilities, but flat at both ends.', 'Like sigmoid but centred on zero, from −1 to 1.', 'Zero for negatives, identity for positives. Fast and the usual default.', 'A small slope for negatives, so neurons never go completely silent.'], chapter: 'Four classics', say: 'The sigmoid squeezes values between zero and one. Tanh is similar but centred on zero. ReLU outputs zero for negative inputs and passes positive ones straight through. Leaky ReLU keeps a small slope for negatives, so neurons never die completely.' },
      { kit: 'compare', head: 'The vanishing gradient problem', left: { title: 'Sigmoid & tanh', items: ['Flatten out for large inputs', 'Slope near zero → tiny gradients', 'Deep networks learn very slowly'], color: 'red' }, right: { title: 'ReLU family', items: ['Slope of 1 for positive inputs', 'Gradients flow through deep networks', 'Cheap to compute'], color: 'green' }, chapter: 'Vanishing gradients', say: 'Sigmoid and tanh flatten out for large inputs, where their slope is almost zero. During training, those tiny slopes multiply through many layers and gradients vanish. ReLU keeps a slope of one for positive inputs, so gradients flow much better.' },
      { kit: 'activation', fns: ['relu', 'gelu'], head: 'Modern choices', notes: ['The default for many convolutional networks.', 'A smooth ReLU used in Transformers such as BERT and GPT models.'], chapter: 'Modern choices', say: 'Modern networks often use ReLU, or smooth variants like GELU, which is common in Transformers. For outputs we use sigmoid for yes or no answers and softmax for choosing between many classes.' },
      { kit: 'bullets', style: 'recap', items: ['Activations add the non-linearity networks need', 'Sigmoid and tanh saturate → vanishing gradients', 'ReLU is simple, fast and the common default', 'Output layers: sigmoid for binary, softmax for many classes'], chapter: 'Recap', say: 'To recap. Activations add non-linearity. Sigmoid and tanh can make gradients vanish. ReLU and its variants are the usual default. And output layers use sigmoid or softmax.' }
    ],
    takeaways: ['Without non-linear activations, stacked layers collapse into one linear function.', 'Sigmoid and tanh saturate, which can cause vanishing gradients.', 'ReLU (and Leaky ReLU, GELU) are standard choices for hidden layers.', 'Use sigmoid for binary outputs and softmax for multi-class outputs.'],
    quiz: [
      { q: 'What is ReLU(−3)?', a: ['−3', '0', '3'], c: 1, why: 'ReLU outputs max(0, x).' },
      { q: 'Why can sigmoid cause vanishing gradients?', a: ['It is nearly flat for large positive or negative inputs', 'It is too fast to compute', 'It outputs negative numbers'], c: 0, why: 'Flat regions have tiny slopes, so gradients shrink.' },
      { q: 'Which activation is common in Transformer models?', a: ['GELU', 'Step function', 'None'], c: 0, why: 'GELU is widely used in Transformers.' }
    ],
    read: ['activation-functions', 'vanishing-exploding-gradients']
  },
  {
    slug: 'loss-functions-and-the-training-loop', title: 'Loss Functions and the Training Loop', track: 'dl', level: 'Beginner', poster: 2,
    summary: 'How a network measures its mistakes and improves: mini-batches, forward pass, loss, backward pass and update — repeated thousands of times.',
    scenes: [
      { kit: 'title', title: 'The Training Loop', sub: 'How a network learns from its mistakes', track: 'Deep Learning', chapter: 'Introduction', say: 'A freshly created network makes random guesses. Training turns it into something useful through one loop, repeated thousands of times.' },
      { kit: 'equation', head: 'Measuring mistakes: the loss', parts: [{ t: 'Loss', c: 'red', note: 'A single number: how wrong the predictions are. Lower is better.' }, { t: ' = ' }, { t: '− log', c: 'amber', note: 'Cross-entropy: heavily punishes confident wrong answers' }, { t: '(' }, { t: 'p_correct', c: 'green', note: 'The probability the model gave to the correct class' }, { t: ')' }], below: 'p = 0.9 → loss 0.11     p = 0.1 → loss 2.30', monoBelow: true, chapter: 'The loss', say: 'First we need a single number that says how wrong the network is: the loss. For classification we usually use cross-entropy: minus the log of the probability given to the correct answer. If the model gives the right class 90 percent, the loss is 0.11. If it gives only 10 percent, the loss is 2.3.' },
      { kit: 'train-loop', chapter: 'The loop', say: 'Here is the loop. Take a mini batch of examples. Run a forward pass to get predictions. Compute the loss. Run a backward pass to find how each weight affects the loss. Update the weights a little. Then take the next batch. The loss on the right falls as training goes on.' },
      { kit: 'bullets', head: 'Vocabulary', items: ['Mini-batch — a small group of examples, often 32 to 256', 'Iteration — one update from one mini-batch', 'Epoch — one full pass through the training data', 'Loss curve — loss plotted over training time'], chapter: 'Key terms', say: 'Some vocabulary. A mini batch is a small group of examples. One iteration is one update. An epoch is one full pass through all the training data. And the loss curve tracks progress.' },
      { kit: 'learning-curve', mode: 'good', chapter: 'Watching progress', say: 'We always watch two curves: loss on the training data and loss on validation data the model does not learn from. When both fall together, the network is genuinely learning, not just memorising.' },
      { kit: 'bullets', style: 'recap', items: ['The loss measures how wrong the model is', 'Cross-entropy for classification, MSE for regression', 'Loop: batch → forward → loss → backward → update', 'Watch training and validation loss together'], chapter: 'Recap', say: 'To recap. The loss measures mistakes. Cross-entropy for classes, mean squared error for numbers. The loop is batch, forward, loss, backward, update. And we watch both training and validation loss.' }
    ],
    takeaways: ['The loss turns prediction errors into one number to minimise.', 'Cross-entropy: −log(p_correct); p = 0.9 gives 0.11, p = 0.1 gives 2.30.', 'Training repeats: mini-batch, forward, loss, backward, update.', 'An epoch is one pass through all the training data.'],
    quiz: [
      { q: 'If the model assigns probability 0.9 to the correct class, the cross-entropy loss is about…', a: ['0.11', '0.9', '2.30'], c: 0, why: '−ln(0.9) ≈ 0.105.' },
      { q: 'What is an epoch?', a: ['One full pass through the training data', 'One mini-batch', 'One neuron'], c: 0, why: 'An epoch covers every training example once.' },
      { q: 'Which step computes how each weight affects the loss?', a: ['The forward pass', 'The backward pass', 'Shuffling'], c: 1, why: 'Backpropagation computes the gradients.' }
    ],
    read: ['loss-functions-deep-learning', 'pytorch-fundamentals', 'debugging-neural-network-training']
  },
  {
    slug: 'backpropagation', title: 'Backpropagation, Step by Step', track: 'dl', level: 'Intermediate', poster: 1,
    summary: 'The chain rule in action: compute values forward, then pass gradients backward through a tiny computational graph — with real numbers.',
    scenes: [
      { kit: 'title', title: 'Backpropagation', sub: 'How networks work out who to blame', track: 'Deep Learning', chapter: 'Introduction', say: 'A network may have millions of weights. After a mistake, how do we know how to change each one? Backpropagation answers that efficiently, using the chain rule from calculus.' },
      { kit: 'backprop-graph', chapter: 'A tiny example', say: 'Take f equals x plus y, times z, with x equals minus 2, y equals 5 and z equals minus 4. Forward: q equals x plus y equals 3, and f equals q times z equals minus 12. Now backward. Start with a gradient of 1 at f. At the multiply node, the gradient for z is q, which is 3, and for q it is z, minus 4. The add node passes minus 4 to both x and y.' },
      { kit: 'equation', head: 'The chain rule', parts: [{ t: '∂f/∂x', c: 'red', note: 'How much f changes when x changes' }, { t: ' = ' }, { t: '∂f/∂q', c: 'pink', note: 'How f depends on the intermediate value q (here z = −4)' }, { t: ' · ' }, { t: '∂q/∂x', c: 'cyan', note: 'How q depends on x (here 1, because q = x + y)' }], below: '−4 × 1 = −4', monoBelow: true, chapter: 'Chain rule', say: 'That is the chain rule. The gradient of f with respect to x equals the gradient of f with respect to q, times the gradient of q with respect to x. Minus four times one gives minus four. Backpropagation applies this rule node by node, from the output back to the inputs.' },
      { kit: 'network', mode: 'both', layers: [4, 6, 6, 3], head: 'Forward, then backward', chapter: 'In a real network', say: 'In a real network it is the same idea at scale. The forward pass computes predictions and the loss. The backward pass sends error signals back through every layer, giving each weight a gradient. Then gradient descent updates them all.' },
      { kit: 'bullets', head: 'Why it matters', items: ['One backward pass gives every weight its gradient', 'Cost is about the same as a forward pass', 'Frameworks like PyTorch do it automatically (autodiff)', 'Popularised for neural networks in 1986'], chapter: 'Why it matters', say: 'Backpropagation is efficient. One backward pass gives every weight its gradient, at roughly the cost of a forward pass. Modern frameworks do it automatically, a feature called automatic differentiation.' },
      { kit: 'bullets', style: 'recap', items: ['Forward pass: compute values', 'Backward pass: apply the chain rule from the output', 'Each weight gets a gradient', 'Gradient descent then updates the weights'], chapter: 'Recap', say: 'To recap. Compute values forward. Apply the chain rule backward. Every weight gets a gradient. And gradient descent uses those gradients to improve the network.' }
    ],
    takeaways: ['Backpropagation applies the chain rule from the output back to every weight.', 'In f = (x + y)·z with x = −2, y = 5, z = −4: f = −12, ∂f/∂z = 3, ∂f/∂x = ∂f/∂y = −4.', 'One backward pass costs about as much as a forward pass.', 'Frameworks compute gradients automatically (autodiff).'],
    quiz: [
      { q: 'In the example, what is ∂f/∂z?', a: ['3', '−4', '−12'], c: 0, why: 'f = q·z, so ∂f/∂z = q = 3.' },
      { q: 'What does an addition node do to the incoming gradient?', a: ['Passes it unchanged to each input', 'Doubles it', 'Sets it to zero'], c: 0, why: 'The local gradient of x + y with respect to each input is 1.' },
      { q: 'Backpropagation is mainly an application of…', a: ['The chain rule', 'Bayes’ theorem', 'Sorting'], c: 0, why: 'It chains local derivatives together.' }
    ],
    read: ['backpropagation-derived', 'computational-graphs-autodiff', 'derivatives-gradients-chain-rule']
  },
  {
    slug: 'optimizers-sgd-momentum-adam', title: 'Optimisers: SGD, Momentum and Adam', track: 'dl', level: 'Intermediate', poster: 1,
    summary: 'Compare optimisers racing across the same loss surface: noisy SGD, plain gradient descent, momentum and Adam.',
    scenes: [
      { kit: 'title', title: 'Optimisers', sub: 'SGD, momentum and Adam', track: 'Deep Learning', chapter: 'Introduction', say: 'Gradients tell us which way is downhill. Optimisers decide how to step. The choice can make training faster, smoother and more reliable.' },
      { kit: 'contour', opts: ['gd', 'sgd'], head: 'Full-batch vs stochastic', chapter: 'SGD', say: 'Plain gradient descent uses the whole dataset for every step. Stochastic gradient descent, or SGD, uses a small random mini batch instead. Each step is noisier, as you can see from the wobbly amber path, but much cheaper, so we can take many more steps.' },
      { kit: 'equation', head: 'Momentum', parts: [{ t: 'v', c: 'pink', note: 'v is a running velocity: an average of recent gradients' }, { t: ' ← ' }, { t: 'β', c: 'amber', note: 'β (often 0.9) controls how much past direction is remembered' }, { t: 'v + ∇L;   w ← w − η' }, { t: 'v', c: 'pink', note: 'We step using the velocity, not just the latest gradient' }], chapter: 'Momentum', say: 'Momentum works like a ball rolling downhill. It keeps a running velocity that averages recent gradients. Zigzags across a valley cancel out, while consistent directions build up speed.' },
      { kit: 'contour', opts: ['gd', 'momentum', 'adam'], head: 'Racing to the minimum', chapter: 'The race', say: 'Here they race on a narrow valley. Plain gradient descent zigzags. Adam adapts its step size for each direction and heads almost straight for the minimum. Momentum accelerates along the valley and ends up closest by the last step.' },
      { kit: 'bullets', head: 'Adam in a nutshell', items: ['Keeps a running average of gradients (like momentum)', 'Keeps a running average of squared gradients', 'Divides by its square root → per-parameter step sizes', 'Default choice for many deep learning projects (often AdamW)'], chapter: 'Adam', say: 'Adam combines momentum with a running average of squared gradients. Dividing by it gives every parameter its own step size. It works well out of the box, so Adam, or its variant AdamW, is a common default.' },
      { kit: 'bullets', style: 'recap', items: ['SGD: cheap, noisy steps on mini-batches', 'Momentum: remembers direction, smooths zigzags', 'Adam: adaptive step size per parameter', 'Learning-rate schedules and warm-up help all of them'], chapter: 'Recap', say: 'To recap. SGD takes cheap noisy steps. Momentum smooths the path. Adam adapts step sizes per parameter. And learning rate schedules help every optimiser.' }
    ],
    takeaways: ['SGD estimates the gradient on mini-batches: cheap but noisy.', 'Momentum averages past gradients to damp zigzags and speed up progress.', 'Adam adapts the step size for each parameter.', 'AdamW is a common default; learning-rate schedules help all optimisers.'],
    quiz: [
      { q: 'Why is SGD’s path noisy?', a: ['Each step uses a small random mini-batch', 'The learning rate is zero', 'It ignores gradients'], c: 0, why: 'Mini-batch gradients are noisy estimates of the full gradient.' },
      { q: 'What does momentum remember?', a: ['A running average of recent gradients', 'Every training example', 'The final answer'], c: 0, why: 'The velocity term accumulates past gradients.' },
      { q: 'What makes Adam “adaptive”?', a: ['Each parameter gets its own effective step size', 'It changes the dataset', 'It adds layers'], c: 0, why: 'It scales updates by running estimates of squared gradients.' }
    ],
    read: ['sgd-momentum-nesterov', 'adaptive-optimizers-adam-adamw', 'learning-rate-schedules-warmup', 'loss-landscapes']
  },
  {
    slug: 'vanishing-gradients-and-resnets', title: 'Vanishing Gradients and Residual Connections', track: 'dl', level: 'Intermediate', poster: 1,
    summary: 'Why very deep networks used to be untrainable — gradients shrinking layer by layer — and how skip connections fixed it.',
    scenes: [
      { kit: 'title', title: 'Vanishing Gradients', sub: 'And the skip connections that fixed them', track: 'Deep Learning', chapter: 'Introduction', say: 'For years, adding more layers made networks worse, not better. The culprit was the vanishing gradient. Let us watch it happen, and see the fix.' },
      { kit: 'gradient-flow', chapter: 'Watching gradients vanish', say: 'During backpropagation, the gradient is multiplied by each layer’s local slope on its way back. The sigmoid’s slope is at most 0.25. Multiply by 0.25 again and again, and by the first layer only about 0.00006 of the signal remains. Early layers barely learn.' },
      { kit: 'equation', head: 'Why it shrinks', parts: [{ t: 'gradient at layer 1', c: 'red', note: 'The signal that reaches the earliest layer' }, { t: ' ≈ ' }, { t: '0.25', c: 'amber', note: 'At best, the sigmoid’s slope' }, { t: ' ⁷' }], below: '0.25⁷ ≈ 0.00006', monoBelow: true, chapter: 'The maths', say: 'With seven layers of sigmoid slopes, the best case is 0.25 to the power 7, which is about 0.00006. Deeper networks make it even smaller. That is why deep sigmoid networks trained so slowly.' },
      { kit: 'gradient-flow', both: true, head: 'Skip connections to the rescue', chapter: 'Residual connections', say: 'Residual networks add skip connections: each block adds its input to its output. The gradient gets a direct highway back through the network. In this illustration it stays around 0.6 even at the first layer. This idea, from ResNet in 2015, made networks with over a hundred layers trainable.' },
      { kit: 'bullets', head: 'The full toolkit', items: ['ReLU-family activations — slope 1 for positive inputs', 'Careful initialisation — He or Xavier', 'Normalisation — batch norm or layer norm', 'Residual connections — gradient highways'], chapter: 'Other fixes', say: 'Several tools work together. ReLU activations, careful weight initialisation, normalisation layers, and residual connections. Modern networks, including Transformers, use all of them.' },
      { kit: 'bullets', style: 'recap', items: ['Gradients are multiplied layer by layer on the way back', 'Small slopes → vanishing gradients in early layers', 'Skip connections give gradients a direct path', 'ResNets made very deep networks trainable'], chapter: 'Recap', say: 'To recap. Gradients are multiplied layer by layer. Small slopes make them vanish. Skip connections provide a direct path, and that is how very deep networks became trainable.' }
    ],
    takeaways: ['Backpropagated gradients are multiplied by each layer’s local derivative.', 'Sigmoid slopes are at most 0.25, so gradients can shrink exponentially (0.25⁷ ≈ 0.00006).', 'Residual (skip) connections give gradients a direct path back.', 'ReLU, good initialisation and normalisation also help.'],
    quiz: [
      { q: 'What is the maximum slope of the sigmoid function?', a: ['0.25', '1', '10'], c: 0, why: 'σ′(z) = σ(z)(1 − σ(z)) peaks at 0.25.' },
      { q: 'What does a residual connection do?', a: ['Adds a block’s input to its output', 'Removes a layer', 'Doubles the learning rate'], c: 0, why: 'y = F(x) + x creates a shortcut for signals and gradients.' },
      { q: 'Which architecture popularised skip connections in 2015?', a: ['ResNet', 'LeNet', 'The perceptron'], c: 0, why: 'ResNet made networks with 100+ layers trainable.' }
    ],
    read: ['vanishing-exploding-gradients', 'residual-connections-resnet-idea', 'weight-initialization', 'batch-normalization']
  },
  {
    slug: 'dropout-and-regularisation', title: 'Dropout and Regularisation', track: 'dl', level: 'Intermediate', poster: 1,
    summary: 'Big networks memorise. Dropout, weight decay, early stopping and augmentation keep them honest — see dropout flicker neurons on and off.',
    scenes: [
      { kit: 'title', title: 'Dropout & Regularisation', sub: 'Stopping networks from memorising', track: 'Deep Learning', chapter: 'Introduction', say: 'Neural networks can have millions of parameters, enough to memorise their training data. Regularisation techniques stop that and help them generalise.' },
      { kit: 'learning-curve', mode: 'overfit', head: 'The warning sign', chapter: 'Spotting overfitting', say: 'Here is the warning sign. Training loss keeps falling, but validation loss starts to rise. The network is memorising details of the training examples. Early stopping would halt training at the dashed line.' },
      { kit: 'dropout', chapter: 'Dropout', say: 'Dropout randomly switches off, here, about half of the hidden neurons at every training step. A different random set each time. No neuron can rely on a particular partner, so the network learns more robust, spread-out features. At test time, every neuron is used, with outputs scaled to match.' },
      { kit: 'bullets', head: 'The regularisation toolkit', items: ['Weight decay — penalise large weights', 'Early stopping — stop when validation loss stops improving', 'Data augmentation — create varied training examples', 'Dropout — randomly drop neurons during training', 'More data — the most reliable fix of all'], chapter: 'Toolkit', say: 'Other tools include weight decay, which penalises large weights; early stopping; data augmentation, which creates varied training examples; and, most reliable of all, more real data.' },
      { kit: 'compare', head: 'Training vs testing with dropout', left: { title: 'During training', items: ['Random neurons switched off each step', 'Forces redundancy', 'Like training many smaller networks'], color: 'amber' }, right: { title: 'At test time', items: ['All neurons active', 'Outputs scaled to match training', 'Like averaging those networks'], color: 'green' }, chapter: 'Train vs test', say: 'During training, dropout is like training many smaller networks that share weights. At test time, using all neurons is like averaging all of them, which usually improves accuracy on new data.' },
      { kit: 'bullets', style: 'recap', items: ['Overfitting shows as a widening train/validation gap', 'Dropout randomly disables neurons during training', 'Weight decay, early stopping and augmentation also help', 'More data is the best regulariser'], chapter: 'Recap', say: 'To recap. Watch for a widening gap between training and validation loss. Dropout, weight decay, early stopping and augmentation all fight overfitting, and more data beats them all.' }
    ],
    takeaways: ['Overfitting appears as validation loss rising while training loss keeps falling.', 'Dropout randomly disables neurons during training so features become robust.', 'At test time all neurons are used, with outputs scaled.', 'Weight decay, early stopping, augmentation and more data also reduce overfitting.'],
    quiz: [
      { q: 'What does dropout do during training?', a: ['Randomly switches off some neurons at each step', 'Deletes training data', 'Stops training early'], c: 0, why: 'A new random subset is dropped every step.' },
      { q: 'Is dropout applied when making predictions on new data?', a: ['Yes, the same way', 'No — all neurons are used, with scaled outputs', 'Only on Mondays'], c: 1, why: 'Dropout is a training-time technique.' },
      { q: 'What does early stopping use to decide when to stop?', a: ['Validation loss', 'Training time only', 'The number of layers'], c: 0, why: 'Training stops when validation performance stops improving.' }
    ],
    read: ['dropout-regularization', 'regularization-in-deep-learning', 'data-augmentation-for-vision']
  },
  {
    slug: 'recurrent-networks-and-lstm', title: 'Recurrent Networks and LSTMs', track: 'dl', level: 'Intermediate', poster: 1,
    summary: 'Networks with memory: an RNN reads a sentence word by word, carrying a hidden state; an LSTM adds gates to remember for longer.',
    scenes: [
      { kit: 'title', title: 'Recurrent Networks & LSTMs', sub: 'Neural networks with memory', track: 'Deep Learning', chapter: 'Introduction', say: 'Language, music and sensor readings are sequences, where order matters. Recurrent neural networks process sequences one step at a time, carrying a memory forward.' },
      { kit: 'rnn', chapter: 'An RNN unrolled', say: 'Here an RNN reads a sentence word by word. At each step it combines the current word with its hidden state, the memory from previous words, and produces a new hidden state. The amber arrow carries that memory forward through time.' },
      { kit: 'equation', head: 'The recurrence', parts: [{ t: 'hₜ', c: 'pink', note: 'The new hidden state after reading step t' }, { t: ' = ' }, { t: 'tanh', c: 'amber', note: 'A squashing activation' }, { t: '(' }, { t: 'W hₜ₋₁', c: 'violet', note: 'The previous memory, transformed' }, { t: ' + ' }, { t: 'U xₜ', c: 'cyan', note: 'The current input word, transformed' }, { t: ')' }], below: 'The same weights W and U are reused at every time step', chapter: 'The maths', say: 'The new hidden state combines the previous hidden state and the current input, using the same weights at every step. But long sentences cause trouble: gradients passed back through many steps tend to vanish, so plain RNNs forget early words.' },
      { kit: 'rnn', lstm: true, chapter: 'LSTM', say: 'The LSTM adds a cell state, a memory highway running along the top, and three gates. The forget gate decides what to erase. The input gate decides what new information to store. The output gate decides what to reveal. This lets LSTMs remember much longer.' },
      { kit: 'compare', head: 'RNNs vs Transformers', left: { title: 'RNN / LSTM', items: ['Reads one step at a time', 'Hard to parallelise', 'Still useful for small, streaming tasks'], color: 'violet' }, right: { title: 'Transformer', items: ['Looks at all tokens at once with attention', 'Trains in parallel on GPUs', 'Now dominant for language'], color: 'cyan' }, chapter: 'RNNs today', say: 'Since 2017, Transformers have replaced RNNs for most language tasks, because attention looks at all words at once and trains in parallel. But LSTMs remain useful for small, streaming and on-device sequence problems.' },
      { kit: 'bullets', style: 'recap', items: ['RNNs carry a hidden state from step to step', 'The same weights are reused at every step', 'Plain RNNs forget long-range information', 'LSTM gates control what to forget, store and output'], chapter: 'Recap', say: 'To recap. RNNs carry a hidden state through time with shared weights. Plain RNNs forget over long ranges. LSTMs use gates and a cell state to remember much longer.' }
    ],
    takeaways: ['RNNs process sequences step by step, carrying a hidden state.', 'The same weights are reused at every time step.', 'LSTMs add a cell state and forget, input and output gates.', 'Transformers now dominate language tasks, but LSTMs remain useful for streaming data.'],
    quiz: [
      { q: 'What carries information from one time step to the next in an RNN?', a: ['The hidden state', 'The learning rate', 'The labels'], c: 0, why: 'The hidden state is the network’s memory.' },
      { q: 'Which LSTM gate decides what to erase from memory?', a: ['Forget gate', 'Output gate', 'Input gate'], c: 0, why: 'The forget gate scales down parts of the cell state.' },
      { q: 'Why did Transformers replace RNNs for most language tasks?', a: ['Attention sees all tokens at once and trains in parallel', 'They have no weights', 'They only work on images'], c: 0, why: 'Parallel attention scales far better on modern hardware.' }
    ],
    read: ['recurrent-neural-networks', 'lstm-networks', 'gru-gated-recurrent-units', 'sequence-to-sequence-models']
  },
  {
    slug: 'embeddings-explained', title: 'Embeddings: Meaning as Vectors', track: 'dl', level: 'Beginner', poster: 2,
    summary: 'Words become points in space where similar meanings sit close together — and directions carry meaning, as in king − man + woman ≈ queen.',
    scenes: [
      { kit: 'title', title: 'Embeddings', sub: 'Turning meaning into numbers', track: 'Deep Learning', chapter: 'Introduction', say: 'Neural networks work with numbers, but words, products and users are not numbers. Embeddings turn them into lists of numbers that capture meaning.' },
      { kit: 'embedding', chapter: 'Meaning as position', say: 'Each word becomes a point in space. We draw two dimensions here, but real embeddings have hundreds. After training, words used in similar ways end up close together. Fruit near fruit, animals near animals, royalty near royalty. Nobody labelled these groups.' },
      { kit: 'embedding', mode: 'analogy', head: 'Directions carry meaning', chapter: 'Analogies', say: 'Even directions can carry meaning. The step from man to woman points the same way as the step from king to queen. So king minus man plus woman lands close to queen. This famous example comes from word2vec.' },
      { kit: 'pipeline', head: 'How embeddings are learned', steps: ['Start random', 'Predict context', 'Adjust vectors', 'Meaning emerges'], desc: ['Every word begins with a random vector.', 'Train a model to predict nearby words, or a label.', 'Gradients move vectors so predictions improve.', 'Words used in similar contexts end up close together.'], chapter: 'Training', say: 'Embeddings start random. A model is trained on a task, such as predicting nearby words. Gradients nudge the vectors, and words that appear in similar contexts drift together. Meaning emerges from usage.' },
      { kit: 'bullets', head: 'Where embeddings are used', items: ['Semantic search — find text with the same meaning', 'Recommendations — similar products, songs or films', 'Language models — the first layer of every LLM', 'Images and audio — multimodal models share one space'], chapter: 'Uses', say: 'Embeddings power semantic search, recommendations and every language model. Multimodal models even place images and text in the same space, so a photo of a dog lands near the words a dog.' },
      { kit: 'bullets', style: 'recap', items: ['Embeddings map items to vectors', 'Similar meanings → nearby points', 'Directions can encode relationships', 'Learned from how items are used'], chapter: 'Recap', say: 'To recap. Embeddings map things to vectors. Similar meanings sit close together, directions can encode relationships, and all of it is learned from usage.' }
    ],
    takeaways: ['Embeddings represent items as vectors in which similar meanings are close.', 'Directions can encode relationships: king − man + woman ≈ queen.', 'They are learned by training on tasks such as predicting context.', 'They power search, recommendations and language models — and can inherit bias from data.'],
    quiz: [
      { q: 'In a good embedding space, “mango” should be close to…', a: ['“apple”', '“bus”', '“tiger”'], c: 0, why: 'Words used in similar contexts end up nearby.' },
      { q: 'king − man + woman is closest to…', a: ['queen', 'prince', 'apple'], c: 0, why: 'The gender direction is shared between the pairs.' },
      { q: 'How are embedding vectors usually obtained?', a: ['Learned during training', 'Typed in by hand', 'Chosen alphabetically'], c: 0, why: 'They start random and are adjusted by gradient descent.' }
    ],
    read: ['embeddings-explained', 'word2vec-word-embeddings', 'semantic-search-information-retrieval']
  },
  {
    slug: 'autoencoders', title: 'Autoencoders: Compress and Reconstruct', track: 'dl', level: 'Intermediate', poster: 1,
    summary: 'Squeeze an image through a tiny bottleneck and rebuild it. Autoencoders learn compact representations — and can clean up noisy inputs.',
    scenes: [
      { kit: 'title', title: 'Autoencoders', sub: 'Learning by compressing', track: 'Deep Learning', chapter: 'Introduction', say: 'What if a network had to rebuild its own input, but through a very narrow gap? To succeed, it must learn what really matters. That is an autoencoder.' },
      { kit: 'autoencoder', chapter: 'Compress and rebuild', say: 'The encoder squeezes a 196 pixel image into a code of just four numbers. The decoder tries to rebuild the image from those four numbers. Training minimises the difference between input and output, so the bottleneck is forced to keep only the essential information.' },
      { kit: 'autoencoder', denoise: true, chapter: 'Denoising', say: 'A denoising autoencoder is given a noisy version of the image but trained to output the clean original. It learns what real images look like, so it can remove noise it has never seen before.' },
      { kit: 'bullets', head: 'What autoencoders are used for', items: ['Compression — compact codes for images or signals', 'Denoising — clean up noisy inputs', 'Anomaly detection — unusual inputs reconstruct badly', 'Representation learning — codes become useful features'], chapter: 'Uses', say: 'Autoencoders compress data, remove noise, and detect anomalies: if something reconstructs badly, it probably looks unlike the training data. Their codes also make useful features for other models.' },
      { kit: 'compare', head: 'Autoencoder vs variational autoencoder', left: { title: 'Autoencoder', items: ['Each input → one fixed code', 'Great for compression and denoising', 'Not designed for generating new data'], color: 'cyan' }, right: { title: 'Variational autoencoder', items: ['Each input → a distribution of codes', 'Smooth, organised latent space', 'Sample new codes to generate new data'], color: 'pink' }, chapter: 'VAEs', say: 'A variational autoencoder encodes each input as a small distribution instead of a single point. That keeps the latent space smooth and organised, so you can sample new codes and generate brand new images.' },
      { kit: 'bullets', style: 'recap', items: ['Encoder compresses, decoder reconstructs', 'The bottleneck forces useful representations', 'Denoising, compression and anomaly detection', 'VAEs make the code space generative'], chapter: 'Recap', say: 'To recap. An encoder compresses and a decoder reconstructs. The bottleneck forces useful representations. Autoencoders denoise, compress and detect anomalies, and VAEs turn the idea into a generator.' }
    ],
    takeaways: ['An autoencoder learns to reconstruct its input through a narrow bottleneck.', 'The encoder produces a compact code; the decoder rebuilds the input.', 'Denoising autoencoders learn to map noisy inputs to clean outputs.', 'Variational autoencoders learn a smooth latent space for generation.'],
    quiz: [
      { q: 'What is an autoencoder trained to output?', a: ['Its own input (or a clean version of it)', 'A class label', 'Random noise'], c: 0, why: 'The target is the input itself.' },
      { q: 'Why is the bottleneck small?', a: ['To force the network to keep only essential information', 'To save disk space only', 'Because larger codes are illegal'], c: 0, why: 'A narrow code prevents simply copying the input.' },
      { q: 'How can autoencoders detect anomalies?', a: ['Unusual inputs reconstruct poorly', 'They count pixels', 'They never can'], c: 0, why: 'High reconstruction error signals something unlike the training data.' }
    ],
    read: ['autoencoders', 'variational-autoencoders', 'anomaly-detection']
  },
  {
    slug: 'generative-adversarial-networks', title: 'Generative Adversarial Networks (GANs)', track: 'dl', level: 'Intermediate', poster: 1,
    summary: 'A forger and a detective train together. Watch the generator’s fake distribution move until it matches real data.',
    scenes: [
      { kit: 'title', title: 'Generative Adversarial Networks', sub: 'A forger versus a detective', track: 'Deep Learning', chapter: 'Introduction', say: 'In 2014, Ian Goodfellow and colleagues proposed a clever game between two neural networks. It led to strikingly realistic generated faces and images. These are GANs.' },
      { kit: 'compare', head: 'Two players', left: { title: 'Generator (forger)', items: ['Takes random noise', 'Produces fake samples', 'Wins by fooling the discriminator'], color: 'pink' }, right: { title: 'Discriminator (detective)', items: ['Sees real and fake samples', 'Outputs the probability of “real”', 'Wins by catching fakes'], color: 'amber' }, chapter: 'Two players', say: 'The generator is a forger. It turns random noise into fake samples. The discriminator is a detective. It looks at real and fake samples and tries to tell them apart. Each network trains to beat the other.' },
      { kit: 'gan', chapter: 'The training game', say: 'Here the green curve is real data. The pink curve is what the generator produces. At first its fakes are obviously wrong, and the discriminator, the dashed line, easily separates them. Round by round, the generator improves until its distribution matches the real one, and the discriminator can only guess: about fifty-fifty.' },
      { kit: 'pipeline', head: 'One training round', steps: ['Sample noise', 'Generate fakes', 'Train discriminator', 'Train generator'], desc: ['Draw random input vectors.', 'The generator turns them into fake samples.', 'Update the discriminator to label real as real and fake as fake.', 'Update the generator so the discriminator calls its fakes real.'], chapter: 'The loop', say: 'Each round: sample noise, generate fakes, update the discriminator to tell real from fake, then update the generator to fool the updated discriminator. Repeat thousands of times.' },
      { kit: 'compare', head: 'GANs today', left: { title: 'Strengths', items: ['Very sharp, realistic images', 'Fast generation in one pass', 'StyleGAN, image-to-image translation'], color: 'green' }, right: { title: 'Challenges', items: ['Unstable training', 'Mode collapse: little variety', 'Diffusion models now lead for text-to-image'], color: 'red' }, chapter: 'Strengths and challenges', say: 'GANs generate sharp images in a single pass. But training can be unstable, and they can suffer mode collapse, producing little variety. For text to image generation, diffusion models have largely taken over.' },
      { kit: 'bullets', style: 'recap', items: ['Generator creates fakes from noise', 'Discriminator tells real from fake', 'They improve by competing', 'At equilibrium, fakes match the real distribution'], chapter: 'Recap', say: 'To recap. The generator creates fakes, the discriminator judges them, and competition drives both to improve, until the fakes match reality.' }
    ],
    takeaways: ['A GAN trains a generator and a discriminator against each other.', 'The generator learns to turn noise into realistic samples.', 'At equilibrium, the discriminator outputs about 0.5 for everything.', 'GANs can be unstable and suffer mode collapse; diffusion models now lead text-to-image.'],
    quiz: [
      { q: 'What does the discriminator output?', a: ['The probability that a sample is real', 'A new image', 'The learning rate'], c: 0, why: 'It judges real versus fake.' },
      { q: 'What is mode collapse?', a: ['The generator produces very little variety', 'The discriminator stops working', 'Training finishes early'], c: 0, why: 'The generator finds a few outputs that fool the discriminator and repeats them.' },
      { q: 'At the ideal end of training, the discriminator’s output is about…', a: ['0.5', '1.0', '0.0'], c: 0, why: 'If fakes match reality, it can only guess.' }
    ],
    read: ['generative-adversarial-networks', 'gan-variants-stylegan-cyclegan', 'generative-vs-discriminative-models']
  }
];
