/* AI in Motion — Generative AI track. © Janin A Apurba, CSE, AUST */
module.exports = [
  {
    slug: 'generative-vs-discriminative-models', title: 'Generative vs Discriminative Models', track: 'gen', level: 'Beginner',
    summary: 'One kind of model learns where the boundary is; the other learns what the data looks like — and can create new examples.',
    scenes: [
      { kit: 'title', title: 'Generative vs Discriminative', sub: 'Drawing boundaries vs learning the data', track: 'Generative AI', chapter: 'Introduction', say: 'Generative AI can write, draw and compose. What makes a model generative? It comes down to what the model learns about the data.' },
      { kit: 'gen-disc', chapter: 'Two ways to learn', say: 'A discriminative model only learns the boundary between classes: is this pink or blue? A generative model learns what each class looks like, here as a cloud of probability. Because it knows the shape of the data, it can draw brand new samples from it, the amber circles.' },
      { kit: 'compare', head: 'Side by side', left: { title: 'Discriminative', items: ['Learns P(label | data)', 'Logistic regression, most classifiers', 'Answers: which class?'], color: 'cyan' }, right: { title: 'Generative', items: ['Learns P(data) or P(data | label)', 'VAEs, GANs, diffusion, LLMs', 'Can create new data'], color: 'violet' }, chapter: 'The difference', say: 'Discriminative models learn the probability of a label given the data. Generative models learn the probability of the data itself. That is harder, but it lets them create new images, text and sound.' },
      { kit: 'timeline', head: 'Generative model families', events: [['2013', 'Variational autoencoders'], ['2014', 'GANs'], ['2018', 'GPT: generative pre-training'], ['2020', 'Diffusion models (DDPM)'], ['2022', 'Stable Diffusion, ChatGPT']], chapter: 'Families', say: 'Generative AI grew through several families: variational autoencoders in 2013, GANs in 2014, generative pre-trained transformers from 2018, diffusion models from 2020, and in 2022 Stable Diffusion and ChatGPT brought them to everyone.' },
      { kit: 'bullets', style: 'recap', items: ['Discriminative: learn the boundary', 'Generative: learn the data distribution', 'Knowing the distribution lets you sample new data', 'VAEs, GANs, diffusion and LLMs are generative'], chapter: 'Recap', say: 'To recap. Discriminative models learn boundaries. Generative models learn the data itself, which lets them sample new examples. VAEs, GANs, diffusion models and language models are all generative.' }
    ],
    takeaways: ['Discriminative models learn P(label | data); generative models learn P(data).', 'Generative models can sample brand-new examples.', 'Major families: VAEs, GANs, autoregressive models (LLMs) and diffusion models.', 'Generative modelling is harder but far more flexible.'],
    quiz: [
      { q: 'What does a discriminative model learn?', a: ['The boundary between classes, P(label | data)', 'How to generate new images', 'The full data distribution'], c: 0, why: 'It focuses on separating classes.' },
      { q: 'Why can generative models create new examples?', a: ['They model the distribution of the data itself', 'They memorise all training data', 'They use larger GPUs'], c: 0, why: 'Sampling from the learned distribution produces new data.' },
      { q: 'Which is a generative model?', a: ['A diffusion model', 'Logistic regression', 'A decision boundary'], c: 0, why: 'Diffusion models generate data.' }
    ],
    read: ['generative-vs-discriminative-models', 'variational-autoencoders', 'generative-adversarial-networks']
  },
  {
    slug: 'variational-autoencoders', title: 'Variational Autoencoders', track: 'gen', level: 'Intermediate',
    summary: 'Encode inputs as small probability clouds in a smooth latent space — then walk through that space to generate and morph new data.',
    scenes: [
      { kit: 'title', title: 'Variational Autoencoders', sub: 'A smooth space of possibilities', track: 'Generative AI', chapter: 'Introduction', say: 'An ordinary autoencoder compresses and rebuilds data. A variational autoencoder, or VAE, organises its compressed codes so neatly that we can generate brand new data from them.' },
      { kit: 'autoencoder', chapter: 'Encode and decode', say: 'Recall the autoencoder: an encoder squeezes the input into a small code, and a decoder rebuilds it. A VAE does the same, but the encoder outputs a small probability cloud, a mean and a spread, instead of one exact point.' },
      { kit: 'equation', head: 'The VAE objective', size: 42, parts: [{ t: 'Loss', c: 'red', note: 'What the VAE minimises during training' }, { t: ' = ' }, { t: 'reconstruction', c: 'cyan', note: 'Rebuild the input well from a sampled code' }, { t: ' + ' }, { t: 'KL', c: 'amber', note: 'KL divergence: keep each code cloud close to a standard normal distribution' }], below: 'Two forces: be accurate, and keep the latent space tidy', chapter: 'Two forces', say: 'Training balances two forces. The reconstruction term says: rebuild the input accurately. The KL term says: keep every code cloud close to a simple standard normal shape. Together they make the latent space smooth and gap-free.' },
      { kit: 'vae-latent', chapter: 'Walking the latent space', say: 'Because the space is smooth, nearby codes decode to similar outputs. In this illustration, one direction changes the shape from circle to square, and the other changes the colour. Walking through the space morphs smoothly between them. Sampling a random point generates something new.' },
      { kit: 'compare', head: 'VAEs today', left: { title: 'Strengths', items: ['Stable training', 'Smooth, meaningful latent space', 'Fast sampling'], color: 'green' }, right: { title: 'Limits and uses', items: ['Samples can look blurry', 'Used inside Stable Diffusion to compress images', 'Used for anomaly detection and design exploration'], color: 'violet' }, chapter: 'VAEs today', say: 'VAEs train stably and give meaningful latent spaces, though their samples can look blurry. Today a VAE sits inside Stable Diffusion, compressing images so diffusion can run in a small latent space.' },
      { kit: 'bullets', style: 'recap', items: ['Encoder outputs a mean and spread, not a point', 'Loss = reconstruction + KL divergence', 'Smooth latent space → sampling and morphing', 'VAEs power latent diffusion models'], chapter: 'Recap', say: 'To recap. VAEs encode inputs as probability clouds, balance reconstruction against a tidy latent space, and let us sample and morph. They also power latent diffusion.' }
    ],
    takeaways: ['A VAE encoder outputs a distribution (mean and variance) for each input.', 'The loss combines reconstruction error with a KL-divergence regulariser.', 'The resulting latent space is smooth, so sampling and interpolation work.', 'VAEs compress images in latent diffusion models such as Stable Diffusion.'],
    quiz: [
      { q: 'What does a VAE encoder output?', a: ['A mean and a spread (a distribution)', 'A class label', 'The final image'], c: 0, why: 'Codes are probability clouds.' },
      { q: 'What does the KL term encourage?', a: ['Codes close to a standard normal distribution', 'Sharper images', 'Faster decoding'], c: 0, why: 'It keeps the latent space tidy.' },
      { q: 'Where is a VAE used in Stable Diffusion?', a: ['To compress images into a latent space', 'To tokenise text', 'To rank search results'], c: 0, why: 'Diffusion runs in the VAE’s latent space.' }
    ],
    read: ['variational-autoencoders', 'autoencoders', 'latent-diffusion-stable-diffusion']
  },
  {
    slug: 'diffusion-models-in-depth', title: 'Diffusion Models in Depth', track: 'gen', level: 'Intermediate',
    summary: 'The forward process adds noise on a schedule; a neural network learns to reverse it. See the real DDPM noise schedule and latent diffusion.',
    scenes: [
      { kit: 'title', title: 'Diffusion Models in Depth', sub: 'Destroy with noise, learn to restore', track: 'Generative AI', chapter: 'Introduction', say: 'Diffusion models power most of today’s image generators. Their training has two halves: slowly destroying images with noise, and learning to undo it.' },
      { kit: 'noise-schedule', chapter: 'The forward process', say: 'The forward process adds a little Gaussian noise at each of a thousand steps, following a schedule. The green curve shows how much of the original image survives. At step 250 it is about 72 percent, at step 500 about 28 percent, and by the final step almost nothing: pure noise. Handily, we can jump straight to any step with one formula.' },
      { kit: 'diffusion', head: 'The reverse process', prompt: 'a pink heart icon', chapter: 'The reverse process', say: 'A neural network, usually a U-Net or a Transformer, is trained to predict the noise in a noisy image at any step. To generate, start from pure noise and repeatedly subtract the predicted noise, step by step, until an image appears.' },
      { kit: 'pipeline', head: 'Latent diffusion (Stable Diffusion)', steps: ['Text prompt', 'Text encoder', 'Denoise in latent space', 'VAE decoder', 'Image'], desc: ['Describe what you want.', 'Turn the prompt into embeddings (e.g. CLIP’s text encoder).', 'Run diffusion on a small compressed latent, guided by the prompt.', 'Decode the finished latent back into full-size pixels.', 'A high-resolution picture in seconds.'], chapter: 'Latent diffusion', say: 'Running diffusion on full-size pixels is expensive. Latent diffusion, used by Stable Diffusion, works on a small compressed version from a VAE. A text encoder turns the prompt into embeddings that guide every step, and the VAE decoder turns the result back into pixels.' },
      { kit: 'bullets', head: 'Making it faster', items: ['Fewer steps with smarter samplers (DDIM and others)', 'Distillation into few-step or one-step models', 'Latent space instead of pixels', 'Same ideas extend to video, audio and 3-D'], chapter: 'Speed-ups', say: 'Early diffusion models needed hundreds of steps. Smarter samplers and distillation now produce good images in a handful of steps, and the same ideas generate video, audio and 3D shapes.' },
      { kit: 'bullets', style: 'recap', items: ['Forward: add noise on a schedule until pure noise', 'Train a network to predict the added noise', 'Reverse: denoise step by step from random noise', 'Latent diffusion runs in a compressed space, guided by text'], chapter: 'Recap', say: 'To recap. Add noise on a schedule, train a network to predict it, then reverse the process from pure noise. Latent diffusion does it in a compressed space, guided by text.' }
    ],
    takeaways: ['The forward process adds Gaussian noise following a schedule (e.g. linear β, 1000 steps).', 'In the demo, √ᾱ is about 0.72 at t = 250 and 0.28 at t = 500.', 'A network learns to predict the noise; generation reverses the process.', 'Latent diffusion runs in a VAE latent space, guided by text embeddings.'],
    quiz: [
      { q: 'What does the forward diffusion process do?', a: ['Gradually adds noise to an image', 'Removes noise from an image', 'Encodes text'], c: 0, why: 'Noise is added step by step until the image is destroyed.' },
      { q: 'What is the network trained to predict?', a: ['The noise added at a given step', 'The prompt', 'The number of steps'], c: 0, why: 'Predicting noise lets it denoise.' },
      { q: 'Why does latent diffusion use a VAE?', a: ['To work in a smaller compressed space, which is much cheaper', 'To add more noise', 'To tokenise prompts'], c: 0, why: 'Denoising small latents is far faster than full pixels.' }
    ],
    read: ['diffusion-models', 'latent-diffusion-stable-diffusion', 'text-to-image-and-video-generation']
  },
  {
    slug: 'classifier-free-guidance', title: 'Classifier-Free Guidance', track: 'gen', level: 'Advanced',
    summary: 'How image generators follow prompts more closely: combine a conditional and an unconditional prediction and push further in the prompt’s direction.',
    scenes: [
      { kit: 'title', title: 'Classifier-Free Guidance', sub: 'Turning up the prompt', track: 'Generative AI', chapter: 'Introduction', say: 'Image generators have a setting called guidance scale or CFG. It controls how strongly the image follows your prompt. Here is what it does under the hood.' },
      { kit: 'cfg', chapter: 'Vector arithmetic', say: 'At each step, the model predicts the noise twice: once without the prompt, the grey arrow, and once with the prompt, the blue arrow. The difference between them points in the prompt’s direction. Guidance takes the unconditional prediction and moves w times along that direction. With w equal to one we get the plain conditional prediction. With w of three or seven and a half, we push further, so the prompt has a stronger effect.' },
      { kit: 'bullets', head: 'Training for guidance', items: ['During training, the prompt is randomly dropped (e.g. 10% of the time)', 'So one network learns both conditional and unconditional predictions', 'No separate classifier is needed — hence “classifier-free”'], chapter: 'Training trick', say: 'The trick is in training: the prompt is randomly dropped some of the time, so a single network learns to predict both with and without the prompt. No separate classifier is needed, which is why it is called classifier free.' },
      { kit: 'compare', head: 'Choosing the scale', left: { title: 'Low guidance', items: ['More varied and natural', 'May ignore parts of the prompt'], color: 'cyan' }, right: { title: 'High guidance', items: ['Follows the prompt closely', 'Too high: over-saturated, artificial'], color: 'pink' }, chapter: 'Choosing w', say: 'Low guidance gives varied, natural images that may drift from the prompt. High guidance follows the prompt closely, but too high produces harsh, over-saturated images. Values around seven are a common default.' },
      { kit: 'bullets', style: 'recap', items: ['Predict noise with and without the prompt', 'Guided = unconditional + w × (conditional − unconditional)', 'Prompt dropout during training enables it', 'Higher w = stronger prompt adherence, less variety'], chapter: 'Recap', say: 'To recap. Guidance combines two predictions and pushes in the prompt’s direction. Prompt dropout during training makes it possible, and the scale trades prompt adherence for variety.' }
    ],
    takeaways: ['Classifier-free guidance combines conditional and unconditional predictions.', 'ε̂ = ε_uncond + w · (ε_cond − ε_uncond); w = 1 is plain conditioning.', 'Randomly dropping the prompt during training teaches both predictions.', 'Higher guidance increases prompt adherence but reduces diversity.'],
    quiz: [
      { q: 'What happens when w = 1?', a: ['You get the ordinary conditional prediction', 'The prompt is ignored', 'The image is pure noise'], c: 0, why: 'ε_uncond + 1·(ε_cond − ε_uncond) = ε_cond.' },
      { q: 'How does one network learn the unconditional prediction?', a: ['The prompt is randomly dropped during training', 'A second network is trained', 'It is never learned'], c: 0, why: 'Prompt dropout teaches both modes.' },
      { q: 'What is a downside of very high guidance?', a: ['Over-saturated, less varied images', 'Slower tokenization', 'Blurry text prompts'], c: 0, why: 'Pushing too far distorts images.' }
    ],
    read: ['classifier-free-guidance', 'diffusion-models']
  },
  {
    slug: 'how-llms-are-trained', title: 'How Large Language Models Are Trained', track: 'gen', level: 'Intermediate',
    summary: 'Pre-training on vast text, instruction tuning, and learning from human preferences — plus the scaling laws that made models grow.',
    scenes: [
      { kit: 'title', title: 'How LLMs Are Trained', sub: 'From next-token prediction to helpful assistant', track: 'Generative AI', chapter: 'Introduction', say: 'A chatbot like ChatGPT or Claude is not trained in one step. It goes through several stages, each teaching something different.' },
      { kit: 'pipeline', head: 'The three stages', steps: ['Pre-training', 'Instruction tuning', 'Preference tuning'], desc: ['Predict the next token across a huge amount of text: language, facts and patterns emerge.', 'Fine-tune on example conversations and tasks so the model follows instructions.', 'Learn from human (or AI) preferences to be more helpful, honest and harmless.'], chapter: 'Three stages', say: 'First, pre-training: predict the next token across an enormous amount of text. Knowledge and language skills emerge. Second, instruction tuning on example conversations, so the model follows requests. Third, preference tuning, so answers become more helpful and safer.' },
      { kit: 'scaling', chapter: 'Scaling laws', say: 'Researchers found scaling laws: as models, data and compute grow, the loss falls in a smooth and predictable way, with diminishing returns. That predictability justified training ever larger models. This curve is illustrative, but the pattern is real.' },
      { kit: 'rlhf', chapter: 'Learning from preferences', say: 'In preference tuning, people compare pairs of answers. Here, response A is clear and child friendly, so it is preferred. A reward model learns to predict these preferences, and the language model is tuned to earn higher reward, with methods like PPO, or more directly with DPO.' },
      { kit: 'bullets', head: 'What each stage gives', items: ['Pre-training — knowledge, grammar, reasoning patterns', 'Instruction tuning — follows requests, answers in the right format', 'Preference tuning — tone, helpfulness, refusing harmful requests', 'None of them guarantees truth — outputs still need checking'], chapter: 'What each stage adds', say: 'Pre-training gives knowledge and language. Instruction tuning gives the ability to follow requests. Preference tuning shapes tone, helpfulness and safety. But none of them guarantees the truth, so important outputs still need checking.' },
      { kit: 'bullets', style: 'recap', items: ['Pre-train: next-token prediction on vast text', 'Instruction-tune on demonstrations', 'Preference-tune with RLHF or DPO', 'Scaling laws: predictable gains with size, data and compute'], chapter: 'Recap', say: 'To recap. Pre-train on vast text, instruction-tune on examples, preference-tune with human feedback, and scale up following predictable laws.' }
    ],
    takeaways: ['LLMs are pre-trained on next-token prediction over very large text corpora.', 'Instruction tuning teaches them to follow requests.', 'RLHF or DPO uses preference comparisons to improve helpfulness and safety.', 'Scaling laws show loss falling predictably with model size, data and compute.'],
    quiz: [
      { q: 'What is the objective during pre-training?', a: ['Predict the next token', 'Classify images', 'Maximise human ratings'], c: 0, why: 'Pre-training is next-token prediction on text.' },
      { q: 'What does a reward model learn in RLHF?', a: ['To predict which answers people prefer', 'To tokenise text', 'To translate languages'], c: 0, why: 'It is trained on human preference comparisons.' },
      { q: 'What do scaling laws describe?', a: ['How loss falls predictably as size, data and compute grow', 'The price of GPUs', 'How fast tokens are generated'], c: 0, why: 'Performance improves smoothly with scale.' }
    ],
    read: ['pretraining-llms-data-and-objectives', 'instruction-tuning', 'rlhf-reinforcement-learning-human-feedback', 'scaling-laws', 'dpo-preference-optimization']
  },
  {
    slug: 'decoding-temperature-and-top-p', title: 'Decoding: Temperature, Top-k and Top-p', track: 'gen', level: 'Beginner',
    summary: 'How a language model picks each word from its probabilities — and how temperature, top-k and top-p change its personality.',
    scenes: [
      { kit: 'title', title: 'Temperature, Top-k and Top-p', sub: 'How language models choose their words', track: 'Generative AI', chapter: 'Introduction', say: 'A language model outputs probabilities for the next token. How we pick from them, called decoding, changes whether the text is safe and predictable or creative and surprising.' },
      { kit: 'sampling', mode: 'temp', chapter: 'Temperature', say: 'After the sky is, the model gives blue 46 percent at temperature one. Lower the temperature to 0.4, and the distribution sharpens: blue jumps to about 77 percent. Raise it to 2 and it flattens: blue falls to about 31 percent, and unusual words like purple get a real chance.' },
      { kit: 'equation', head: 'Softmax with temperature', parts: [{ t: 'p(i)', c: 'green', note: 'Probability of candidate token i' }, { t: ' = e^(' }, { t: 'zᵢ', c: 'cyan', note: 'The model’s raw score (logit) for token i' }, { t: ' / ' }, { t: 'T', c: 'amber', note: 'Temperature: divide scores before softmax. T < 1 sharpens, T > 1 flattens.' }, { t: ') / Σ …' }], chapter: 'The formula', say: 'Temperature simply divides the raw scores before the softmax. Below one, differences grow and the top choice dominates. Above one, differences shrink and choices even out.' },
      { kit: 'sampling', mode: 'topk', chapter: 'Top-k and top-p', say: 'Top k keeps only the k most likely tokens, here three, and samples among them. Top p, or nucleus sampling, keeps the smallest set whose probabilities add up to 90 percent. Here that is four tokens. Both cut off the long tail of unlikely, often nonsensical choices.' },
      { kit: 'compare', head: 'Choosing settings', left: { title: 'Factual tasks', items: ['Low temperature (0–0.3)', 'Code, extraction, answers', 'Consistent and precise'], color: 'cyan' }, right: { title: 'Creative tasks', items: ['Higher temperature (0.7–1.0)', 'Top-p around 0.9', 'Stories, brainstorming, variety'], color: 'pink' }, chapter: 'Practical settings', say: 'For factual work like code or data extraction, use a low temperature for consistent answers. For brainstorming and stories, a higher temperature with top p around 0.9 gives variety without nonsense.' },
      { kit: 'bullets', style: 'recap', items: ['Decoding picks tokens from the model’s probabilities', 'Temperature sharpens (low) or flattens (high)', 'Top-k keeps k tokens; top-p keeps a probability mass', 'Low for facts, higher for creativity'], chapter: 'Recap', say: 'To recap. Decoding chooses from probabilities. Temperature sharpens or flattens them. Top k and top p trim the unlikely tail. Low for facts, higher for creativity.' }
    ],
    takeaways: ['Temperature divides logits before softmax: T < 1 sharpens, T > 1 flattens.', 'In the demo “blue” is 76.7% at T = 0.4, 46.2% at T = 1 and 31.4% at T = 2.', 'Top-k keeps the k most likely tokens; top-p keeps the smallest set covering p of the probability.', 'Use low temperature for factual tasks and higher for creative ones.'],
    quiz: [
      { q: 'What does lowering the temperature do?', a: ['Makes the top choice even more likely', 'Makes all choices equal', 'Adds new words'], c: 0, why: 'Dividing by a small T exaggerates differences.' },
      { q: 'Top-p = 0.9 keeps…', a: ['The smallest set of tokens whose probabilities sum to at least 90%', 'Exactly 9 tokens', 'Tokens with probability above 0.9'], c: 0, why: 'Nucleus sampling uses cumulative probability.' },
      { q: 'Which setting suits extracting data from invoices?', a: ['Low temperature', 'Very high temperature', 'Top-k = 1000'], c: 0, why: 'Precision matters more than variety.' }
    ],
    read: ['decoding-strategies-sampling', 'large-language-models-overview']
  },
  {
    slug: 'prompt-engineering-and-chain-of-thought', title: 'Prompt Engineering and Chain-of-Thought', track: 'gen', level: 'Beginner',
    summary: 'Clear roles, context, examples and step-by-step reasoning: how to get much better answers from language models.',
    scenes: [
      { kit: 'title', title: 'Prompt Engineering', sub: 'Asking language models the right way', track: 'Generative AI', chapter: 'Introduction', say: 'The same model can give a vague answer or an excellent one, depending on how you ask. Prompt engineering is the skill of asking well.' },
      { kit: 'pipeline', head: 'Building blocks of a good prompt', steps: ['Role', 'Context', 'Task', 'Constraints', 'Format'], desc: ['“You are an experienced maths teacher.”', 'Who it is for, what you already know, relevant documents.', 'A clear, specific instruction with a verb.', 'Length, tone, what to avoid.', 'Bullet list, table, JSON — whatever you need.'], chapter: 'Building blocks', say: 'Strong prompts usually include a role, the context, a clear task, constraints such as length and tone, and the output format you want. When an answer disappoints, one of these is usually missing.' },
      { kit: 'chat', head: 'Few-shot examples', msgs: [['user', 'Classify the sentiment. “Loved the food!” → positive. “Waited an hour.” → negative. “The staff were so kind.” →'], ['assistant', 'positive']], chapter: 'Few-shot prompting', say: 'Showing a few examples in the prompt, called few shot prompting, teaches the model the pattern you want without any training. It is a form of in-context learning.' },
      { kit: 'chat', head: 'Chain-of-thought', msgs: [['user', 'A pen and a notebook cost 110 taka. The notebook costs 100 taka more than the pen. How much is the pen? Think step by step.'], ['assistant', 'Let the pen cost x. Then the notebook costs x + 100. So x + (x + 100) = 110, 2x = 10, x = 5. The pen costs 5 taka.']], chapter: 'Thinking step by step', say: 'For reasoning problems, asking the model to think step by step, or using a model with built-in reasoning, often improves accuracy. The quick answer here is ten taka, which is wrong. Working it out shows the pen costs five taka.' },
      { kit: 'bullets', head: 'Tips that work', items: ['Be specific — say exactly what “good” looks like', 'Give examples of the output you want', 'Break big tasks into smaller steps', 'Ask for sources, and verify important facts'], chapter: 'Tips', say: 'Be specific. Give examples. Break big tasks into steps. Ask for sources, and always verify important facts, because a well-phrased prompt still does not guarantee a correct answer.' },
      { kit: 'bullets', style: 'recap', items: ['Role, context, task, constraints, format', 'Few-shot examples teach patterns in context', 'Step-by-step reasoning improves hard problems', 'Iterate — and verify'], chapter: 'Recap', say: 'To recap. Give role, context, task, constraints and format. Use examples. Ask for step by step reasoning on hard problems. Iterate, and verify.' }
    ],
    takeaways: ['Good prompts specify role, context, task, constraints and format.', 'Few-shot examples teach a pattern through in-context learning.', 'Step-by-step (chain-of-thought) reasoning improves multi-step problems.', 'Prompting improves answers but never guarantees correctness.'],
    quiz: [
      { q: 'What is few-shot prompting?', a: ['Including a few worked examples in the prompt', 'Training the model for a few steps', 'Using very short prompts'], c: 0, why: 'Examples show the desired pattern.' },
      { q: 'In the pen-and-notebook puzzle, what does the pen cost?', a: ['5 taka', '10 taka', '100 taka'], c: 0, why: 'x + (x + 100) = 110 gives x = 5.' },
      { q: 'Why ask for step-by-step reasoning?', a: ['It often improves accuracy on multi-step problems', 'It makes answers shorter', 'It changes the model’s training data'], c: 0, why: 'Intermediate steps help the model avoid quick wrong answers.' }
    ],
    read: ['prompt-engineering', 'chain-of-thought-reasoning', 'in-context-learning']
  },
  {
    slug: 'retrieval-augmented-generation', title: 'Retrieval-Augmented Generation (RAG)', track: 'gen', level: 'Intermediate',
    summary: 'Give a language model the right documents at the right moment: retrieve relevant passages, then generate a grounded answer with citations.',
    scenes: [
      { kit: 'title', title: 'Retrieval-Augmented Generation', sub: 'Answers grounded in your own documents', track: 'Generative AI', chapter: 'Introduction', say: 'Language models do not know your company’s policies or last week’s news, and they sometimes make things up. Retrieval augmented generation, or RAG, fixes both by looking things up first.' },
      { kit: 'rag', chapter: 'The RAG pipeline', say: 'The question is embedded into a vector. A vector store finds the most similar passages from your documents: the leave policy, and the carry-over rule. These chunks are placed into the prompt, and the language model writes an answer based on them: twenty days of paid leave, with up to five days carrying over, citing its sources.' },
      { kit: 'vector-search', head: 'Step 1: retrieval', chapter: 'Retrieval', say: 'Retrieval is semantic search. Because it matches meaning, a question like I can’t sign in finds the password reset guide even though they share no words.' },
      { kit: 'bullets', head: 'Getting RAG right', items: ['Chunking — split documents into sensible passages', 'Good embeddings and hybrid (keyword + vector) search', 'Re-rank the top results before generating', 'Tell the model to answer only from the sources and cite them'], chapter: 'Best practices', say: 'Quality depends on the details. Split documents sensibly, use good embeddings with hybrid search, re-rank results, and instruct the model to answer only from the retrieved sources, with citations.' },
      { kit: 'compare', head: 'RAG vs fine-tuning', left: { title: 'RAG', items: ['Adds knowledge at question time', 'Easy to update: change the documents', 'Answers can cite sources'], color: 'green' }, right: { title: 'Fine-tuning', items: ['Changes the model’s behaviour and style', 'Needs retraining to update', 'Good for format, tone and specialised skills'], color: 'violet' }, chapter: 'RAG vs fine-tuning', say: 'RAG adds knowledge at question time and is easy to keep up to date. Fine-tuning changes the model’s behaviour and style. Many real systems use both.' },
      { kit: 'bullets', style: 'recap', items: ['Embed the question, retrieve relevant chunks', 'Put the chunks into the prompt', 'Generate an answer grounded in, and citing, the sources', 'Easy to update, fewer hallucinations'], chapter: 'Recap', say: 'To recap. Retrieve relevant passages, add them to the prompt, and generate a grounded answer with citations. RAG keeps answers current and reduces hallucinations.' }
    ],
    takeaways: ['RAG retrieves relevant passages and adds them to the prompt before generating.', 'Retrieval is usually semantic (embedding) search, often hybrid with keywords.', 'Grounding in retrieved text reduces hallucinations and enables citations.', 'RAG adds knowledge; fine-tuning changes behaviour — they are often combined.'],
    quiz: [
      { q: 'What happens before generation in RAG?', a: ['Relevant documents are retrieved and added to the prompt', 'The model is retrained', 'The answer is translated'], c: 0, why: 'Retrieval provides grounding context.' },
      { q: 'Why does RAG reduce hallucinations?', a: ['The model answers from retrieved source text', 'It uses a smaller model', 'It removes the prompt'], c: 0, why: 'Grounded answers rely on real documents.' },
      { q: 'How do you update a RAG system with new policies?', a: ['Update the documents in the store', 'Retrain from scratch', 'Change the temperature'], c: 0, why: 'Knowledge lives in the documents.' }
    ],
    read: ['retrieval-augmented-generation', 'vector-databases', 'building-llm-applications-end-to-end']
  },
  {
    slug: 'lora-and-parameter-efficient-fine-tuning', title: 'LoRA and Parameter-Efficient Fine-Tuning', track: 'gen', level: 'Intermediate',
    summary: 'Fine-tune a huge model by training two tiny matrices. See why LoRA needs well under 1% of the parameters of full fine-tuning.',
    scenes: [
      { kit: 'title', title: 'LoRA', sub: 'Fine-tuning giants on a budget', track: 'Generative AI', chapter: 'Introduction', say: 'Fine-tuning every weight of a billion-parameter model needs huge memory. LoRA, low-rank adaptation, gets similar results by training tiny extra matrices instead.' },
      { kit: 'lora', chapter: 'Low-rank adapters', say: 'Take one weight matrix, 4096 by 4096. That is about 16.8 million parameters. LoRA freezes it and adds the product of two thin matrices, B and A, with rank 8. They hold only 65,536 parameters, about 0.39 percent of the original, yet they can steer the model to a new task.' },
      { kit: 'equation', head: 'The idea', parts: [{ t: 'W′', c: 'green', note: 'The adapted weight used at inference time' }, { t: ' = ' }, { t: 'W', c: 'blue', note: 'Original pre-trained weights — frozen' }, { t: ' + ' }, { t: 'B·A', c: 'orange', note: 'Low-rank update: B is d × r, A is r × d, with r much smaller than d' }], below: 'Parameters per matrix: d² for full tuning vs 2·d·r for LoRA', chapter: 'The formula', say: 'The adapted weight equals the frozen original plus B times A. Because the rank r is small, the update has two times d times r parameters instead of d squared. After training, the update can even be merged into W, so there is no extra cost at inference.' },
      { kit: 'bullets', head: 'Why LoRA is popular', items: ['Far less GPU memory — often fits on a single GPU', 'Small adapter files (megabytes, not gigabytes)', 'Swap adapters for different tasks on one base model', 'QLoRA: combine with 4-bit quantisation for even less memory'], chapter: 'Why it matters', say: 'LoRA needs far less memory, produces small adapter files, and lets one base model switch between many tasks by swapping adapters. QLoRA combines it with four-bit quantisation, making fine-tuning possible on a single GPU.' },
      { kit: 'bullets', style: 'recap', items: ['Freeze the big pre-trained weights', 'Train small low-rank matrices B and A', '4096 × 4096 with rank 8: 65,536 vs 16.8M parameters', 'Small, swappable adapters; QLoRA saves even more memory'], chapter: 'Recap', say: 'To recap. Freeze the big weights, train small low-rank matrices, and get swappable adapters that use a tiny fraction of the parameters.' }
    ],
    takeaways: ['LoRA freezes pre-trained weights and learns a low-rank update B·A.', 'For a 4096 × 4096 matrix with rank 8: 65,536 trainable parameters instead of 16,777,216 (0.39%).', 'Adapters are small and swappable, and can be merged for inference.', 'QLoRA combines LoRA with 4-bit quantisation.'],
    quiz: [
      { q: 'What does LoRA train?', a: ['Small low-rank matrices added to frozen weights', 'Every weight in the model', 'Only the tokenizer'], c: 0, why: 'The original weights stay frozen.' },
      { q: 'How many parameters does a rank-8 LoRA update have for a 4096 × 4096 matrix?', a: ['65,536', '16,777,216', '8'], c: 0, why: '2 × 4096 × 8 = 65,536.' },
      { q: 'What does QLoRA add?', a: ['4-bit quantisation of the base model', 'More layers', 'A new tokenizer'], c: 0, why: 'Quantising the frozen model saves memory.' }
    ],
    read: ['lora-and-parameter-efficient-fine-tuning', 'fine-tuning-pretrained-language-models', 'llm-quantization']
  },
  {
    slug: 'quantization', title: 'Quantisation: Smaller, Faster Models', track: 'gen', level: 'Intermediate',
    summary: 'Store each weight in fewer bits. See weights snap to int8 and int4 levels, and how a 7B model shrinks from 28 GB to 3.5 GB.',
    scenes: [
      { kit: 'title', title: 'Quantisation', sub: 'Fewer bits per weight', track: 'Generative AI', chapter: 'Introduction', say: 'Large models are heavy. A seven billion parameter model in full precision needs about 28 gigabytes just for its weights. Quantisation makes it much smaller.' },
      { kit: 'quantize', chapter: 'Snapping to levels', say: 'Normally each weight is a 32-bit floating point number. Int8 quantisation snaps every weight to one of 256 levels. Int4 uses only 16 levels. Memory for a seven billion parameter model falls from 28 gigabytes to 14 in 16-bit, 7 in 8-bit and 3.5 in 4-bit.' },
      { kit: 'equation', head: 'Mapping floats to integers', parts: [{ t: 'q', c: 'green', note: 'The stored integer' }, { t: ' = round(' }, { t: 'w', c: 'cyan', note: 'The original floating-point weight' }, { t: ' / ' }, { t: 's', c: 'amber', note: 'Scale: chosen so the range of weights fits the integer range' }, { t: ')' }], below: 'To use it: w ≈ q × s', chapter: 'The formula', say: 'Each weight is divided by a scale factor and rounded to the nearest integer. To use it, multiply back by the scale. The rounding error is the price we pay. Good methods choose scales per group of weights to keep errors small.' },
      { kit: 'compare', head: 'Trade-offs', left: { title: 'Benefits', items: ['4–8× less memory than FP32', 'Faster inference on supported hardware', 'Run large models on laptops and phones'], color: 'green' }, right: { title: 'Costs', items: ['Small loss in quality, larger at very low bits', 'Outlier weights need special handling', 'Some methods need calibration data'], color: 'amber' }, chapter: 'Trade-offs', say: 'Quantisation cuts memory and often speeds up inference, making large models run on laptops and phones. The cost is a small drop in quality, larger at very low bit widths, and outlier weights need careful handling.' },
      { kit: 'bullets', style: 'recap', items: ['Store weights in fewer bits: 16, 8 or 4', '7B model: 28 GB → 14 → 7 → 3.5 GB', 'q = round(w / s), with w ≈ q × s', 'Much smaller models, small quality cost'], chapter: 'Recap', say: 'To recap. Quantisation stores weights in fewer bits, shrinking a seven billion parameter model from 28 gigabytes to 3.5, with a small cost in quality.' }
    ],
    takeaways: ['Quantisation stores weights with fewer bits (e.g. 16, 8 or 4).', 'A 7B-parameter model needs about 28 GB in FP32, 14 GB in FP16, 7 GB in INT8 and 3.5 GB in INT4 (weights only).', 'Weights are scaled and rounded: q = round(w / s).', 'It trades a small loss of quality for large memory and speed gains.'],
    quiz: [
      { q: 'How much memory do the weights of a 7B model need in INT4?', a: ['About 3.5 GB', 'About 28 GB', 'About 70 GB'], c: 0, why: '7 billion × 0.5 bytes = 3.5 GB.' },
      { q: 'How many distinct levels can a 4-bit integer represent?', a: ['16', '256', '4'], c: 0, why: '2⁴ = 16.' },
      { q: 'What is the main cost of quantisation?', a: ['A small loss in accuracy from rounding', 'Much larger files', 'Longer training time'], c: 0, why: 'Rounding introduces small errors.' }
    ],
    read: ['llm-quantization', 'llm-inference-optimization', 'pruning-and-quantization']
  },
  {
    slug: 'mixture-of-experts', title: 'Mixture of Experts', track: 'gen', level: 'Advanced',
    summary: 'A router sends each token to a few specialised experts, so a model can have many parameters while using only a fraction per token.',
    scenes: [
      { kit: 'title', title: 'Mixture of Experts', sub: 'Big models, smaller compute', track: 'Generative AI', chapter: 'Introduction', say: 'What if a model could be huge, but only use a small part of itself for each word? That is the idea behind mixture of experts.' },
      { kit: 'moe', chapter: 'Routing tokens', say: 'Inside each mixture of experts layer there are several feed-forward networks, the experts, and a small router. For every token, the router scores all eight experts and sends the token to the best two. Their outputs are combined as a weighted sum. Different tokens go to different experts.' },
      { kit: 'compare', head: 'Dense vs mixture of experts', left: { title: 'Dense model', items: ['Every parameter used for every token', 'Compute grows with model size'], color: 'blue' }, right: { title: 'Mixture of experts', items: ['Only the chosen experts run per token', 'More total parameters for the same compute', 'Example: Mixtral 8×7B uses 2 of 8 experts per token'], color: 'green' }, chapter: 'Dense vs MoE', say: 'In a dense model every parameter works on every token. In a mixture of experts, only the chosen experts run, so total capacity grows without the compute growing as fast. For example, Mixtral 8 by 7B uses two of its eight experts for each token.' },
      { kit: 'bullets', head: 'Challenges', items: ['Load balancing — stop the router from overusing a few experts', 'Memory — all experts must still be stored', 'Communication — experts may live on different GPUs', 'Training stability needs care'], chapter: 'Challenges', say: 'There are challenges. The router must spread tokens fairly so some experts are not overloaded, which is handled with a load balancing loss. All experts must still fit in memory, and moving tokens between GPUs adds communication.' },
      { kit: 'bullets', style: 'recap', items: ['Many experts, a router picks the top few per token', 'Output = weighted sum of chosen experts', 'More parameters without proportional compute', 'Load balancing and memory are the main challenges'], chapter: 'Recap', say: 'To recap. A router sends each token to a few experts, their outputs are combined, and the model gains capacity without proportional compute, as long as load and memory are managed.' }
    ],
    takeaways: ['An MoE layer has several expert networks and a router.', 'Each token is sent to its top-k experts (often 2) and their outputs are combined.', 'Total parameters grow while per-token compute stays much smaller.', 'Load balancing, memory and communication are key challenges.'],
    quiz: [
      { q: 'What does the router do in an MoE layer?', a: ['Chooses which experts process each token', 'Tokenises the text', 'Removes experts permanently'], c: 0, why: 'It scores experts and picks the top ones.' },
      { q: 'Why can MoE models be cheaper per token than dense models of the same size?', a: ['Only a few experts run for each token', 'They have no parameters', 'They skip attention'], c: 0, why: 'Sparse activation saves compute.' },
      { q: 'What does a load-balancing loss prevent?', a: ['A few experts receiving almost all tokens', 'Overfitting of the tokenizer', 'Slow GPUs'], c: 0, why: 'It encourages even expert usage.' }
    ],
    read: ['mixture-of-experts', 'llm-inference-optimization', 'distributed-training']
  },
  {
    slug: 'ai-agents-and-tool-use', title: 'AI Agents and Tool Use', track: 'gen', level: 'Intermediate',
    summary: 'Language models that act: plan, call tools like search or calculators, read the results and continue until the task is done.',
    scenes: [
      { kit: 'title', title: 'AI Agents and Tool Use', sub: 'From chatting to doing', track: 'Generative AI', chapter: 'Introduction', say: 'A chatbot answers from what it already knows. An AI agent can take actions: search the web, run code, check a calendar, and use the results to finish a task.' },
      { kit: 'chat', head: 'An agent using tools', msgs: [['user', 'What is 18% VAT on a 2,450 taka order, and what is the total?'], ['call', 'calculator(2450 * 0.18)'], ['tool', '441'], ['call', 'calculator(2450 + 441)'], ['tool', '2891'], ['assistant', 'The VAT is 441 taka, so the total is 2,891 taka.']], chapter: 'A tool-using agent', say: 'Here the model does not guess the arithmetic. It calls a calculator tool: 2,450 times 0.18 is 441. It calls it again for the total, 2,891, and only then answers. The model decides which tool to call, reads the result, and continues.' },
      { kit: 'cycle', head: 'The agent loop', steps: ['Plan', 'Call a tool', 'Observe', 'Decide', 'Answer'], desc: ['Break the goal into steps', 'Search, code, calculator, API', 'Read the tool’s output', 'Is the task done?', 'Report back to the user'], chapter: 'The loop', say: 'Agents run a loop. Plan the next step, call a tool, observe the result, decide whether the task is done, and repeat until it is time to answer.' },
      { kit: 'bullets', head: 'Designing safe agents', items: ['Show what the agent is doing and why', 'Ask for approval before payments, deletions or sending messages', 'Limit tools and permissions to what the task needs', 'Treat content from web pages and files as data, not instructions'], chapter: 'Safety', say: 'Agents need careful design. Show what they are doing. Ask for approval before payments, deletions or sending messages. Give only the permissions a task needs. And treat text found on web pages as data, not as instructions, to avoid prompt injection.' },
      { kit: 'bullets', style: 'recap', items: ['Agents combine a language model with tools', 'Plan → call tool → observe → decide → repeat', 'Tools give up-to-date facts and exact results', 'Human approval for risky actions'], chapter: 'Recap', say: 'To recap. Agents combine language models with tools, loop through planning, acting and observing, get exact and current results, and should ask people before risky actions.' }
    ],
    takeaways: ['An AI agent uses a language model to plan and call tools in a loop.', 'Tools provide exact computation and up-to-date information (441 VAT, 2,891 total in the demo).', 'The loop: plan, call a tool, observe, decide, answer.', 'Safe agents limit permissions, ask for approval and resist prompt injection.'],
    quiz: [
      { q: 'Why did the agent call a calculator instead of answering directly?', a: ['Tools give exact results rather than guesses', 'It could not read the question', 'To make the answer longer'], c: 0, why: 'Language models can make arithmetic mistakes.' },
      { q: 'What should an agent do before sending an email on your behalf?', a: ['Ask for your approval', 'Send it immediately', 'Delete it'], c: 0, why: 'Risky or irreversible actions need human approval.' },
      { q: 'How should an agent treat instructions found inside a web page?', a: ['As data, not as commands', 'As top-priority commands', 'As the user’s own request'], c: 0, why: 'This protects against prompt injection.' }
    ],
    read: ['ai-agents-tool-use', 'building-llm-applications-end-to-end', 'intelligent-agents-and-environments']
  },
  {
    slug: 'multimodal-models-and-clip', title: 'Multimodal Models and CLIP', track: 'gen', level: 'Intermediate',
    summary: 'Put images and text in one shared space by pulling matching pairs together — the idea behind CLIP, image search and vision-language assistants.',
    scenes: [
      { kit: 'title', title: 'Multimodal Models', sub: 'Connecting images and language', track: 'Generative AI', chapter: 'Introduction', say: 'The newest AI assistants can look at a photo and talk about it. The key idea is to put images and text in one shared space. CLIP, from 2021, showed how.' },
      { kit: 'clip', chapter: 'Contrastive learning', say: 'CLIP has an image encoder and a text encoder. For a batch of images and their captions, it computes the similarity of every image with every caption. Training pulls the matching pairs, on the diagonal, together, and pushes mismatched pairs apart. After training, a picture of a cat sits closest to the words a sleepy cat.' },
      { kit: 'bullets', head: 'What a shared space enables', items: ['Zero-shot classification — compare an image with “a photo of a …” for each class', 'Image search with plain-language queries', 'Guiding image generators with text', 'Vision-language assistants that describe and reason about images'], chapter: 'What it enables', say: 'A shared space enables a lot. Zero-shot classification, by comparing an image with a caption for each class. Image search with plain-language queries. Guiding image generators with text. And assistants that describe and reason about pictures.' },
      { kit: 'pipeline', head: 'A vision-language assistant', steps: ['Image', 'Vision encoder', 'Projection', 'Language model', 'Answer'], desc: ['A photo or screenshot.', 'Turns the image into a set of feature vectors.', 'Maps image features into the language model’s token space.', 'Reads image tokens and your question together.', 'A description, explanation or answer in text.'], chapter: 'Vision-language models', say: 'Many vision-language assistants connect a vision encoder to a language model. The image becomes a set of vectors, a projection layer maps them into the language model’s token space, and the model reads them alongside your question.' },
      { kit: 'bullets', style: 'recap', items: ['Image and text encoders share one embedding space', 'Contrastive training: match pairs, separate the rest', 'Enables zero-shot classification and text-to-image search', 'Vision encoder + language model = multimodal assistant'], chapter: 'Recap', say: 'To recap. CLIP puts images and text in one space using contrastive training. That enables zero-shot classification and search, and connecting a vision encoder to a language model gives multimodal assistants.' }
    ],
    takeaways: ['CLIP trains an image encoder and a text encoder into one shared space.', 'Contrastive learning pulls matching image–caption pairs together and pushes others apart.', 'Shared spaces enable zero-shot classification and natural-language image search.', 'Multimodal assistants connect a vision encoder to a language model.'],
    quiz: [
      { q: 'In CLIP’s similarity matrix, which cells should be highest after training?', a: ['The diagonal — matching image–caption pairs', 'The first row', 'All cells equally'], c: 0, why: 'Matching pairs are pulled together.' },
      { q: 'How does zero-shot classification with CLIP work?', a: ['Compare the image with a text prompt for each class', 'Retrain for every new class', 'Count pixels'], c: 0, why: 'The closest class description wins.' },
      { q: 'What connects image features to a language model in many assistants?', a: ['A projection layer into the token space', 'A spreadsheet', 'A tokenizer for pixels only'], c: 0, why: 'It maps vision features into the LLM’s input space.' }
    ],
    read: ['clip-vision-language', 'multimodal-models', 'vision-transformers']
  }
];
