/* AI in Motion — Machine Learning track. © Janin A Apurba, CSE, AUST */
module.exports = [
  {
    slug: 'what-is-machine-learning', title: 'What Is Machine Learning?', track: 'ml', level: 'Beginner', poster: 3,
    summary: 'Instead of writing rules, show the computer examples. The core idea of machine learning, its three main types and the standard workflow.',
    scenes: [
      { kit: 'title', title: 'What Is Machine Learning?', sub: 'Learning from examples instead of rules', track: 'Machine Learning', chapter: 'Introduction', say: 'Traditional programs follow rules that a programmer writes. Machine learning flips this around: we show the computer examples, and it works out the rules itself.' },
      { kit: 'compare', head: 'Programming vs machine learning', left: { title: 'Traditional programming', items: ['Input: data + rules', 'Output: answers', 'Programmer writes every rule'], color: 'amber' }, right: { title: 'Machine learning', items: ['Input: data + answers', 'Output: rules (a model)', 'Algorithm learns from examples'], color: 'green' }, chapter: 'Rules vs examples', say: 'In traditional programming, you give the computer data and rules, and get answers. In machine learning, you give it data and the correct answers, and it produces the rules, which we call a model.' },
      { kit: 'bullets', head: 'Three main types of learning', items: ['Supervised — learn from labelled examples, like emails marked spam or not', 'Unsupervised — find structure in unlabelled data, like customer groups', 'Reinforcement — learn by trial and error from rewards, like a game agent'], chapter: 'Types of learning', say: 'There are three main types. Supervised learning uses labelled examples. Unsupervised learning finds structure without labels. Reinforcement learning learns by trial and error, guided by rewards.' },
      { kit: 'scatter-fit', head: 'A first example: learning a line', chapter: 'A first example', say: 'Here is supervised learning in action. Each dot is a student: hours studied and exam score. The model starts with a bad guess and adjusts itself until its line fits the data well. That adjusting process is called training.' },
      { kit: 'pipeline', head: 'The machine learning workflow', steps: ['Collect data', 'Prepare features', 'Train', 'Evaluate', 'Deploy'], desc: ['Gather examples that represent the real problem.', 'Clean the data and choose the inputs the model learns from.', 'Adjust the model’s parameters to fit the training data.', 'Test on data the model has never seen.', 'Use it in a product and monitor it over time.'], chapter: 'Workflow', say: 'Real projects follow a workflow. Collect data. Prepare features. Train the model. Evaluate it on data it has never seen. Then deploy it and keep monitoring, because the world changes.' },
      { kit: 'bullets', style: 'recap', items: ['ML learns rules from examples', 'Supervised, unsupervised and reinforcement learning', 'Training adjusts parameters to reduce error', 'Always evaluate on unseen data'], chapter: 'Recap', say: 'To recap. Machine learning learns rules from examples. There are three main types. Training adjusts the model to reduce its errors. And we always judge a model on data it has never seen.' }
    ],
    takeaways: ['Machine learning learns rules (a model) from data and answers.', 'Supervised, unsupervised and reinforcement learning are the main types.', 'Training adjusts parameters to reduce errors on examples.', 'Models must be evaluated on data they have not seen.'],
    quiz: [
      { q: 'In supervised learning the training data includes…', a: ['Only inputs', 'Inputs and correct answers (labels)', 'Only rewards'], c: 1, why: 'Supervised learning learns from labelled examples.' },
      { q: 'Grouping customers into segments without labels is…', a: ['Supervised learning', 'Unsupervised learning', 'Reinforcement learning'], c: 1, why: 'Finding structure without labels is unsupervised.' },
      { q: 'Why evaluate on unseen data?', a: ['To check the model generalises instead of memorising', 'Because it is faster', 'To make the model bigger'], c: 0, why: 'Only unseen data shows real-world performance.' }
    ],
    read: ['what-is-machine-learning', 'types-of-machine-learning', 'machine-learning-workflow']
  },
  {
    slug: 'linear-regression', title: 'Linear Regression, Visually', track: 'ml', level: 'Beginner', poster: 2,
    summary: 'Fit a straight line to data with gradient descent. Watch the residuals shrink and the mean squared error fall from 9.45 to 0.55.',
    scenes: [
      { kit: 'title', title: 'Linear Regression', sub: 'The “hello world” of machine learning', track: 'Machine Learning', chapter: 'Introduction', say: 'Does studying longer lead to higher scores? Linear regression answers questions like this by fitting a straight line through data.' },
      { kit: 'equation', head: 'The model', parts: [{ t: 'ŷ', c: 'pink', note: 'ŷ (y-hat) is the model’s prediction' }, { t: ' = ' }, { t: 'w', c: 'cyan', note: 'w is the weight or slope: how much ŷ changes per unit of x' }, { t: ' · x + ' }, { t: 'b', c: 'amber', note: 'b is the bias or intercept: the prediction when x is 0' }], below: 'Training means finding the w and b that fit the data best', chapter: 'The model', say: 'The model is a line: y hat equals w times x plus b. W is the slope, how steep the line is. B is the intercept, where it crosses the axis. Training means finding the best w and b.' },
      { kit: 'scatter-fit', chapter: 'Fitting the line', say: 'The red lines are residuals, the errors between each real score and the prediction. Gradient descent nudges w and b to shrink them. The mean squared error starts at 9.45 and falls to about 0.55 after 400 small steps.' },
      { kit: 'equation', head: 'Measuring the error', parts: [{ t: 'MSE', c: 'red', note: 'Mean squared error: the average of the squared residuals' }, { t: ' = ' }, { t: '(1/n)', c: 'cyan', note: 'Average over all n training examples' }, { t: ' Σ ' }, { t: '(ŷᵢ − yᵢ)²', c: 'pink', note: 'Squaring makes every error positive and punishes big errors more' }], below: 'Lower MSE means a better fit on the training data', chapter: 'Mean squared error', say: 'We measure the fit with the mean squared error. Take each residual, square it so it is positive and big errors count more, then average them. Lower is better.' },
      { kit: 'bullets', head: 'Where it works — and where it doesn’t', items: ['Good — roughly straight-line relationships, quick baselines', 'Good — easy to explain: “each hour adds about 0.6 points”', 'Careful — curved relationships need extra features', 'Careful — outliers can pull the line badly'], chapter: 'Strengths and limits', say: 'Linear regression is simple, fast and easy to explain. But real relationships are often curved, and a few outliers can drag the line off course. Then we add features or use more flexible models.' },
      { kit: 'bullets', style: 'recap', items: ['ŷ = w·x + b', 'Residuals are the prediction errors', 'MSE averages the squared residuals', 'Gradient descent finds w and b'], chapter: 'Recap', say: 'To recap. The model is a line. Residuals are its errors. Mean squared error measures them. And gradient descent finds the best line.' }
    ],
    takeaways: ['Linear regression fits ŷ = w·x + b.', 'Residuals are the differences between predictions and real values.', 'Mean squared error averages squared residuals; in the animation it falls from 9.45 to 0.55.', 'It is interpretable but limited to straight-line relationships.'],
    quiz: [
      { q: 'In ŷ = w·x + b, what does w control?', a: ['The slope of the line', 'Where the line crosses the y-axis', 'The number of data points'], c: 0, why: 'w is the weight or slope.' },
      { q: 'Why are errors squared in MSE?', a: ['To make them positive and punish large errors more', 'To make the numbers smaller', 'Because it is traditional only'], c: 0, why: 'Squaring removes signs and emphasises big mistakes.' },
      { q: 'What does gradient descent adjust during training?', a: ['The data', 'The parameters w and b', 'The number of students'], c: 1, why: 'Training updates the model’s parameters.' }
    ],
    read: ['linear-regression-from-first-principles', 'regression-metrics', 'polynomial-regression-basis-functions']
  },
  {
    slug: 'gradient-descent', title: 'Gradient Descent and the Learning Rate', track: 'ml', level: 'Beginner', poster: 1,
    summary: 'How almost every ML model learns: follow the slope downhill. See small, good and too-large learning rates, and how optimisers like Adam move on a loss surface.',
    scenes: [
      { kit: 'title', title: 'Gradient Descent', sub: 'Walking downhill in the fog', track: 'Machine Learning', chapter: 'Introduction', say: 'Almost every machine learning model, from linear regression to giant neural networks, learns with gradient descent. The idea is to walk downhill on the error.' },
      { kit: 'loss-curve', lr: .25, verdict: 'A good learning rate: big steps where it is steep, small steps near the bottom.', chapter: 'Following the slope', say: 'The curve shows the loss for different values of one weight. We measure the slope, the dashed line, and step the opposite way. Where it is steep, steps are big. Near the bottom, the slope flattens and steps shrink automatically.' },
      { kit: 'equation', head: 'The update rule', parts: [{ t: 'w', c: 'cyan', note: 'The weight we are learning' }, { t: ' ← w − ' }, { t: 'η', c: 'amber', note: 'η (eta) is the learning rate: how big each step is' }, { t: ' · ' }, { t: '∂L/∂w', c: 'pink', note: 'The gradient: the slope of the loss with respect to w' }], below: 'Move against the gradient — downhill', chapter: 'Update rule', say: 'The update rule is short. The new weight equals the old weight, minus the learning rate times the gradient. The minus sign means we always move downhill.' },
      { kit: 'loss-curve', lr: .05, head: 'Learning rate too small', verdict: 'After 14 steps it has only reached w ≈ 2.6 — painfully slow.', chapter: 'Too small', say: 'With a learning rate that is too small, every step is tiny. After fourteen steps, the weight has only crawled to about 2.6, far from the minimum at 5.5. Training would take forever.' },
      { kit: 'loss-curve', lr: 2.9, head: 'Learning rate too large', verdict: 'Each step overshoots the valley and it bounces from side to side, never settling.', chapter: 'Too large', say: 'With a learning rate that is too large, each step overshoots the valley. The weight bounces from one side to the other and never settles. The loss does not go down.' },
      { kit: 'contour', opts: ['gd', 'momentum', 'adam'], head: 'Optimisers on a narrow valley', chapter: 'Optimisers', say: 'Real models have many weights, so the loss is a surface. On this narrow valley, plain gradient descent zigzags from side to side. Adam adapts its step size for each direction and heads almost straight in. Momentum builds up speed along the valley, and by the end it is closest to the minimum.' },
      { kit: 'bullets', style: 'recap', items: ['Step against the gradient to reduce the loss', 'The learning rate sets the step size', 'Too small: slow. Too large: overshooting', 'Momentum and Adam are popular improvements'], chapter: 'Recap', say: 'To recap. Gradient descent steps against the slope. The learning rate sets the step size, neither too small nor too large. And optimisers like momentum and Adam make the journey faster and smoother.' }
    ],
    takeaways: ['Gradient descent updates w ← w − η·∂L/∂w.', 'A small learning rate is slow; a large one overshoots and may diverge.', 'Steps naturally shrink as the slope flattens near a minimum.', 'Momentum and Adam improve on plain gradient descent in narrow valleys.'],
    quiz: [
      { q: 'What happens if the learning rate is far too large?', a: ['Training is slow but steady', 'Steps overshoot and the loss may never settle', 'Nothing changes'], c: 1, why: 'Large steps jump over the minimum repeatedly.' },
      { q: 'Why do steps get smaller near the minimum?', a: ['The gradient (slope) gets smaller', 'The learning rate is always reduced', 'The data changes'], c: 0, why: 'Step size is learning rate × gradient, and the slope flattens.' },
      { q: 'Which optimiser adapts its step size separately for each direction?', a: ['Adam', 'Plain gradient descent', 'k-means'], c: 0, why: 'Adam scales updates using running estimates of gradient size.' }
    ],
    read: ['gradient-descent-theory', 'sgd-momentum-nesterov', 'adaptive-optimizers-adam-adamw', 'learning-rate-schedules-warmup']
  },
  {
    slug: 'logistic-regression-and-the-perceptron', title: 'Linear Classifiers: Logistic Regression and the Perceptron', track: 'ml', level: 'Beginner', poster: 2,
    summary: 'Draw a line that separates two classes. Watch logistic regression learn a probabilistic boundary and the perceptron nudge its line towards mistakes.',
    scenes: [
      { kit: 'title', title: 'Linear Classifiers', sub: 'Logistic regression and the perceptron', track: 'Machine Learning', chapter: 'Introduction', say: 'Classification means predicting a category: spam or not, pass or fail. The simplest classifiers separate the classes with a straight line.' },
      { kit: 'classify-boundary', model: 'logistic', chapter: 'Logistic regression', say: 'Logistic regression learns a boundary and a probability for every point. The background shading shows how confident it is. Watch the boundary move as training runs. Accuracy climbs from 59 percent to 93 percent, with a few overlapping points still misclassified.' },
      { kit: 'equation', head: 'The sigmoid turns scores into probabilities', parts: [{ t: 'p', c: 'pink', note: 'p is the predicted probability of the positive class' }, { t: ' = ' }, { t: 'σ', c: 'amber', note: 'σ, the sigmoid, squeezes any number into the range 0 to 1' }, { t: '(' }, { t: 'w·x + b', c: 'cyan', note: 'A linear score, just like linear regression' }, { t: ')' }], below: 'σ(z) = 1 / (1 + e^(−z))  ·  predict the class when p > 0.5', chapter: 'The sigmoid', say: 'The model computes a linear score, like linear regression, and passes it through the sigmoid, which squeezes any number into a probability between zero and one. Above one half, we predict the positive class.' },
      { kit: 'classify-boundary', model: 'perceptron', chapter: 'The perceptron', say: 'The perceptron, from 1958, is even simpler. It looks at a training point. If the point is on the wrong side, it nudges the line towards it. If it is correct, it does nothing. Repeat, and the line settles into a good position.' },
      { kit: 'compare', head: 'Logistic regression vs perceptron', left: { title: 'Logistic regression', items: ['Outputs probabilities', 'Smooth training with gradient descent', 'Widely used baseline today'], color: 'cyan' }, right: { title: 'Perceptron', items: ['Outputs only a class', 'Updates only on mistakes', 'The ancestor of neural networks'], color: 'pink' }, chapter: 'Comparison', say: 'Logistic regression gives probabilities and trains smoothly. The perceptron only outputs a class and only learns from mistakes. But it is historically important: it is the ancestor of every neural network.' },
      { kit: 'bullets', style: 'recap', items: ['A linear classifier separates classes with a line', 'Logistic regression: sigmoid of a linear score → probability', 'Perceptron: move the line towards misclassified points', 'Neither can separate classes that need a curved boundary'], chapter: 'Recap', say: 'To recap. Linear classifiers draw a straight boundary. Logistic regression outputs probabilities. The perceptron learns from mistakes. And neither can handle problems that need a curved boundary, which is where more powerful models come in.' }
    ],
    takeaways: ['Linear classifiers separate classes with a straight line (or plane).', 'Logistic regression applies the sigmoid to a linear score to get a probability.', 'The perceptron updates only when it misclassifies a point.', 'In the animation both reach 41 of 44 points correct (93%).'],
    quiz: [
      { q: 'What does the sigmoid function do?', a: ['Squeezes any number into the range 0–1', 'Sorts the data', 'Adds noise'], c: 0, why: 'Sigmoid outputs can be read as probabilities.' },
      { q: 'When does the perceptron change its line?', a: ['After every point', 'Only when a point is misclassified', 'Never'], c: 1, why: 'It learns only from mistakes.' },
      { q: 'What is a limitation of both models?', a: ['They can only draw straight boundaries', 'They cannot be trained', 'They need images'], c: 0, why: 'Linear models cannot represent curved boundaries without extra features.' }
    ],
    read: ['logistic-regression-explained', 'the-perceptron', 'softmax-regression-multiclass']
  },
  {
    slug: 'k-nearest-neighbours', title: 'k-Nearest Neighbours: Learning by Similarity', track: 'ml', level: 'Beginner', poster: 1,
    summary: 'Classify a new point by asking its closest neighbours to vote. Simple, intuitive and a great first classifier.',
    scenes: [
      { kit: 'title', title: 'k-Nearest Neighbours', sub: 'Tell me who your neighbours are…', track: 'Machine Learning', chapter: 'Introduction', say: 'If you want to guess whether you will like a film, you might ask friends with similar taste. The k nearest neighbours algorithm works exactly like that.' },
      { kit: 'knn', k: 5, chapter: 'How k-NN classifies', say: 'Here are labelled pink and blue points. A new point arrives with no label. We measure its distance to every example, find the five nearest, and let them vote. Three are blue and two are pink, so the new point is classified as blue.' },
      { kit: 'knn', k: 3, head: 'k-nearest neighbours (k = 3)', chapter: 'Changing k', say: 'With k equals three, the vote is two blue to one pink, still blue. Small k is sensitive to noisy points. Large k is smoother but can blur real boundaries. We choose k by testing on validation data, and an odd k avoids ties between two classes.' },
      { kit: 'bullets', head: 'Things to know', items: ['No training phase — it simply remembers all the examples', 'Prediction is slow on big datasets — it compares with every point', 'Scale your features — otherwise large numbers dominate distance', 'Works for regression too — average the neighbours’ values'], chapter: 'Practical tips', say: 'k nearest neighbours has no training step: it just stores the data. That makes prediction slow on big datasets. Always scale your features, or large numbers like income will dominate the distance. And it works for regression too, by averaging neighbours.' },
      { kit: 'bullets', style: 'recap', items: ['Classify by majority vote of the k closest examples', 'Choose k with validation data; odd k avoids ties', 'Normalise features so distances are fair', 'Simple and explainable, slow on large data'], chapter: 'Recap', say: 'To recap. Find the k closest examples and take a vote. Choose k carefully, normalise your features, and remember it is simple and explainable but slow on large data.' }
    ],
    takeaways: ['k-NN predicts by majority vote among the k most similar examples.', 'In the animation, k = 5 gives 3 blue vs 2 pink → blue.', 'Feature scaling matters because distances drive everything.', 'There is no training phase, but predictions can be slow.'],
    quiz: [
      { q: 'With k = 5, three neighbours are blue and two are pink. The prediction is…', a: ['Pink', 'Blue', 'A tie'], c: 1, why: 'The majority of the five neighbours are blue.' },
      { q: 'Why normalise features for k-NN?', a: ['So one large-scale feature does not dominate the distance', 'To make training faster', 'To remove labels'], c: 0, why: 'Distance treats all features equally only if their scales are comparable.' },
      { q: 'What is a downside of k-NN on very large datasets?', a: ['Predictions are slow because it compares with many points', 'It cannot classify', 'It needs a GPU'], c: 0, why: 'Each prediction needs distances to the stored examples.' }
    ],
    read: ['k-nearest-neighbors', 'feature-scaling-normalization']
  },
  {
    slug: 'decision-trees-and-random-forests', title: 'Decision Trees and Random Forests', track: 'ml', level: 'Beginner', poster: 1,
    summary: 'A tree learns yes/no questions that carve the data into pure regions. A forest of trees votes for more robust predictions.',
    scenes: [
      { kit: 'title', title: 'Decision Trees & Random Forests', sub: 'Learning to ask the right questions', track: 'Machine Learning', chapter: 'Introduction', say: 'A doctor diagnoses by asking questions. A decision tree learns its own series of yes or no questions from data.' },
      { kit: 'tree-split', chapter: 'Growing a tree', say: 'Before any split, predicting pink for everything is right 60 percent of the time. The first question, is feature one below 5.5, raises accuracy to 77 percent. A second split makes it 87 percent, and a third makes every region pure: 100 percent on this training data.' },
      { kit: 'bullets', head: 'How the tree picks questions', items: ['Try many possible splits for every feature', 'Measure how pure the resulting groups are — Gini impurity or entropy', 'Keep the split that makes groups purest', 'Repeat on each branch until groups are pure or small'], chapter: 'Choosing splits', say: 'At each step, the tree tries many possible questions and measures how pure the resulting groups would be, using Gini impurity or entropy. It keeps the best question and repeats on each branch.' },
      { kit: 'compare', head: 'The overfitting trap', left: { title: 'Deep tree', items: ['Memorises every training point', '100% on training data', 'Often worse on new data'], color: 'red' }, right: { title: 'Controlled tree', items: ['Limit maximum depth', 'Require enough examples per leaf', 'Prune branches that do not help'], color: 'green' }, chapter: 'Overfitting', say: 'A tree grown too deep memorises noise. It scores perfectly on training data and badly on new data. We control it by limiting depth, requiring enough examples per leaf, or pruning.' },
      { kit: 'forest', chapter: 'Random forests', say: 'A random forest trains many trees, each on a random sample of the data and features. Each tree votes. Here four trees say cat and one says dog, so the forest predicts cat. Averaging many different trees makes predictions far more stable.' },
      { kit: 'bullets', style: 'recap', items: ['Trees learn readable yes/no questions', 'Splits are chosen to make groups pure', 'Deep trees overfit — limit or prune them', 'Random forests average many trees for robustness'], chapter: 'Recap', say: 'To recap. Decision trees learn readable questions. Splits aim for purity. Deep trees overfit. And random forests combine many trees into a strong, stable model.' }
    ],
    takeaways: ['Decision trees split data with yes/no questions chosen to maximise purity.', 'In the animation, accuracy rises 60% → 77% → 87% → 100% with three splits.', 'Deep trees overfit; limit depth or prune.', 'Random forests train many randomised trees and let them vote.'],
    quiz: [
      { q: 'How does a tree choose each question?', a: ['Randomly', 'The split that makes the resulting groups purest', 'Alphabetically'], c: 1, why: 'Splits are scored with impurity measures such as Gini or entropy.' },
      { q: 'Why can a very deep tree be a problem?', a: ['It can memorise noise and generalise poorly', 'It is always too slow to train', 'It cannot make predictions'], c: 0, why: 'Deep trees overfit the training data.' },
      { q: 'A random forest makes its final prediction by…', a: ['Using only the deepest tree', 'Majority vote or averaging across trees', 'Asking the user'], c: 1, why: 'Many trees vote to produce a robust prediction.' }
    ],
    read: ['decision-trees', 'random-forests', 'bagging-and-bootstrap', 'gradient-boosting-machines']
  },
  {
    slug: 'support-vector-machines', title: 'Support Vector Machines and the Kernel Trick', track: 'ml', level: 'Intermediate', poster: 2,
    summary: 'Of all the lines that separate two classes, pick the widest street. Then lift the data into a new dimension to separate what a line cannot.',
    scenes: [
      { kit: 'title', title: 'Support Vector Machines', sub: 'The widest street between two classes', track: 'Machine Learning', chapter: 'Introduction', say: 'Support vector machines were among the most successful classifiers before deep learning. Their idea is elegant: find the widest possible street between two classes.' },
      { kit: 'svm', chapter: 'Maximum margin', say: 'Many different lines separate the pink and blue points. Which is best? An SVM chooses the line with the widest margin, the empty street between the classes. The points touching the edges of the street are the support vectors. Only they decide where the boundary goes.' },
      { kit: 'bullets', head: 'Why a wide margin helps', items: ['More room for error on new, slightly different points', 'Only the support vectors matter — other points can move freely', 'A “soft margin” allows a few mistakes when data overlaps', 'The parameter C balances margin width against mistakes'], chapter: 'Why margins matter', say: 'A wide margin leaves more room for new points that are a little different. Only the support vectors matter. When classes overlap, a soft margin allows a few mistakes, and the parameter C balances width against errors.' },
      { kit: 'svm', mode: 'kernel', chapter: 'The kernel trick', say: 'What if no straight line works? Here the blue points sit on both sides of the pink ones. No single threshold separates them. But add a new feature, x squared, and the blue points lift up. Now a straight line separates them easily. That is the idea behind the kernel trick.' },
      { kit: 'bullets', head: 'Popular kernels', items: ['Linear — a straight boundary', 'Polynomial — curved boundaries of a chosen degree', 'RBF (Gaussian) — flexible, smooth, “bubble-shaped” regions', 'The trick: compute similarities without building the new features explicitly'], chapter: 'Kernels', say: 'Common kernels include linear, polynomial and the radial basis function. The clever part is that kernels compute similarities in the higher-dimensional space without ever building those features explicitly.' },
      { kit: 'bullets', style: 'recap', items: ['SVMs choose the maximum-margin boundary', 'Support vectors are the points on the margin', 'Soft margins handle overlapping classes', 'Kernels allow curved boundaries'], chapter: 'Recap', say: 'To recap. SVMs pick the widest street. Support vectors define it. Soft margins tolerate overlap. And kernels unlock curved boundaries.' }
    ],
    takeaways: ['An SVM chooses the separating boundary with the largest margin.', 'Support vectors are the training points that lie on the margin.', 'Soft margins (parameter C) allow some mistakes when classes overlap.', 'Kernels map data to higher dimensions so a linear boundary can separate it.'],
    quiz: [
      { q: 'Which points determine the SVM boundary?', a: ['All points equally', 'The support vectors on the margin', 'The points furthest away'], c: 1, why: 'Only support vectors affect the maximum-margin solution.' },
      { q: 'In the kernel example, which new feature made the data separable?', a: ['x²', 'x + 1', 'The point’s colour'], c: 0, why: 'Lifting points by x² separated the outer blue points from the inner pink points.' },
      { q: 'What does a soft margin allow?', a: ['A few misclassified points when classes overlap', 'Infinite margin', 'Training without data'], c: 0, why: 'Soft margins trade a little error for a wider, more robust margin.' }
    ],
    read: ['support-vector-machines', 'kernel-methods-kernel-trick']
  },
  {
    slug: 'k-means-clustering', title: 'k-Means Clustering, Step by Step', track: 'ml', level: 'Beginner', poster: 1,
    summary: 'Unsupervised learning in action: assign points to the nearest centroid, move each centroid to its points’ average, repeat.',
    scenes: [
      { kit: 'title', title: 'k-Means Clustering', sub: 'Finding groups without labels', track: 'Machine Learning', chapter: 'Introduction', say: 'You have lots of data and no labels. Are there natural groups hiding in it? k means is the most popular way to find out.' },
      { kit: 'kmeans', chapter: 'Watching k-means', say: 'We ask for three clusters and drop three centroids, the crosses, at random positions. Step one: every point joins its nearest centroid. Step two: every centroid moves to the average of its points. Repeat. The within-cluster distance on the right drops every round, until the centroids stop moving.' },
      { kit: 'pipeline', head: 'The algorithm', steps: ['Choose k', 'Place centroids', 'Assign', 'Update', 'Repeat'], desc: ['Decide how many clusters you want.', 'Start with k centroids, randomly or with k-means++.', 'Each point joins the cluster of its nearest centroid.', 'Each centroid moves to the mean of its assigned points.', 'Stop when assignments no longer change.'], chapter: 'The algorithm', say: 'Choose k. Place the centroids. Assign every point to its nearest centroid. Move each centroid to the mean of its points. Repeat until nothing changes. That is the whole algorithm.' },
      { kit: 'bullets', head: 'Choosing k and avoiding pitfalls', items: ['Elbow method — plot error against k and look for the bend', 'Silhouette score — how well points fit their own cluster', 'Run several times — results depend on the starting centroids', 'Scale features and expect round, similar-sized clusters'], chapter: 'Pitfalls', say: 'You must choose k yourself. The elbow method and silhouette score help. Run it several times, because the start matters. Scale your features. And remember, k means assumes round clusters of similar size.' },
      { kit: 'bullets', style: 'recap', items: ['Unsupervised: no labels needed', 'Alternate assign and update steps', 'Error falls every round until convergence', 'Used for segmentation, compression and exploration'], chapter: 'Recap', say: 'To recap. k means needs no labels. It alternates between assigning points and updating centroids until it converges. It is used for customer segments, image compression and exploring data.' }
    ],
    takeaways: ['k-means alternates between assigning points and moving centroids.', 'The within-cluster distance never increases from one round to the next.', 'You choose k — the elbow method and silhouette score help.', 'Results depend on initial centroids and feature scaling.'],
    quiz: [
      { q: 'In the update step, each centroid moves to…', a: ['The mean of its assigned points', 'A random new place', 'The furthest point'], c: 0, why: 'Centroids become the average of their cluster members.' },
      { q: 'Does k-means need labelled data?', a: ['Yes', 'No — it is unsupervised', 'Only for the first cluster'], c: 1, why: 'It groups unlabelled data.' },
      { q: 'Why run k-means several times?', a: ['Different starting centroids can give different results', 'It is required by law', 'To increase k automatically'], c: 0, why: 'Initialisation affects which solution it converges to.' }
    ],
    read: ['k-means-clustering', 'hierarchical-clustering', 'dbscan-density-clustering', 'gaussian-mixture-models-em']
  },
  {
    slug: 'principal-component-analysis', title: 'Principal Component Analysis (PCA)', track: 'ml', level: 'Intermediate', poster: 1,
    summary: 'Find the direction in which data varies most, then project onto it. Watch two dimensions become one while keeping 93.5% of the variance.',
    scenes: [
      { kit: 'title', title: 'Principal Component Analysis', sub: 'Keeping what matters, dropping dimensions', track: 'Machine Learning', chapter: 'Introduction', say: 'Real datasets can have hundreds of features. Principal component analysis, or PCA, finds a smaller set of directions that capture most of the information.' },
      { kit: 'pca', chapter: 'Finding the first component', say: 'Here is a cloud of points that is stretched in one direction. We rotate a line and measure how much the data spreads along it. The spread, or variance, is highest along one direction. That is the first principal component. Projecting onto it turns two dimensions into one while keeping 93.5 percent of the variance.' },
      { kit: 'pipeline', head: 'How PCA works', steps: ['Centre the data', 'Covariance', 'Eigenvectors', 'Project'], desc: ['Subtract the mean of each feature.', 'Measure how features vary together.', 'The eigenvectors of the covariance matrix are the principal directions, ordered by variance.', 'Keep the top few directions and project the data onto them.'], chapter: 'The recipe', say: 'The recipe: centre the data, compute the covariance matrix, and find its eigenvectors. They point along the directions of greatest variance. Keep the top few and project the data onto them.' },
      { kit: 'bullets', head: 'What PCA is used for', items: ['Visualisation — squash many features into 2-D plots', 'Compression — store fewer numbers per example', 'Noise reduction — small components are often noise', 'Faster models — fewer inputs, less overfitting'], chapter: 'Uses', say: 'PCA is used to visualise high-dimensional data in two dimensions, compress data, remove noise and speed up other models. But the new components are mixtures of features, so they can be harder to interpret.' },
      { kit: 'bullets', style: 'recap', items: ['Principal components are directions of maximum variance', 'They come from the covariance matrix’s eigenvectors', 'Project onto the top components to reduce dimensions', 'Check how much variance you keep'], chapter: 'Recap', say: 'To recap. Principal components point where the data varies most. They come from eigenvectors of the covariance matrix. Projecting onto the top few reduces dimensions, and you should always check how much variance you keep.' }
    ],
    takeaways: ['PCA finds orthogonal directions of maximum variance.', 'They are the eigenvectors of the data’s covariance matrix.', 'In the animation, one component keeps 93.5% of the variance.', 'PCA helps with visualisation, compression and noise reduction.'],
    quiz: [
      { q: 'The first principal component is the direction of…', a: ['Maximum variance', 'Minimum variance', 'The first feature in the table'], c: 0, why: 'PC1 captures the largest spread in the data.' },
      { q: 'What should you do before PCA?', a: ['Centre (and usually scale) the data', 'Delete half the rows', 'Label every example'], c: 0, why: 'PCA works on centred data; scaling prevents one feature dominating.' },
      { q: 'What is a downside of PCA?', a: ['Components mix features, so they can be hard to interpret', 'It always increases dimensions', 'It needs labels'], c: 0, why: 'Each component is a combination of original features.' }
    ],
    read: ['principal-component-analysis', 'eigenvalues-and-eigenvectors', 'tsne-and-umap', 'curse-of-dimensionality']
  },
  {
    slug: 'overfitting-and-bias-variance', title: 'Overfitting, Underfitting and Bias–Variance', track: 'ml', level: 'Beginner', poster: 1,
    summary: 'Too simple, just right, too complex: see three models on the same data and why validation error — not training error — tells the truth.',
    scenes: [
      { kit: 'title', title: 'Overfitting & Underfitting', sub: 'The central challenge of machine learning', track: 'Machine Learning', chapter: 'Introduction', say: 'The goal of machine learning is not to fit the training data. It is to do well on new data. Two opposite failures get in the way.' },
      { kit: 'fit-compare', chapter: 'Three models', say: 'The same data, three models. A straight line underfits: training error 1.53. A gentle curve fits well: 0.25. A degree nine polynomial passes through every point: training error zero. But on new validation points, the curve wins with 1.26, while the overfit model is worst at 2.30.' },
      { kit: 'darts', chapter: 'Bias and variance', say: 'Think of darts. High bias means aiming off-centre, like a model that is too simple. High variance means throws scattered everywhere, like a model that changes wildly with small changes in data. We want low bias and low variance.' },
      { kit: 'learning-curve', mode: 'overfit', chapter: 'Learning curves', say: 'Learning curves reveal overfitting during training. Training loss keeps falling, but validation loss stops improving and starts rising. The widening gap means the model is memorising. Early stopping keeps the model from the best point.' },
      { kit: 'compare', head: 'How to fix it', left: { title: 'Underfitting', items: ['Use a more flexible model', 'Add better features', 'Train longer'], color: 'amber' }, right: { title: 'Overfitting', items: ['Get more data', 'Simplify or regularise the model', 'Early stopping, dropout, augmentation'], color: 'red' }, chapter: 'Fixes', say: 'To fix underfitting, use a more flexible model, better features, or train longer. To fix overfitting, get more data, simplify or regularise the model, and use tricks like early stopping, dropout and data augmentation.' },
      { kit: 'bullets', style: 'recap', items: ['Underfit — too simple, bad everywhere', 'Overfit — perfect on training, poor on new data', 'Judge models by validation error', 'Balance bias against variance'], chapter: 'Recap', say: 'To recap. Underfitting is too simple. Overfitting memorises. Always judge by validation error, and aim for the balance between bias and variance.' }
    ],
    takeaways: ['Underfitting: high error on training and validation data.', 'Overfitting: very low training error but high validation error.', 'In the animation: validation error 1.87 (line), 1.26 (curve), 2.30 (degree-9 polynomial).', 'More data, regularisation and early stopping reduce overfitting.'],
    quiz: [
      { q: 'A model has 0 training error but high validation error. It is…', a: ['Underfitting', 'Overfitting', 'Perfect'], c: 1, why: 'It has memorised the training data.' },
      { q: 'In the darts analogy, high variance looks like…', a: ['Throws scattered widely', 'Throws tightly grouped but off-centre', 'No throws at all'], c: 0, why: 'Variance is sensitivity: results scatter.' },
      { q: 'Which helps against overfitting?', a: ['More training data', 'Removing the validation set', 'Training forever'], c: 0, why: 'More data makes memorisation harder and patterns clearer.' }
    ],
    read: ['bias-variance-tradeoff', 'overfitting-underfitting-learning-curves', 'regularization-ridge-lasso-elastic-net']
  },
  {
    slug: 'train-test-split-and-cross-validation', title: 'Train/Test Splits and Cross-Validation', track: 'ml', level: 'Beginner', poster: 1,
    summary: 'Why data is split into training, validation and test sets — and how k-fold cross-validation gives a more reliable score.',
    scenes: [
      { kit: 'title', title: 'Train, Validation, Test', sub: 'How not to fool yourself', track: 'Machine Learning', chapter: 'Introduction', say: 'If students see the exam questions in advance, their scores mean nothing. Models are the same. To know how good a model really is, we must test it on data it has never seen.' },
      { kit: 'split-folds', chapter: 'Splitting the data', say: 'First shuffle the data so every part is representative. Then split it. Around seventy percent for training, fifteen percent for validation to tune settings, and fifteen percent for a final test that we look at only once.' },
      { kit: 'bullets', head: 'The role of each set', items: ['Training — the model learns its parameters here', 'Validation — choose settings and compare models', 'Test — one final, honest estimate', 'Golden rule — never tune on the test set'], chapter: 'Roles', say: 'The model learns from the training set. We use the validation set to choose settings and compare models. The test set gives one final honest estimate. If you keep tuning on the test set, it stops being honest.' },
      { kit: 'split-folds', mode: 'kfold', k: 5, scores: [.84, .87, .82, .86, .85], sub: 'example scores', chapter: 'Cross-validation', say: 'With small datasets, one split can be lucky or unlucky. Five-fold cross-validation splits the data into five parts. Each round trains on four and validates on the fifth, until every part has been the validation set once. Here the five example scores average 0.848.' },
      { kit: 'bullets', head: 'Watch out for leakage', items: ['Duplicates in both training and test sets', 'Scaling or imputing using the whole dataset before splitting', 'Features that contain the answer, like “refund issued”', 'Time series — always test on the future, not a random mix'], chapter: 'Data leakage', say: 'Beware of data leakage: when information from the test data sneaks into training. Duplicates, preprocessing before splitting, features that secretly contain the answer, or shuffling time series. Leakage makes models look brilliant, then fail in reality.' },
      { kit: 'bullets', style: 'recap', items: ['Shuffle, then split into train / validation / test', 'Tune on validation; test only once', 'k-fold cross-validation averages several splits', 'Guard against leakage'], chapter: 'Recap', say: 'To recap. Shuffle and split. Tune on validation and test only once. Use cross-validation for small data. And guard carefully against leakage.' }
    ],
    takeaways: ['Split data into training, validation and test sets (e.g. 70/15/15).', 'Tune on validation data; use the test set only once at the end.', 'k-fold cross-validation rotates the validation fold and averages the scores.', 'Data leakage makes results look better than they really are.'],
    quiz: [
      { q: 'Which set should you use to choose hyperparameters?', a: ['Training set', 'Validation set', 'Test set'], c: 1, why: 'Tuning on validation keeps the test set honest.' },
      { q: 'In 5-fold cross-validation, how many times is the model trained?', a: ['Once', 'Five times', 'Fifty times'], c: 1, why: 'Each of the five folds takes a turn as validation data.' },
      { q: 'Which is an example of data leakage?', a: ['Normalising the full dataset before splitting it', 'Shuffling before splitting', 'Using a validation set'], c: 0, why: 'Test statistics influence the training data when preprocessing happens before the split.' }
    ],
    read: ['train-validation-test-cross-validation', 'hyperparameter-tuning']
  },
  {
    slug: 'classification-metrics', title: 'Confusion Matrix, Precision, Recall and ROC', track: 'ml', level: 'Intermediate', poster: 1,
    summary: 'Accuracy alone can mislead. Build a confusion matrix, compute precision, recall and F1, then move the threshold and trace an ROC curve.',
    scenes: [
      { kit: 'title', title: 'Classification Metrics', sub: 'Accuracy is not the whole story', track: 'Machine Learning', chapter: 'Introduction', say: 'A spam filter is 86 percent accurate. Is it good? That depends on how it is wrong. Let us open up the confusion matrix.' },
      { kit: 'confusion', chapter: 'The confusion matrix', say: 'We test the filter on 100 emails. 42 spam emails are caught: true positives. 8 real emails are wrongly marked as spam: false positives. 6 spam emails slip through: false negatives. And 44 real emails are correctly left alone. From these four numbers we get accuracy 86 percent, precision 84 percent, recall 87.5 percent and F1 85.7 percent.' },
      { kit: 'bullets', head: 'What each metric means', items: ['Precision — when it says spam, how often is it right? 42 / 50', 'Recall — of all the spam, how much did it catch? 42 / 48', 'F1 — one number that balances precision and recall', 'Accuracy — misleading when one class is rare'], chapter: 'Precision and recall', say: 'Precision asks: when the model says spam, how often is it right? Recall asks: of all the spam, how much did it catch? F1 balances the two. And accuracy can be misleading when one class is rare.' },
      { kit: 'confusion', mode: 'threshold', chapter: 'Moving the threshold', say: 'The model gives each email a score. The threshold decides which scores count as spam. Move it left and recall rises, but precision falls. Move it right and precision rises, but recall falls. Tracing every threshold draws the ROC curve. The area under it, the AUC, is about 0.94 here.' },
      { kit: 'compare', head: 'Which metric matters?', left: { title: 'Favour precision', items: ['Spam filters — hiding real email is costly', 'Recommendations — bad suggestions annoy users'], color: 'green' }, right: { title: 'Favour recall', items: ['Disease screening — missing a patient is costly', 'Fraud alerts — missed fraud is expensive'], color: 'violet' }, chapter: 'Choosing', say: 'Which metric matters depends on the cost of mistakes. A spam filter should favour precision, so real email is not hidden. Disease screening should favour recall, so sick patients are not missed.' },
      { kit: 'bullets', style: 'recap', items: ['TP, FP, FN, TN — the four outcomes', 'Precision = TP / (TP + FP); recall = TP / (TP + FN)', 'The threshold trades precision against recall', 'ROC and AUC summarise all thresholds'], chapter: 'Recap', say: 'To recap. Four outcomes make the confusion matrix. Precision and recall answer different questions. The threshold trades one for the other. And the ROC curve and AUC summarise performance across all thresholds.' }
    ],
    takeaways: ['The confusion matrix counts true/false positives and negatives.', 'In the example: accuracy 86%, precision 84%, recall 87.5%, F1 85.7%.', 'Changing the threshold trades precision against recall.', 'The ROC curve and AUC summarise performance across thresholds (AUC ≈ 0.94 in the demo).'],
    quiz: [
      { q: 'Precision is…', a: ['TP / (TP + FP)', 'TP / (TP + FN)', '(TP + TN) / all'], c: 0, why: 'Of everything predicted positive, how much is truly positive.' },
      { q: 'Lowering the threshold usually…', a: ['Raises recall and lowers precision', 'Raises precision and lowers recall', 'Changes nothing'], c: 0, why: 'More items are flagged, catching more positives but also more false alarms.' },
      { q: 'For disease screening, which metric is usually most important?', a: ['Recall', 'Precision', 'Training time'], c: 0, why: 'Missing sick patients (false negatives) is very costly.' }
    ],
    read: ['classification-metrics', 'roc-auc-and-precision-recall-curves', 'imbalanced-data-techniques']
  }
];
