/* AI in Motion — Natural Language Processing track. © Janin A Apurba, CSE, AUST */
module.exports = [
  {
    slug: 'what-is-nlp', title: 'What Is Natural Language Processing?', track: 'nlp', level: 'Beginner',
    summary: 'How computers read, understand and generate human language — the tasks, the pipeline and how the field moved from rules to neural networks.',
    scenes: [
      { kit: 'title', title: 'What Is NLP?', sub: 'Teaching computers human language', track: 'Natural Language Processing', chapter: 'Introduction', say: 'Every search you type, every translation and every chatbot reply relies on natural language processing: the science of getting computers to work with human language.' },
      { kit: 'bullets', head: 'What NLP systems do', items: ['Classify — spam or not, positive or negative review', 'Extract — names, places, dates and facts from text', 'Translate — from one language to another', 'Answer — find and explain answers to questions', 'Generate — summaries, emails, code and conversation'], chapter: 'NLP tasks', say: 'NLP covers many tasks. Classifying text, extracting names and facts, translating between languages, answering questions, and generating new text, from summaries to conversations.' },
      { kit: 'pipeline', head: 'From text to answers', steps: ['Raw text', 'Tokens', 'Numbers (vectors)', 'Model', 'Output'], desc: ['Human language, full of ambiguity, slang and typos.', 'Split into words or sub-words.', 'Each token becomes a vector the model can compute with.', 'A classifier, tagger or language model processes the vectors.', 'A label, a translation, an answer or new text.'], chapter: 'The pipeline', say: 'Almost every NLP system follows the same path. Raw text is split into tokens. Tokens become vectors of numbers. A model processes those vectors, and produces an output: a label, a translation, an answer or new text.' },
      { kit: 'compare', head: 'Why language is hard', left: { title: 'Ambiguity', items: ['“I saw her duck” — bird or movement?', '“Bank” — river or money?', 'Meaning depends on context'], color: 'amber' }, right: { title: 'Variety', items: ['Slang, typos and emojis', 'Thousands of languages and dialects', 'Sarcasm: “Great, another Monday.”'], color: 'pink' }, chapter: 'Why it is hard', say: 'Language is hard for computers. Words are ambiguous: is a bank beside a river or full of money? And people use slang, typos, emojis, sarcasm and thousands of languages. Context is everything.' },
      { kit: 'timeline', head: 'Three eras of NLP', events: [['1950s–80s', 'Hand-written rules and grammars'], ['1990s–2000s', 'Statistics: n-grams, TF-IDF'], ['2013', 'Word embeddings (word2vec)'], ['2017', 'The Transformer'], ['2018+', 'Pre-trained models: BERT, GPT']], chapter: 'Three eras', say: 'NLP moved through three eras. First hand-written rules. Then statistics, counting words and word pairs. Then neural networks: word embeddings in 2013, the Transformer in 2017, and huge pre-trained models like BERT and GPT.' },
      { kit: 'bullets', style: 'recap', items: ['NLP lets computers classify, extract, translate and generate text', 'Pipeline: text → tokens → vectors → model → output', 'Ambiguity and variety make language hard', 'Rules → statistics → neural networks'], chapter: 'Recap', say: 'To recap. NLP classifies, extracts, translates and generates. Text becomes tokens and vectors before any model sees it. Ambiguity makes it hard. And the field moved from rules to statistics to neural networks.' }
    ],
    takeaways: ['NLP covers classification, extraction, translation, question answering and generation.', 'Text is turned into tokens and then vectors before a model can process it.', 'Ambiguity, context and variety make language difficult for computers.', 'The field moved from rules to statistics to neural networks and pre-trained Transformers.'],
    quiz: [
      { q: 'What must happen before a neural model can process text?', a: ['Text is converted into tokens and then numbers', 'Text is printed', 'Nothing — models read letters directly'], c: 0, why: 'Models compute with vectors, so text is tokenised and embedded.' },
      { q: '“I saw her duck” is hard for computers because of…', a: ['Ambiguity', 'Spelling mistakes', 'Its length'], c: 0, why: '“Duck” could be an animal or an action.' },
      { q: 'Which architecture (2017) underpins BERT and GPT?', a: ['The Transformer', 'The perceptron', 'k-means'], c: 0, why: 'Both are built from Transformer blocks.' }
    ],
    read: ['introduction-to-nlp', 'text-preprocessing-tokenization']
  },
  {
    slug: 'tokenization-and-subwords', title: 'Tokenization and Byte-Pair Encoding', track: 'nlp', level: 'Beginner',
    summary: 'Words, characters or sub-words? See three ways to tokenise text, then watch byte-pair encoding learn sub-words from a tiny corpus.',
    scenes: [
      { kit: 'title', title: 'Tokenization', sub: 'The first step of every language model', track: 'Natural Language Processing', chapter: 'Introduction', say: 'Before a model can read a sentence, the sentence must be cut into pieces called tokens. How we cut it matters more than you might think.' },
      { kit: 'tokenize', chapter: 'Three strategies', say: 'Word-level tokenization gives short sequences, but needs a huge vocabulary and cannot handle new words. Character-level needs only a tiny vocabulary, but sequences become very long. Sub-word tokenization sits in between: common words stay whole, rare words split into meaningful pieces.' },
      { kit: 'bpe', chapter: 'Byte-pair encoding', say: 'Byte-pair encoding learns sub-words from data. Start with single characters. Count every adjacent pair, weighted by word frequency, and merge the most frequent one. Here e and s appear together nine times, so they merge first, then e s with t, then est with the end of a word. Repeat, and useful pieces like est and low emerge.' },
      { kit: 'bullets', head: 'Why sub-words won', items: ['No unknown words — anything can be spelled with pieces', 'Shared pieces: “play”, “playing”, “player”', 'A manageable vocabulary, often 30,000 to 100,000+ tokens', 'Used by GPT (BPE), BERT (WordPiece) and many others'], chapter: 'Why sub-words', say: 'Sub-words mean no word is ever unknown, because anything can be spelled from pieces. Related words share pieces, and the vocabulary stays manageable. GPT models use byte-pair encoding, and BERT uses a close cousin called WordPiece.' },
      { kit: 'bullets', head: 'Tokens in practice', items: ['In English, one token is roughly ¾ of a word on average', 'Many other languages need more tokens for the same meaning', 'Context limits and API prices are counted in tokens', 'Tokenization explains some odd LLM mistakes, like counting letters'], chapter: 'In practice', say: 'In English, a token is roughly three quarters of a word on average. Many other languages need more tokens for the same meaning. Model limits and prices are counted in tokens, and tokenization even explains why language models struggle to count letters in a word.' },
      { kit: 'bullets', style: 'recap', items: ['Tokens are the units a model reads', 'Word, character and sub-word tokenization', 'BPE merges the most frequent pair, again and again', 'Sub-words handle any word with a compact vocabulary'], chapter: 'Recap', say: 'To recap. Tokens are what models read. Sub-word tokenization is the modern standard, and byte-pair encoding builds it by repeatedly merging the most frequent pair of symbols.' }
    ],
    takeaways: ['Tokenization splits text into units (tokens) that a model processes.', 'Sub-word tokenization balances vocabulary size and sequence length.', 'BPE repeatedly merges the most frequent adjacent pair; in the demo e+s (9 times) merges first.', 'In English, a token is about ¾ of a word on average.'],
    quiz: [
      { q: 'What does each BPE step do?', a: ['Merges the most frequent adjacent pair of symbols', 'Deletes rare words', 'Sorts the vocabulary'], c: 0, why: 'BPE builds sub-words by merging the most common pair.' },
      { q: 'A key advantage of sub-word tokenization is…', a: ['It can represent any word, even unseen ones', 'It needs no training data', 'It makes sequences longer'], c: 0, why: 'Unknown words can be spelled from known pieces.' },
      { q: 'Why can character-level models be slow?', a: ['Sequences become very long', 'The vocabulary is huge', 'They cannot read spaces'], c: 0, why: 'Every character is a separate token.' }
    ],
    read: ['text-preprocessing-tokenization', 'subword-tokenization-bpe-wordpiece']
  },
  {
    slug: 'bag-of-words-and-tf-idf', title: 'Bag of Words and TF-IDF', track: 'nlp', level: 'Beginner',
    summary: 'The classic way to turn documents into numbers: count words, then weigh them by how rare they are. Computed live on three tiny documents.',
    scenes: [
      { kit: 'title', title: 'Bag of Words & TF-IDF', sub: 'Turning documents into numbers', track: 'Natural Language Processing', chapter: 'Introduction', say: 'Long before neural networks, search engines and spam filters turned documents into numbers by counting words. The idea is simple and still useful today.' },
      { kit: 'bow-tfidf', chapter: 'Count, then weigh', say: 'A bag of words counts how often each word appears in each document. Word order is thrown away. But common words like the dominate the counts. TF-IDF fixes that. Words that appear in every document get an inverse document frequency of zero, so the has no weight. Rare, distinctive words like mat, log and chased get the highest weights.' },
      { kit: 'equation', head: 'The TF-IDF formula', parts: [{ t: 'tf-idf', c: 'green', note: 'How important a word is to one document' }, { t: ' = ' }, { t: 'tf', c: 'cyan', note: 'Term frequency: how often the word appears in this document' }, { t: ' × ' }, { t: 'log(N / df)', c: 'amber', note: 'Inverse document frequency: N documents, df of them contain the word. Rare words score high.' }], below: '“the” is in all 3 documents → log(3/3) = 0', chapter: 'The formula', say: 'TF-IDF multiplies term frequency, how often a word appears in this document, by inverse document frequency, the log of the number of documents divided by how many contain the word. A word found everywhere scores zero.' },
      { kit: 'compare', head: 'Strengths and limits', left: { title: 'Strengths', items: ['Fast and simple', 'Works well for search and spam filtering', 'Easy to explain'], color: 'green' }, right: { title: 'Limits', items: ['Ignores word order: “dog bites man” = “man bites dog”', 'No meaning: “car” and “automobile” are unrelated', 'Huge, sparse vectors'], color: 'red' }, chapter: 'Strengths and limits', say: 'Bag of words is fast, simple and still strong for search and spam filtering. But it ignores word order, so dog bites man equals man bites dog, and it has no idea that car and automobile mean the same thing. Embeddings solve that.' },
      { kit: 'bullets', style: 'recap', items: ['Bag of words: count each word, ignore order', 'TF-IDF: term frequency × inverse document frequency', 'Common words get low weight, distinctive words high', 'Great baseline; no notion of meaning'], chapter: 'Recap', say: 'To recap. Bag of words counts words. TF-IDF weighs them by how distinctive they are. It is a great baseline, but it does not understand meaning.' }
    ],
    takeaways: ['Bag of words represents a document by word counts, ignoring order.', 'TF-IDF = term frequency × log(N / document frequency).', 'Words in every document (like “the”) get zero weight; rare words get high weight.', 'It is a strong, fast baseline but has no notion of meaning or order.'],
    quiz: [
      { q: 'What is the IDF of a word that appears in every document?', a: ['0', '1', 'Infinity'], c: 0, why: 'log(N / N) = log(1) = 0.' },
      { q: 'What information does bag of words throw away?', a: ['Word order', 'Word counts', 'The vocabulary'], c: 0, why: 'Only counts remain.' },
      { q: 'Which words get the highest TF-IDF weight?', a: ['Frequent in this document but rare elsewhere', 'Common in every document', 'Punctuation'], c: 0, why: 'High term frequency times high inverse document frequency.' }
    ],
    read: ['bag-of-words-tf-idf', 'text-classification']
  },
  {
    slug: 'n-gram-language-models', title: 'N-gram Language Models', track: 'nlp', level: 'Beginner',
    summary: 'Predict the next word by counting word pairs. A bigram model built from a tiny corpus — the ancestor of today’s LLMs.',
    scenes: [
      { kit: 'title', title: 'N-gram Language Models', sub: 'Predicting the next word by counting', track: 'Natural Language Processing', chapter: 'Introduction', say: 'A language model predicts the next word. Today that is done by giant neural networks, but the idea started with simple counting.' },
      { kit: 'ngram', chapter: 'A bigram model', say: 'Here is a tiny corpus. A bigram model looks at pairs of words. After the word i, the corpus continues with like twice and drink once, so the probability of like is two thirds. After like, green and black are equally likely. After green, it is always tea.' },
      { kit: 'equation', head: 'Estimating probabilities', parts: [{ t: 'P(wₙ | wₙ₋₁)', c: 'blue', note: 'The probability of the next word given the previous word' }, { t: ' = ' }, { t: 'count(wₙ₋₁ wₙ)', c: 'green', note: 'How often the pair appears' }, { t: ' / ' }, { t: 'count(wₙ₋₁)', c: 'amber', note: 'How often the previous word appears' }], below: 'P(like | i) = 2 / 3', chapter: 'The formula', say: 'The probability of the next word, given the previous one, is the count of the pair divided by the count of the previous word. Like after i: two divided by three.' },
      { kit: 'bullets', head: 'Problems with counting', items: ['Sparsity — most word combinations never appear in the data', 'Zero probability for anything unseen', 'Smoothing (e.g. add-one, Kneser–Ney) gives unseen pairs a little probability', 'Short memory — a trigram only sees two words back'], chapter: 'Limitations', say: 'Counting has problems. Most word combinations never appear, so they get zero probability. Smoothing techniques give unseen pairs a little probability. And n-grams have short memory: a trigram only sees two words back.' },
      { kit: 'compare', head: 'N-grams vs neural language models', left: { title: 'N-gram', items: ['Counts of word sequences', 'Memory of n − 1 words', 'Fast, tiny, interpretable'], color: 'amber' }, right: { title: 'Neural (Transformer) LM', items: ['Learned vectors and attention', 'Context of thousands of tokens', 'Generalises to unseen phrases'], color: 'blue' }, chapter: 'From counts to neural', say: 'Neural language models replace counts with learned vectors, generalise to phrases they have never seen, and use attention to look back across thousands of tokens. But the goal is the same: predict the next word.' },
      { kit: 'bullets', style: 'recap', items: ['A language model predicts the next word', 'Bigram: P(next | previous) from counts', 'Smoothing handles unseen combinations', 'Neural LMs keep the goal, improve the method'], chapter: 'Recap', say: 'To recap. A language model predicts the next word. N-grams do it by counting. Smoothing handles unseen pairs. And modern neural models pursue the same goal with far more context.' }
    ],
    takeaways: ['A language model assigns probabilities to the next word.', 'Bigram: P(wₙ | wₙ₋₁) = count(wₙ₋₁ wₙ) / count(wₙ₋₁); in the demo P(like | i) = 2/3.', 'Unseen combinations get zero probability unless smoothed.', 'Neural language models keep the same objective with much longer context.'],
    quiz: [
      { q: 'In the corpus, “i” is followed by “like” 2 times and “drink” once. What is P(like | i)?', a: ['1/3', '2/3', '1'], c: 1, why: '2 out of 3 occurrences.' },
      { q: 'What problem does smoothing solve?', a: ['Zero probability for unseen word combinations', 'Slow training', 'Long sentences'], c: 0, why: 'It reserves some probability for unseen n-grams.' },
      { q: 'How much context does a trigram model use?', a: ['The previous 2 words', 'The whole document', 'None'], c: 0, why: 'A trigram conditions on n − 1 = 2 previous words.' }
    ],
    read: ['n-gram-language-models', 'nlp-evaluation-metrics']
  },
  {
    slug: 'word2vec-and-word-embeddings', title: 'Word2vec and Word Embeddings', track: 'nlp', level: 'Intermediate',
    summary: 'You shall know a word by the company it keeps. See how skip-gram turns context windows into training pairs — and meaning into vectors.',
    scenes: [
      { kit: 'title', title: 'Word2vec', sub: 'Learning meaning from context', track: 'Natural Language Processing', chapter: 'Introduction', say: 'In 2013, word2vec showed that a simple neural network could learn the meaning of words just by reading lots of text. The key idea: a word is known by the company it keeps.' },
      { kit: 'skipgram', chapter: 'Context windows', say: 'Slide a window across the text. For each centre word, every neighbour within two positions becomes a training pair: quick predicts the, brown and fox. Millions of such pairs teach the network which words appear in similar contexts.' },
      { kit: 'pipeline', head: 'Skip-gram training', steps: ['Centre word', 'Embedding', 'Predict context', 'Update vectors'], desc: ['Take one word from the window.', 'Look up its vector: a few hundred numbers.', 'Score how likely each context word is.', 'Nudge vectors so real context words score higher than random ones (negative sampling).'], chapter: 'How it trains', say: 'For each pair, look up the centre word’s vector, predict the context word, and nudge the vectors so real neighbours score higher than random words. That trick is called negative sampling.' },
      { kit: 'embedding', mode: 'analogy', head: 'The result: meaningful directions', chapter: 'Analogies', say: 'After training, similar words sit close together, and directions carry meaning. The step from man to woman is parallel to the step from king to queen, so king minus man plus woman lands near queen.' },
      { kit: 'compare', head: 'Static vs contextual embeddings', left: { title: 'word2vec / GloVe', items: ['One vector per word', '“bank” has the same vector everywhere', 'Fast and lightweight'], color: 'amber' }, right: { title: 'Contextual (BERT, GPT)', items: ['A different vector in every sentence', '“river bank” ≠ “bank loan”', 'Much richer, but heavier'], color: 'blue' }, chapter: 'Static vs contextual', say: 'Word2vec gives each word a single vector, so bank means the same in river bank and bank loan. Modern models like BERT produce contextual embeddings, a different vector each time, depending on the sentence.' },
      { kit: 'bullets', style: 'recap', items: ['Words in similar contexts get similar vectors', 'Skip-gram: predict neighbours from the centre word', 'Directions capture relationships', 'Contextual models give each occurrence its own vector'], chapter: 'Recap', say: 'To recap. Word2vec learns vectors by predicting neighbours. Similar words end up close together, directions capture relationships, and contextual models took the idea further.' }
    ],
    takeaways: ['Word2vec (2013) learns word vectors by predicting context words.', 'Skip-gram creates (centre, context) pairs from a sliding window.', 'Negative sampling contrasts real context words with random ones.', 'Static embeddings give one vector per word; contextual models give one per occurrence.'],
    quiz: [
      { q: 'With window size 2, which words are context for “brown” in “the quick brown fox jumps”?', a: ['the, quick, fox, jumps', 'only quick', 'every word in the corpus'], c: 0, why: 'Two words on each side.' },
      { q: 'What does negative sampling do?', a: ['Contrasts real context words with random words', 'Deletes negative words', 'Removes stop words'], c: 0, why: 'It makes training efficient by scoring a few random negatives.' },
      { q: 'How do contextual embeddings differ from word2vec?', a: ['The same word gets different vectors in different sentences', 'They have no vectors', 'They only work for numbers'], c: 0, why: 'Context changes the representation.' }
    ],
    read: ['word2vec-word-embeddings', 'glove-fasttext-embeddings', 'embeddings-explained']
  },
  {
    slug: 'sentiment-and-text-classification', title: 'Sentiment Analysis and Text Classification', track: 'nlp', level: 'Beginner',
    summary: 'Is this review positive or negative? See how word evidence adds up, why negation is tricky, and how modern classifiers are built.',
    scenes: [
      { kit: 'title', title: 'Sentiment Analysis', sub: 'Teaching computers to read the mood', track: 'Natural Language Processing', chapter: 'Introduction', say: 'Companies read thousands of reviews and comments every day. Sentiment analysis, a kind of text classification, tells them automatically whether people are happy or not.' },
      { kit: 'sentiment', chapter: 'Adding up evidence', say: 'A simple classifier gives each word a weight. Delicious pushes strongly towards positive. Slow and rude push towards negative. The weights add up, and a sigmoid turns the total into a probability. But look at the last sentence. Not bad at all is actually positive, yet word by word it looks negative. Negation is hard.' },
      { kit: 'pipeline', head: 'Building a text classifier', steps: ['Labelled texts', 'Features', 'Train', 'Evaluate'], desc: ['Thousands of reviews tagged positive or negative.', 'TF-IDF counts, or better, embeddings from a pre-trained model.', 'Logistic regression, or fine-tune a Transformer.', 'Accuracy, precision and recall on held-out data.'], chapter: 'The recipe', say: 'The recipe: collect labelled texts, turn them into features, TF-IDF or embeddings from a pre-trained model, train a classifier, and evaluate it on held-out data.' },
      { kit: 'compare', head: 'Classic vs modern', left: { title: 'Classic', items: ['TF-IDF + logistic regression', 'Fast, explainable', 'Misses negation and sarcasm'], color: 'amber' }, right: { title: 'Modern', items: ['Fine-tuned BERT-style model', 'Understands context: “not bad”', 'Needs more compute'], color: 'blue' }, chapter: 'Classic vs modern', say: 'Classic models are fast and explainable, but miss negation and sarcasm. Fine-tuned Transformer models read words in context, so they understand that not bad means good.' },
      { kit: 'bullets', head: 'Real-world uses', items: ['Customer reviews and support tickets', 'Spam and toxic-content filtering', 'Routing emails to the right team', 'Tracking opinion on social media'], chapter: 'Uses', say: 'Text classification powers review analysis, spam and toxicity filters, routing emails and support tickets, and tracking public opinion.' },
      { kit: 'bullets', style: 'recap', items: ['Sentiment = classifying the feeling of a text', 'Word evidence adds up into a probability', 'Negation and sarcasm need context', 'Fine-tuned Transformers are the modern standard'], chapter: 'Recap', say: 'To recap. Sentiment analysis classifies feelings. Word evidence adds up into a probability, context handles negation, and fine-tuned Transformers are today’s standard.' }
    ],
    takeaways: ['Sentiment analysis is text classification into positive/negative (or more classes).', 'Simple models add word weights and apply a sigmoid.', 'Negation (“not bad”) and sarcasm require context.', 'Fine-tuned Transformers handle context far better than bag-of-words models.'],
    quiz: [
      { q: 'Why is “Not bad at all” difficult for a word-weight model?', a: ['Individual words look negative but the phrase is positive', 'It is too long', 'It has no words'], c: 0, why: 'Negation flips meaning; context is needed.' },
      { q: 'What turns the summed word weights into a probability?', a: ['A sigmoid', 'A pooling layer', 'Tokenization'], c: 0, why: 'The sigmoid squashes the total into 0–1.' },
      { q: 'Which approach best understands context?', a: ['A fine-tuned Transformer model', 'Counting exclamation marks', 'A fixed word list'], c: 0, why: 'Transformers represent words in context.' }
    ],
    read: ['sentiment-analysis', 'text-classification', 'fine-tuning-pretrained-language-models']
  },
  {
    slug: 'named-entity-recognition', title: 'Named Entity Recognition', track: 'nlp', level: 'Beginner',
    summary: 'Find people, organisations, places and dates in text and tag every token with BIO labels.',
    scenes: [
      { kit: 'title', title: 'Named Entity Recognition', sub: 'Finding who, what, where and when', track: 'Natural Language Processing', chapter: 'Introduction', say: 'News articles, contracts and medical notes are full of names, places and dates. Named entity recognition finds them automatically.' },
      { kit: 'ner', chapter: 'Tagging entities', say: 'Here the model reads a sentence and labels each token. Ada Lovelace is a person, Charles Babbage is another person, London is a location and 1843 is a date. Each token gets a BIO tag. B marks the beginning of an entity, I marks its continuation, and O means outside any entity.' },
      { kit: 'bullets', head: 'Why it is a sequence problem', items: ['Labels depend on neighbours: “New” + “York” = one place', 'The same word can be different types: “Apple” the company or the fruit', 'Models read the whole sentence before deciding', 'Classic: CRFs; modern: fine-tuned Transformers'], chapter: 'A sequence problem', say: 'NER is a sequence labelling problem. A token’s label depends on its neighbours: New York is one place. The same word can be a company or a fruit. So models read the whole sentence, from classic conditional random fields to modern fine-tuned Transformers.' },
      { kit: 'bullets', head: 'Where NER is used', items: ['Search — understand queries like “flights to Dhaka”', 'Finance and law — extract parties, amounts and dates', 'Healthcare — find drugs, doses and symptoms', 'Knowledge graphs — connect people, places and events'], chapter: 'Applications', say: 'NER helps search engines understand queries, extracts parties and amounts from legal and financial documents, finds drugs and symptoms in medical notes, and builds knowledge graphs.' },
      { kit: 'bullets', style: 'recap', items: ['NER labels people, organisations, locations, dates…', 'BIO tags: Begin, Inside, Outside', 'Context decides the type of ambiguous words', 'Fine-tuned Transformers are state of the art'], chapter: 'Recap', say: 'To recap. NER labels entities in text using BIO tags. Context decides ambiguous cases, and fine-tuned Transformers are the modern approach.' }
    ],
    takeaways: ['NER finds and classifies entities such as people, organisations, locations and dates.', 'BIO tagging marks the Beginning, Inside and Outside of entities.', 'It is a sequence labelling task where context resolves ambiguity.', 'Modern systems fine-tune Transformer models; classic ones used CRFs.'],
    quiz: [
      { q: 'In BIO tagging, what does “I-LOC” mean?', a: ['A token inside (continuing) a location', 'The first token of a location', 'Not an entity'], c: 0, why: 'I = inside, continuing an entity.' },
      { q: 'Why is “Apple” hard for NER?', a: ['It can be a company or a fruit', 'It is too short', 'It is always a place'], c: 0, why: 'The entity type depends on context.' },
      { q: 'Which tag is given to tokens that are not part of any entity?', a: ['O', 'B', 'X'], c: 0, why: 'O means outside.' }
    ],
    read: ['named-entity-recognition', 'pos-tagging-and-crf']
  },
  {
    slug: 'sequence-to-sequence-translation', title: 'Sequence-to-Sequence Models and Translation', track: 'nlp', level: 'Intermediate',
    summary: 'An encoder reads a sentence, a decoder writes the translation — and attention lets it look back at exactly the right words.',
    scenes: [
      { kit: 'title', title: 'Sequence to Sequence', sub: 'How neural machine translation works', track: 'Natural Language Processing', chapter: 'Introduction', say: 'Translation turns one sequence into another, of a different length and word order. Sequence to sequence models, introduced around 2014, made neural translation practical.' },
      { kit: 'seq2seq', chapter: 'Encoder and decoder', say: 'The encoder reads the English sentence word by word and compresses it into a context vector. The decoder then writes the French translation one word at a time: le chat noir dort. Notice that the order changes: black cat becomes chat noir.' },
      { kit: 'bullets', head: 'The bottleneck problem', items: ['The whole sentence is squeezed into one vector', 'Long sentences lose information', 'Translation quality drops as sentences get longer'], chapter: 'The bottleneck', say: 'But squeezing a whole sentence into one fixed vector is a bottleneck. For long sentences, information gets lost, and translation quality drops.' },
      { kit: 'seq2seq', mode: 'attention', chapter: 'Adding attention', say: 'Attention fixes the bottleneck. At every step, the decoder looks back at all the encoder states and decides which to focus on. When writing chat, it attends to cat. When writing noir, it attends to black. The word order problem solves itself.' },
      { kit: 'bullets', head: 'From seq2seq to Transformers', items: ['2014 — encoder–decoder RNNs', '2015 — attention added to translation', '2017 — the Transformer: attention everywhere, no RNNs', 'Today — models like T5 and many translation systems are encoder–decoder Transformers'], chapter: 'What came next', say: 'Attention was so useful that the 2017 Transformer kept only attention and dropped the recurrent networks. Encoder decoder Transformers such as T5 are still used for translation and summarisation.' },
      { kit: 'bullets', style: 'recap', items: ['Encoder reads, decoder writes', 'One fixed vector is a bottleneck', 'Attention lets the decoder look back at every input word', 'This idea led to the Transformer'], chapter: 'Recap', say: 'To recap. The encoder reads, the decoder writes. A single context vector is a bottleneck. Attention lets the decoder look back at every word, and that idea led straight to the Transformer.' }
    ],
    takeaways: ['Seq2seq models use an encoder to read and a decoder to generate.', 'A single fixed context vector limits quality on long sentences.', 'Attention lets the decoder focus on relevant source words at every step.', 'The Transformer (2017) built an entire architecture from attention.'],
    quiz: [
      { q: 'What does the encoder do?', a: ['Reads the source sentence into representations', 'Writes the translation', 'Counts words'], c: 0, why: 'The encoder processes the input sequence.' },
      { q: 'What problem does attention solve in seq2seq models?', a: ['The fixed-size bottleneck vector', 'Tokenization', 'Overfitting'], c: 0, why: 'The decoder can look at all encoder states directly.' },
      { q: 'When writing “noir”, the decoder should attend mostly to…', a: ['black', 'the', 'sleeps'], c: 0, why: '“Noir” translates “black”.' }
    ],
    read: ['sequence-to-sequence-models', 'neural-machine-translation', 'attention-mechanism']
  },
  {
    slug: 'positional-encoding', title: 'Positional Encoding: Teaching Transformers Word Order', track: 'nlp', level: 'Intermediate',
    summary: 'Attention ignores order, so Transformers add position information. See the sine-and-cosine pattern that gives every position a unique fingerprint.',
    scenes: [
      { kit: 'title', title: 'Positional Encoding', sub: 'How Transformers know word order', track: 'Natural Language Processing', chapter: 'Introduction', say: 'Attention compares every word with every other word, but on its own it has no idea which word came first. Dog bites man and man bites dog would look the same. Positional encodings fix that.' },
      { kit: 'posenc', chapter: 'Waves of different speeds', say: 'The original Transformer adds a pattern of sine and cosine waves to each word’s embedding. Early dimensions oscillate quickly, later ones slowly, like the hands of a clock. Together they give every position a unique fingerprint, shown as one row of this heat map.' },
      { kit: 'equation', head: 'The sinusoidal formula', size: 40, parts: [{ t: 'PE(pos, 2i)', c: 'amber', note: 'Even dimensions of the encoding for position pos' }, { t: ' = ' }, { t: 'sin', c: 'pink', note: 'Even dimensions use sine; odd dimensions use cosine' }, { t: '(pos / 10000^(2i/d))', c: 'cyan', note: 'Each pair of dimensions has its own frequency; higher i means a slower wave' }], below: 'Relative offsets become simple rotations — easy for attention to use', chapter: 'The formula', say: 'Each pair of dimensions uses a sine and cosine at its own frequency, from fast to very slow. A neat property: moving a fixed number of positions corresponds to a rotation, so relative positions are easy for attention to detect.' },
      { kit: 'compare', head: 'Kinds of position information', left: { title: 'Absolute', items: ['Sinusoidal (original Transformer)', 'Learned position embeddings (BERT, GPT-2)', 'Added to token embeddings'], color: 'amber' }, right: { title: 'Relative', items: ['RoPE — rotates queries and keys (many modern LLMs)', 'ALiBi — penalises distant tokens', 'Often extend better to longer texts'], color: 'blue' }, chapter: 'Modern variants', say: 'Absolute encodings, sinusoidal or learned, give each position its own vector. Many modern language models use relative schemes instead, such as rotary embeddings, RoPE, or ALiBi, which often cope better with longer texts.' },
      { kit: 'bullets', style: 'recap', items: ['Attention alone is blind to word order', 'Positional encodings add order information', 'Sinusoidal: waves of many frequencies, unique per position', 'Modern LLMs often use RoPE or ALiBi'], chapter: 'Recap', say: 'To recap. Attention is blind to order, so we add positional information. Sinusoidal encodings use waves of many speeds, and modern models often use relative methods like RoPE.' }
    ],
    takeaways: ['Self-attention alone does not know the order of tokens.', 'The original Transformer adds sinusoidal positional encodings to embeddings.', 'Different dimensions use different frequencies, giving each position a unique pattern.', 'Many modern LLMs use relative schemes such as RoPE or ALiBi.'],
    quiz: [
      { q: 'Why do Transformers need positional encodings?', a: ['Attention by itself ignores word order', 'To reduce vocabulary size', 'To speed up tokenization'], c: 0, why: 'Without them, permuted sentences look identical.' },
      { q: 'In sinusoidal encodings, later dimensions…', a: ['Oscillate more slowly', 'Are always zero', 'Oscillate faster'], c: 0, why: 'Frequency decreases with the dimension index.' },
      { q: 'Which is a relative position method used by many modern LLMs?', a: ['RoPE', 'TF-IDF', 'Max pooling'], c: 0, why: 'Rotary position embeddings rotate queries and keys.' }
    ],
    read: ['positional-encodings-rope-alibi', 'transformer-architecture-explained', 'efficient-transformers-long-context']
  },
  {
    slug: 'bert-and-gpt', title: 'BERT and GPT: Two Kinds of Language Models', track: 'nlp', level: 'Intermediate',
    summary: 'BERT reads in both directions to understand; GPT reads left to right to generate. See their training games and attention masks.',
    scenes: [
      { kit: 'title', title: 'BERT and GPT', sub: 'Understanding vs generating', track: 'Natural Language Processing', chapter: 'Introduction', say: 'In 2018, two families of pre-trained Transformer models changed NLP: BERT and GPT. They share building blocks but play different training games.' },
      { kit: 'masked-lm', chapter: 'BERT fills in blanks', say: 'BERT is trained by hiding some words and predicting them. To guess the masked word, it uses context from both sides: the chef cooked a something dinner for us. Reading in both directions makes BERT excellent at understanding text.' },
      { kit: 'llm', prompt: 'Once upon a time', steps: [['there', [['there', .62], ['in', .21], [',', .1], ['a', .07]]], ['was', [['was', .71], ['lived', .22], ['were', .07]]], ['a', [['a', .64], ['an', .2], ['the', .16]]], ['robot', [['robot', .3], ['king', .28], ['girl', .25], ['dragon', .17]]]], head: 'GPT predicts the next token', sub: 'illustrative probabilities', chapter: 'GPT continues text', say: 'GPT is trained to predict the next token, reading only from left to right. That makes it a natural writer: give it a beginning and it continues, one token at a time.' },
      { kit: 'mask-compare', chapter: 'Attention masks', say: 'The difference shows up in the attention mask. In BERT, every word can attend to every other word. In GPT, a causal mask blocks the future: each word only sees the words before it. Otherwise the model could cheat by looking at the answer.' },
      { kit: 'compare', head: 'Which to use?', left: { title: 'BERT-style (encoder)', items: ['Classification, NER, search', 'Reads the whole input at once', 'Great embeddings for retrieval'], color: 'cyan' }, right: { title: 'GPT-style (decoder)', items: ['Chatbots, writing, code', 'Generates token by token', 'Scales into today’s large LLMs'], color: 'pink' }, chapter: 'Which one?', say: 'BERT-style encoders shine at classification, entity recognition and search embeddings. GPT-style decoders generate text, and scaled up, they became today’s large language models. Encoder decoder models like T5 combine both.' },
      { kit: 'bullets', style: 'recap', items: ['BERT: masked-word prediction, bidirectional', 'GPT: next-token prediction, left to right', 'Causal masks stop GPT from seeing the future', 'Encoders understand, decoders generate'], chapter: 'Recap', say: 'To recap. BERT fills in blanks using both directions. GPT predicts the next token using only the past. Encoders understand, decoders generate.' }
    ],
    takeaways: ['BERT is pre-trained with masked language modelling and reads bidirectionally.', 'GPT is pre-trained to predict the next token, left to right.', 'GPT uses a causal attention mask so tokens cannot see the future.', 'Encoders suit understanding tasks; decoders suit generation.'],
    quiz: [
      { q: 'How is BERT pre-trained?', a: ['Predicting masked words using both sides of context', 'Predicting the next word only', 'Translating sentences'], c: 0, why: 'Masked language modelling is bidirectional.' },
      { q: 'What does a causal attention mask do?', a: ['Prevents tokens from attending to future tokens', 'Removes rare words', 'Doubles the context'], c: 0, why: 'Each position sees only earlier positions.' },
      { q: 'Which model type is best suited to writing new text?', a: ['GPT-style decoder', 'BERT-style encoder', 'TF-IDF'], c: 0, why: 'Decoders generate token by token.' }
    ],
    read: ['bert-explained', 'gpt-family-autoregressive-models', 't5-encoder-decoder-models']
  },
  {
    slug: 'semantic-search', title: 'Semantic Search with Embeddings', track: 'nlp', level: 'Intermediate',
    summary: 'Search by meaning, not matching words. Embed documents and queries, then find the nearest neighbours.',
    scenes: [
      { kit: 'title', title: 'Semantic Search', sub: 'Finding answers by meaning', track: 'Natural Language Processing', chapter: 'Introduction', say: 'Keyword search fails when people use different words for the same thing. Semantic search matches meaning instead.' },
      { kit: 'vector-search', chapter: 'Nearest neighbours', say: 'Every help article is embedded as a vector, a point in meaning space. The query, I can’t sign in, shares no words with reset your password or forgot login details. But its embedding lands right next to them, so they are returned as the top results.' },
      { kit: 'pipeline', head: 'Building semantic search', steps: ['Chunk documents', 'Embed chunks', 'Store vectors', 'Embed the query', 'Rank by similarity'], desc: ['Split long documents into passages.', 'Run each passage through an embedding model.', 'Keep the vectors in a vector database with an index.', 'Embed the user’s question with the same model.', 'Return the passages with the highest cosine similarity.'], chapter: 'The recipe', say: 'Split documents into passages, embed them, and store the vectors in a vector database. At query time, embed the question with the same model and return the passages with the highest cosine similarity.' },
      { kit: 'compare', head: 'Keyword vs semantic', left: { title: 'Keyword (e.g. BM25)', items: ['Exact word matches', 'Great for names, codes, rare terms', 'Misses synonyms'], color: 'amber' }, right: { title: 'Semantic (embeddings)', items: ['Matches meaning and paraphrases', 'Works across wording and even languages', 'Can miss exact identifiers'], color: 'blue' }, chapter: 'Hybrid search', say: 'Keyword search is still great for exact names and codes. Semantic search handles paraphrases. Many real systems combine both, a hybrid search, and add a re-ranking model on top.' },
      { kit: 'bullets', style: 'recap', items: ['Embed documents and queries in the same space', 'Nearest neighbours = most similar meaning', 'Vector databases make search fast at scale', 'Hybrid keyword + semantic search works best'], chapter: 'Recap', say: 'To recap. Embed documents and queries, find the nearest neighbours, use a vector database for speed, and combine with keyword search for the best results. This is also the first half of retrieval augmented generation.' }
    ],
    takeaways: ['Semantic search embeds queries and documents and ranks by vector similarity.', 'It finds relevant text even without shared words.', 'Vector databases index embeddings for fast nearest-neighbour search.', 'Hybrid search combines keyword precision with semantic recall.'],
    quiz: [
      { q: 'Why did “Reset your password” match “I can’t sign in”?', a: ['Their embeddings are close in meaning', 'They share many words', 'Alphabetical order'], c: 0, why: 'Semantic search compares meaning via vectors.' },
      { q: 'What must be true of the query and document embeddings?', a: ['Produced by the same (compatible) embedding model', 'Different models for each', 'Stored as text only'], c: 0, why: 'Otherwise the vectors are not comparable.' },
      { q: 'When is keyword search still better?', a: ['Exact identifiers like product codes and names', 'Paraphrased questions', 'Different languages'], c: 0, why: 'Exact matches matter for rare identifiers.' }
    ],
    read: ['semantic-search-information-retrieval', 'vector-databases', 'question-answering-systems']
  },
  {
    slug: 'speech-recognition', title: 'Speech Recognition: From Sound to Text', track: 'nlp', level: 'Intermediate',
    summary: 'How a voice becomes words: waveforms, spectrograms and neural models that turn frequency patterns into text.',
    scenes: [
      { kit: 'title', title: 'Speech Recognition', sub: 'Turning sound waves into words', track: 'Natural Language Processing', chapter: 'Introduction', say: 'Voice assistants, live captions and dictation all start by turning sound into text. That is automatic speech recognition.' },
      { kit: 'spectrogram', chapter: 'Waveform to spectrogram', say: 'A microphone records a waveform: air pressure changing thousands of times per second. Hard to read directly. So we compute a spectrogram, which shows how much energy each frequency has over time. Speech sounds appear as distinctive patterns. A neural network reads these patterns and outputs words.' },
      { kit: 'pipeline', head: 'A modern speech recognition system', steps: ['Audio', 'Spectrogram', 'Encoder', 'Decoder', 'Text'], desc: ['Record sound, often at 16,000 samples per second.', 'Convert short overlapping windows into frequency features (mel spectrogram).', 'A Transformer or convolutional encoder builds acoustic representations.', 'A decoder or CTC layer turns them into tokens.', 'Words with punctuation, sometimes timestamps.'], chapter: 'The pipeline', say: 'Modern systems convert audio into a mel spectrogram, an encoder builds acoustic representations, and a decoder turns them into text tokens. Models such as Whisper are trained on huge amounts of transcribed audio.' },
      { kit: 'bullets', head: 'What makes speech hard', items: ['Accents and dialects', 'Background noise and overlapping speakers', 'Homophones: “there”, “their”, “they’re”', 'Low-resource languages with little training data'], chapter: 'Challenges', say: 'Speech is hard because of accents, background noise, overlapping speakers and words that sound alike. Many languages also have little transcribed training data, which makes them harder to support.' },
      { kit: 'bullets', style: 'recap', items: ['Waveform → spectrogram → neural model → text', 'Spectrograms show frequency energy over time', 'Encoder–decoder Transformers are common', 'Accents, noise and data scarcity remain challenges'], chapter: 'Recap', say: 'To recap. Sound becomes a spectrogram, a neural model turns frequency patterns into text, and accents, noise and data scarcity are the big challenges.' }
    ],
    takeaways: ['Speech recognition converts audio into text.', 'Spectrograms show the energy of each frequency over time.', 'Modern systems use neural encoders and decoders on mel spectrograms.', 'Accents, noise and low-resource languages are major challenges.'],
    quiz: [
      { q: 'What does a spectrogram show?', a: ['Energy at each frequency over time', 'The words spoken', 'The speaker’s name'], c: 0, why: 'It is a time–frequency picture of sound.' },
      { q: 'Which is a common input representation for speech models?', a: ['Mel spectrogram', 'TF-IDF vector', 'Bounding boxes'], c: 0, why: 'Mel spectrograms mimic human hearing.' },
      { q: 'Which is a major challenge for speech recognition?', a: ['Background noise and accents', 'Too few frequencies', 'Tokens being too long'], c: 0, why: 'Real audio is noisy and varied.' }
    ],
    read: ['automatic-speech-recognition', 'text-to-speech-synthesis', 'multilingual-low-resource-nlp']
  }
];
